package analyzer

import (
	"github.com/kimjooyoon/meta-ontology-go/internal/semantic"
	"runtime"
	"strings"
	"testing"
)

func TestGeneratedBillingByteMutationFailsReconcileWithoutWrite(t *testing.T) {
	source := generatedBillingSource(t)
	policy := generatedBillingPolicy(t)
	registry := generatedBillingRegistry(t)
	base := semantic.NewIR("billing", semantic.Namespace("billing"))
	before := irSnapshot(base)
	mutated := source
	mutated.Source = []byte(strings.Replace(
		string(source.Source), "type Order struct{}", "type Order struct{ _ byte }", 1,
	))
	first, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{source}, Registry: registry, Policy: policy,
		Producer: semantic.GoHostedCompilerID, EvidenceKind: semantic.CompilerRunEvidence,
		ToolchainIdentity: "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH,
	})
	if err != nil {
		t.Fatal(err)
	}
	second, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{mutated}, Registry: registry, Policy: policy,
		Producer: semantic.GoHostedCompilerID, EvidenceKind: semantic.CompilerRunEvidence,
		ToolchainIdentity: "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH,
	})
	if err != nil {
		t.Fatal(err)
	}
	reconcile := ReconcileSemantic(second, first.IR, first.SourceDigest, first.PolicyDigest,
		first.ToolchainDigest, first.ImplementationObservationDigest)
	if reconcile.SourceMatch || reconcile.ObservationMatch || reconcile.Accepted {
		t.Fatal("mutated generated bytes passed source-bound reconcile")
	}
	if first.ImplementationObservationDigest == second.ImplementationObservationDigest ||
		first.ImplementationObservations[0].Fingerprint() == second.ImplementationObservations[0].Fingerprint() {
		t.Fatal("generated body mutation did not change implementation observation digest")
	}
	if got := irSnapshot(base); got != before {
		t.Fatalf("base IR changed after rejected reconcile: before=%q after=%q", before, got)
	}
}
func TestGeneratedBillingWrongIdentityFailsReconcileWithoutWrite(t *testing.T) {
	source := generatedBillingSource(t)
	policy := generatedBillingPolicy(t)
	base := semantic.NewIR("billing", semantic.Namespace("billing"))
	before := irSnapshot(base)
	wrong := generatedBillingRegistryWithOrder(t, "billing://entity/wrong-order")
	observed, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{source}, Registry: wrong, Policy: policy,
		Producer: semantic.GoHostedCompilerID, EvidenceKind: semantic.CompilerRunEvidence,
		ToolchainIdentity: "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH,
	})
	if err != nil {
		t.Fatal(err)
	}
	expected := declaredBillingContract(t)
	reconcile := ReconcileSemantic(observed, expected, observed.SourceDigest, policy.Digest(),
		observed.ToolchainDigest, observed.ImplementationObservationDigest)
	if reconcile.Comparison.SemanticEqual || reconcile.Accepted {
		t.Fatal("wrong registered semantic identity reconciled as billing contract")
	}
	if got := irSnapshot(base); got != before {
		t.Fatalf("base IR changed after wrong identity: before=%q after=%q", before, got)
	}
}
