package analyzer

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/kimjooyoon/meta-ontology-go/internal/semantic"
)

func TestGeneratedBillingProjectionLiftsAgainstDeclaredContract(t *testing.T) {
	source := generatedBillingSource(t)
	policy := generatedBillingPolicy(t)
	registry := generatedBillingRegistry(t)
	base := semantic.NewIR("billing", semantic.Namespace("billing"))
	toolchain := "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH
	input := SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{source}, Registry: registry, Policy: policy,
		Producer: semantic.GoHostedCompilerID, EvidenceKind: semantic.CompilerRunEvidence,
		ToolchainIdentity: toolchain,
	}
	adapted, err := AnalyzeAndAdaptSemantic(input)
	if err != nil {
		t.Fatalf("lift generated billing projection: %v", err)
	}
	delta, err := AnalyzePackage([]SourceFile{source}, registry)
	if err != nil {
		t.Fatalf("analyze generated billing projection: %v", err)
	}
	if len(delta.Delta.Added) != 4 || len(delta.Delta.Candidates) != 0 {
		t.Fatalf("generated delta = %#v, want four facts and no candidates", delta.Delta)
	}
	for _, fact := range delta.Delta.Added[:3] {
		if fact.Origin != OriginSignature {
			t.Fatalf("contract fact origin = %q, want signature", fact.Origin)
		}
	}
	if delta.Delta.Added[3].Origin != OriginImplementation {
		t.Fatalf("implementation fact origin = %q, want implementation", delta.Delta.Added[3].Origin)
	}
	expected := declaredBillingContract(t)
	reconcile := ReconcileSemantic(adapted, expected, adapted.SourceDigest, policy.Digest(),
		ToolchainDigest(toolchain), "")
	if !reconcile.Comparison.SemanticEqual {
		t.Fatalf("lifted semantic facts do not match DSL contract: %#v", reconcile.Comparison)
	}
	if reconcile.Accepted || reconcile.Comparison.ProvenanceEqual {
		t.Fatal("synthetic or absent external provenance was accepted")
	}
	if len(adapted.IR.Graph.DeterministicFacts()) != 3 {
		t.Fatalf("authoritative facts = %d, want 3", len(adapted.IR.Graph.DeterministicFacts()))
	}
	if len(adapted.DeferredFacts) != 1 || adapted.DeferredFacts[0].Origin != OriginImplementation {
		t.Fatalf("implementation observation was not deferred: %#v", adapted.DeferredFacts)
	}
	if len(adapted.ImplementationObservations) != 1 {
		t.Fatalf("implementation observations = %d, want 1", len(adapted.ImplementationObservations))
	}
	observation := adapted.ImplementationObservations[0]
	if observation.SourceFile != source.Filename || observation.BaseDigest != base.StableHash() {
		t.Fatalf("implementation observation binding = %#v", observation)
	}
	if observation.Fingerprint() == "" || !validDigest(adapted.ImplementationObservationDigest) {
		t.Fatalf("missing implementation observation digest: %#v", adapted)
	}
	if len(adapted.DeferredCandidates) != 0 || len(adapted.ImplementationDetails) != 0 {
		t.Fatalf("generated projection produced unexpected candidate/detail evidence")
	}
	if !validDigest(adapted.SourceDigest) || !validDigest(adapted.BindingDigest) {
		t.Fatalf("missing source binding: source=%q binding=%q", adapted.SourceDigest, adapted.BindingDigest)
	}
	digest, err := SourceBundleDigest([]SourceFile{source})
	if err != nil || adapted.SourceDigest != digest {
		t.Fatalf("source digest binding = %q, want %q (err=%v)", adapted.SourceDigest, digest, err)
	}
	if err := adapted.IR.Validate(); err != nil {
		t.Fatalf("lifted IR invalid: %v", err)
	}
}

func TestGeneratedBillingByteMutationFailsReconcileWithoutWrite(t *testing.T) {
	source := generatedBillingSource(t)
	policy := generatedBillingPolicy(t)
	registry := generatedBillingRegistry(t)
	base := semantic.NewIR("billing", semantic.Namespace("billing"))
	before := irSnapshot(base)
	mutated := source
	mutated.Source = []byte(strings.Replace(
		string(source.Source), "type Order struct{}", "type Order struct{ _ byte }", 1,
	))
	first, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{source}, Registry: registry, Policy: policy,
		Producer: semantic.GoHostedCompilerID, EvidenceKind: semantic.CompilerRunEvidence,
		ToolchainIdentity: "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH,
	})
	if err != nil {
		t.Fatal(err)
	}
	second, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{mutated}, Registry: registry, Policy: policy,
		Producer: semantic.GoHostedCompilerID, EvidenceKind: semantic.CompilerRunEvidence,
		ToolchainIdentity: "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH,
	})
	if err != nil {
		t.Fatal(err)
	}
	reconcile := ReconcileSemantic(second, first.IR, first.SourceDigest, first.PolicyDigest,
		first.ToolchainDigest, first.ImplementationObservationDigest)
	if reconcile.SourceMatch || reconcile.ObservationMatch || reconcile.Accepted {
		t.Fatal("mutated generated bytes passed source-bound reconcile")
	}
	if first.ImplementationObservationDigest == second.ImplementationObservationDigest ||
		first.ImplementationObservations[0].Fingerprint() == second.ImplementationObservations[0].Fingerprint() {
		t.Fatal("generated body mutation did not change implementation observation digest")
	}
	if got := irSnapshot(base); got != before {
		t.Fatalf("base IR changed after rejected reconcile: before=%q after=%q", before, got)
	}
}

func TestGeneratedBillingWrongIdentityFailsReconcileWithoutWrite(t *testing.T) {
	source := generatedBillingSource(t)
	policy := generatedBillingPolicy(t)
	base := semantic.NewIR("billing", semantic.Namespace("billing"))
	before := irSnapshot(base)
	wrong := generatedBillingRegistryWithOrder(t, "billing://entity/wrong-order")
	observed, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{source}, Registry: wrong, Policy: policy,
		Producer: semantic.GoHostedCompilerID, EvidenceKind: semantic.CompilerRunEvidence,
		ToolchainIdentity: "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH,
	})
	if err != nil {
		t.Fatal(err)
	}
	expected := declaredBillingContract(t)
	reconcile := ReconcileSemantic(observed, expected, observed.SourceDigest, policy.Digest(),
		observed.ToolchainDigest, observed.ImplementationObservationDigest)
	if reconcile.Comparison.SemanticEqual || reconcile.Accepted {
		t.Fatal("wrong registered semantic identity reconciled as billing contract")
	}
	if got := irSnapshot(base); got != before {
		t.Fatalf("base IR changed after wrong identity: before=%q after=%q", before, got)
	}
}

func TestGeneratedBillingDuplicateFilenameRejectsBeforeWrite(t *testing.T) {
	source := generatedBillingSource(t)
	base := semantic.NewIR("billing", semantic.Namespace("billing"))
	before := irSnapshot(base)
	_, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{source, source}, Registry: generatedBillingRegistry(t),
		Policy: generatedBillingPolicy(t), Producer: semantic.GoHostedCompilerID,
		EvidenceKind: semantic.CompilerRunEvidence, ToolchainIdentity: "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH,
	})
	var adapterErr AdapterError
	if !errors.As(err, &adapterErr) || adapterErr.Code != AdapterSourceConfig {
		t.Fatalf("duplicate filename error = %v, want source-config", err)
	}
	if got := irSnapshot(base); got != before {
		t.Fatalf("base IR changed after duplicate filename: before=%q after=%q", before, got)
	}
}

func TestGeneratedBillingParseFailureDoesNotWrite(t *testing.T) {
	source := generatedBillingSource(t)
	source.Source = []byte("package billing\nfunc broken(\n")
	base := semantic.NewIR("billing", semantic.Namespace("billing"))
	before := irSnapshot(base)
	_, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{source}, Registry: generatedBillingRegistry(t),
		Policy: generatedBillingPolicy(t), Producer: semantic.GoHostedCompilerID,
		EvidenceKind:      semantic.CompilerRunEvidence,
		ToolchainIdentity: "go1.26.5|" + runtime.GOOS + "/" + runtime.GOARCH,
	})
	if err == nil {
		t.Fatal("invalid generated source was accepted")
	}
	if got := irSnapshot(base); got != before {
		t.Fatalf("base IR changed after parse failure: before=%q after=%q", before, got)
	}
}

func TestGeneratedBillingConfigFailureDoesNotWrite(t *testing.T) {
	source := generatedBillingSource(t)
	base := semantic.NewIR("billing", semantic.Namespace("billing"))
	before := irSnapshot(base)
	_, err := AnalyzeAndAdaptSemantic(SourceSemanticAdapterInput{
		Base: base, Sources: []SourceFile{source}, Registry: generatedBillingRegistry(t),
		Policy: generatedBillingPolicy(t), Producer: semantic.GoHostedCompilerID,
		EvidenceKind: semantic.CompilerRunEvidence,
	})
	var adapterErr AdapterError
	if !errors.As(err, &adapterErr) || adapterErr.Code != AdapterSourceConfig {
		t.Fatalf("missing toolchain error = %v, want source-config", err)
	}
	if got := irSnapshot(base); got != before {
		t.Fatalf("base IR changed after config failure: before=%q after=%q", before, got)
	}
}

func generatedBillingSource(t *testing.T) SourceFile {
	t.Helper()
	root, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root = filepath.Clean(filepath.Join(root, "..", ".."))
	out := t.TempDir()
	command := exec.Command("go", "run", "./cmd/gooo", "generate", "examples/billing/main.gooo", "--out", out)
	command.Dir = root
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("generate billing projection: %v\n%s", err, output)
	}
	projection, err := os.ReadFile(filepath.Join(out, "semantic.gooo.go"))
	if err != nil {
		t.Fatalf("read generated billing projection: %v", err)
	}
	return SourceFile{Filename: "semantic.gooo.go", PackagePath: "billing", Source: projection}
}

func generatedBillingRegistry(t *testing.T) *Registry {
	t.Helper()
	return generatedBillingRegistryWithOrder(t, "billing://entity/order")
}

func generatedBillingRegistryWithOrder(t *testing.T, orderID string) *Registry {
	t.Helper()
	registry := NewRegistry()
	for _, entry := range []Registration{
		{Ref: billingRef("PayOrder"), Kind: KindActivity, Identity: NewIdentity("billing", "billing://activity/pay-order")},
		{Ref: billingRef("Order"), Kind: KindEntity, Identity: NewIdentity("billing", orderID)},
		{Ref: billingRef("PaymentMethod"), Kind: KindEntity,
			Identity: NewIdentity("billing", "billing://entity/payment-method")},
		{Ref: billingRef("Payment"), Kind: KindEntity, Identity: NewIdentity("billing", "billing://entity/payment")},
	} {
		if err := registry.Register(entry); err != nil {
			t.Fatal(err)
		}
	}
	return registry
}

func generatedBillingPolicy(t *testing.T) MappingPolicy {
	t.Helper()
	policy, err := NewMappingPolicy(CurrentSemanticAdapterPolicy)
	if err != nil {
		t.Fatal(err)
	}
	for _, mapping := range []RelationMapping{
		{Source: RelationUses, Predicate: semantic.Used,
			SourceSubjectKind: semantic.Activity, SourceObjectKind: semantic.Entity,
			AllowedOrigins: []ObservationOrigin{OriginSignature}},
		{Source: RelationGenerates, Predicate: semantic.WasGeneratedBy,
			SourceSubjectKind: semantic.Activity, SourceObjectKind: semantic.Entity,
			Reverse: true, AllowedOrigins: []ObservationOrigin{OriginSignature}},
	} {
		if err := policy.Register(mapping); err != nil {
			t.Fatal(err)
		}
	}
	return policy
}

func declaredBillingContract(t *testing.T) semantic.IR {
	t.Helper()
	ir := semantic.NewIR("billing", semantic.Namespace("billing"))
	activity := mustBillingNode(t, semantic.Activity, "billing://activity/pay-order", "PayOrder")
	order := mustBillingNode(t, semantic.Entity, "billing://entity/order", "Order")
	method := mustBillingNode(t, semantic.Entity, "billing://entity/payment-method", "PaymentMethod")
	payment := mustBillingNode(t, semantic.Entity, "billing://entity/payment", "Payment")
	for _, node := range []semantic.Node{activity, order, method, payment} {
		if err := ir.AddNode(node); err != nil {
			t.Fatal(err)
		}
	}
	if err := ir.AddActivityContract(semantic.ActivityContract{
		Activity: activity.ID, Inputs: []semantic.ID{order.ID, method.ID}, Outputs: []semantic.ID{payment.ID},
	}); err != nil {
		t.Fatal(err)
	}
	return ir
}

func mustBillingNode(t *testing.T, kind semantic.Kind, id, name string) semantic.Node {
	t.Helper()
	node, err := semantic.NewNode(kind, semantic.MustIdentity(id), semantic.Namespace("billing"), name)
	if err != nil {
		t.Fatal(err)
	}
	return node
}

func billingRef(name string) SymbolRef {
	return SymbolRef{PackagePath: "billing", PackageName: "billing", Name: name}
}
