// Code generated by gooo receipt-schema; DO NOT EDIT.
// Projection profile: gooo/receipt-structure-projection/v1
package completeness

const CompletenessReceiptSchema = "gooo/metaprogramming-completeness-receipt/v2"
const DeclarationSHA256 = "c7059936a1fe6b98d6129e9a90a38d09779e8aaa5575868c703ff8a089d184ae"
const ProjectionProfile = "gooo/receipt-structure-projection/v1"

//gooo:generated:start id="gooo://completeness/entity/dimension" kind="entity"
type CompletenessDimension struct {
	ID          string   `json:"id" gooo:"gooo://completeness/field/dimension/id"`
	Status      string   `json:"status" gooo:"gooo://completeness/field/dimension/status"`
	Numerator   int      `json:"numerator" gooo:"gooo://completeness/field/dimension/numerator"`
	Denominator int      `json:"denominator" gooo:"gooo://completeness/field/dimension/denominator"`
	Unit        string   `json:"unit" gooo:"gooo://completeness/field/dimension/unit"`
	Reason      string   `json:"reason" gooo:"gooo://completeness/field/dimension/reason"`
	Evidence    []string `json:"evidence" gooo:"gooo://completeness/field/dimension/evidence"`
}

//gooo:generated:end id="gooo://completeness/entity/dimension" kind="entity"

//gooo:generated:start id="gooo://completeness/entity/unresolved-claim" kind="entity"
type UnresolvedCompletenessClaim struct {
	ID            string `json:"id" gooo:"gooo://completeness/field/claim/id"`
	Status        string `json:"status" gooo:"gooo://completeness/field/claim/status"`
	Reason        string `json:"reason" gooo:"gooo://completeness/field/claim/reason"`
	NextOperation string `json:"next_operation" gooo:"gooo://completeness/field/claim/next-operation"`
}

//gooo:generated:end id="gooo://completeness/entity/unresolved-claim" kind="entity"

//gooo:generated:start id="gooo://schema/metaprogramming-completeness-receipt/v2" kind="entity"
type CompletenessReceipt struct {
	Schema                     string                        `json:"schema" gooo:"gooo://completeness/field/receipt/schema"`
	ProfileID                  string                        `json:"profile_id" gooo:"gooo://completeness/field/receipt/profile"`
	Decision                   string                        `json:"decision" gooo:"gooo://completeness/field/receipt/decision"`
	DecisionBasis              string                        `json:"decision_basis" gooo:"gooo://completeness/field/receipt/decision-basis"`
	Scope                      map[string]any                `json:"scope" gooo:"gooo://completeness/field/receipt/scope"`
	CoreDimensions             []string                      `json:"core_dimensions" gooo:"gooo://completeness/field/receipt/core-dimensions"`
	Dimensions                 []CompletenessDimension       `json:"dimensions" gooo:"gooo://completeness/field/receipt/dimensions"`
	StatusCounts               map[string]int                `json:"status_counts" gooo:"gooo://completeness/field/receipt/status-counts"`
	AggregateCompletenessScore *float64                      `json:"aggregate_completeness_score" gooo:"gooo://completeness/field/receipt/aggregate-score"`
	FirstUnresolved            *UnresolvedCompletenessClaim  `json:"first_unresolved" gooo:"gooo://completeness/field/receipt/first-unresolved"`
	UnresolvedClaims           []UnresolvedCompletenessClaim `json:"unresolved_claims" gooo:"gooo://completeness/field/receipt/unresolved-claims"`
	NotClaimed                 []string                      `json:"not_claimed" gooo:"gooo://completeness/field/receipt/not-claimed"`
	FailClosedReason           *string                       `json:"fail_closed_reason" gooo:"gooo://completeness/field/receipt/fail-closed-reason"`
}

//gooo:generated:end id="gooo://schema/metaprogramming-completeness-receipt/v2" kind="entity"
