package adapter

// Observed contains producer output that the runner can compare without
// importing implementation-specific generator types.
type Observed struct {
	SemanticDigest  string    `json:"semantic_digest,omitempty"`
	SourceDigest    string    `json:"source_digest,omitempty"`
	RegionDigest    string    `json:"region_digest,omitempty"`
	ImportDigest    string    `json:"import_digest,omitempty"`
	SourceMapDigest string    `json:"source_map_digest,omitempty"`
	CacheKey        string    `json:"cache_key,omitempty"`
	Regions         []Region  `json:"regions,omitempty"`
	Slots           []Slot    `json:"slots,omitempty"`
	Imports         []Import  `json:"imports,omitempty"`
	SourceMap       []Mapping `json:"source_map,omitempty"`
	Delta           *Delta    `json:"delta,omitempty"`
}

// Region is one generated ownership boundary.
type Region struct {
	Kind       string `json:"kind"`
	SemanticID string `json:"semantic_id"`
	OwnerID    string `json:"owner_id,omitempty"`
	Start      int    `json:"start_offset"`
	End        int    `json:"end_offset"`
	BodyDigest string `json:"body_digest,omitempty"`
}

// Slot is a handwritten implementation boundary inside a region.
type Slot struct {
	ID         string `json:"slot_id"`
	OwnerID    string `json:"owner_id"`
	Start      int    `json:"start_offset"`
	End        int    `json:"end_offset"`
	BodyDigest string `json:"body_digest,omitempty"`
}

// Import is a canonical package binding.
type Import struct {
	Path   string   `json:"path"`
	Alias  string   `json:"alias,omitempty"`
	UsedBy []string `json:"used_by_ids,omitempty"`
}

// Mapping links a semantic identity to source and generated byte ranges.
type Mapping struct {
	SemanticID string `json:"semantic_id"`
	Kind       string `json:"kind"`
	Source     Range  `json:"source_range"`
	Generated  Range  `json:"generated_range"`
}

// Range is a half-open byte range.
type Range struct {
	Start int `json:"start_offset"`
	End   int `json:"end_offset"`
}

// Delta is the source-backed semantic change lifted from Go.
type Delta struct {
	Added      []Fact     `json:"added_facts,omitempty"`
	Removed    []Fact     `json:"removed_facts,omitempty"`
	Candidates []Fact     `json:"candidate_facts,omitempty"`
	Locality   []string   `json:"locality_ids,omitempty"`
	Conflicts  []Conflict `json:"conflicts,omitempty"`
}
