package adapter

// Observed contains producer output that the runner can compare without
// importing implementation-specific generator types.
type Observed struct {
	SemanticDigest  string    `json:"semantic_digest,omitempty"`
	SourceDigest    string    `json:"source_digest,omitempty"`
	RegionDigest    string    `json:"region_digest,omitempty"`
	ImportDigest    string    `json:"import_digest,omitempty"`
	SourceMapDigest string    `json:"source_map_digest,omitempty"`
	CacheKey        string    `json:"cache_key,omitempty"`
	Regions         []Region  `json:"regions,omitempty"`
	Slots           []Slot    `json:"slots,omitempty"`
	Imports         []Import  `json:"imports,omitempty"`
	SourceMap       []Mapping `json:"source_map,omitempty"`
	Delta           *Delta    `json:"delta,omitempty"`
}

// Region is one generated ownership boundary.
type Region struct {
	Kind       string `json:"kind"`
	SemanticID string `json:"semantic_id"`
	OwnerID    string `json:"owner_id,omitempty"`
	Start      int    `json:"start_offset"`
	End        int    `json:"end_offset"`
	BodyDigest string `json:"body_digest,omitempty"`
}

// Slot is a handwritten implementation boundary inside a region.
type Slot struct {
	ID         string `json:"slot_id"`
	OwnerID    string `json:"owner_id"`
	Start      int    `json:"start_offset"`
	End        int    `json:"end_offset"`
	BodyDigest string `json:"body_digest,omitempty"`
}

// Import is a canonical package binding.
type Import struct {
	Path   string   `json:"path"`
	Alias  string   `json:"alias,omitempty"`
	UsedBy []string `json:"used_by_ids,omitempty"`
}

// Mapping links a semantic identity to source and generated byte ranges.
type Mapping struct {
	SemanticID string `json:"semantic_id"`
	Kind       string `json:"kind"`
	Source     Range  `json:"source_range"`
	Generated  Range  `json:"generated_range"`
}

// Range is a half-open byte range.
type Range struct {
	Start int `json:"start_offset"`
	End   int `json:"end_offset"`
}

// Delta is the source-backed semantic change lifted from Go.
type Delta struct {
	Added      []Fact     `json:"added_facts,omitempty"`
	Removed    []Fact     `json:"removed_facts,omitempty"`
	Candidates []Fact     `json:"candidate_facts,omitempty"`
	Locality   []string   `json:"locality_ids,omitempty"`
	Conflicts  []Conflict `json:"conflicts,omitempty"`
}

// Fact is a compact semantic relation record.
type Fact struct {
	SubjectID string `json:"subject_id"`
	Predicate string `json:"predicate"`
	ObjectID  string `json:"object_id"`
	Class     string `json:"fact_class"`
	SourceURI string `json:"source_uri,omitempty"`
	Start     int    `json:"start_offset,omitempty"`
	End       int    `json:"end_offset,omitempty"`
}

// Conflict describes a rejected or unresolved semantic change.
type Conflict struct {
	Code       string `json:"code"`
	SemanticID string `json:"semantic_id,omitempty"`
	Detail     string `json:"detail,omitempty"`
}

// Measurements are correctness counts, not performance claims.
type Measurements struct {
	SourceSpanCount        int  `json:"source_span_count"`
	ProtectedBytesEqual    bool `json:"protected_bytes_equal"`
	UnrelatedRegionCount   int  `json:"unrelated_region_count"`
	NoWrite                bool `json:"no_write"`
	RepeatCount            int  `json:"repeat_count"`
	CanonicalEqualCount    int  `json:"canonical_equal_count"`
	SourceEqualCount       int  `json:"source_equal_count"`
	SemanticEqualCount     int  `json:"semantic_equal_count"`
	RegionEqualCount       int  `json:"region_equal_count"`
	SourceMapResolvedCount int  `json:"source_map_resolved_count"`
	FalseAcceptanceCount   int  `json:"false_acceptance_count"`
	EnvironmentLeakCount   int  `json:"environment_leak_count"`
}
