package generation

import (
	"errors"
	"fmt"
	"runtime"
	"strings"

	"github.com/kimjooyoon/meta-ontology-go/internal/cache"
	"github.com/kimjooyoon/meta-ontology-go/internal/meta/retentionpolicy"
)

const (
	SemanticRetentionCertificateSchema = "gooo/semantic-self-retention-certificate/v1"
	SemanticRetentionResultSchema      = "gooo/semantic-self-retention-result/v1"
	SemanticRetentionReportSchema      = "gooo/semantic-self-retention-report/v1"
	SemanticRetentionTarget            = SemanticAdoptionTarget
	SemanticRetentionMode              = "caller-owned-immutable-certificate"

	SemanticRetentionUnknownCertificateReason   = "MISSING_RETAINED_CERTIFICATE"
	SemanticRetentionUnknownAuthorizationReason = "MISSING_RETENTION_AUTHORIZATION"
	SemanticRetentionUnknownNext                = "PROVIDE_RETAINED_EVIDENCE"
	SemanticRetentionUnknownClass               = "INCOMPLETE_EVIDENCE"
	SemanticRetentionUnknownStage               = "RETENTION"
	SemanticRetentionUnknownCertificateStep     = "LOAD_CERTIFICATE"
	SemanticRetentionUnknownAuthorizationStep   = "AUTHORIZE_CERTIFICATE"
	SemanticRetentionRefutedReason              = "RETENTION_CERTIFICATE_MISMATCH"
	SemanticRetentionCertifiedReason            = "EXACT_RETAINED_KNOWLEDGE_CERTIFIED"
	SemanticRetentionHitReason                  = "EXACT_RETAINED_KNOWLEDGE_HIT"
	SemanticRetentionRefuted                    = "REFUTED"
	SemanticPublicGenerationReportSchema        = "gooo/semantic-public-generation-report/v1"
	SemanticPublicGenerationBaselineReason      = "PUBLIC_GENERATE_BASELINE"
	SemanticPublicGenerationHitReason           = "PUBLIC_GENERATE_RETAINED_KNOWLEDGE_HIT"
	SemanticPublicGenerationArtifactsClosed     = 4
	SemanticPublicGenerationArtifactsFailClosed = 2

	SemanticRetentionCaseDenominator  = 6
	SemanticRetentionArtifactsPerCase = 6
)

var semanticRetentionCaseIDs = [...]string{
	"CERTIFICATE_HIT",
	"CERTIFICATE_REPLAY",
	"MISSING_CERTIFICATE",
	"MISSING_AUTHORIZATION",
	"STALE_INPUT",
	"MISMATCHED_CERTIFICATE",
}

var semanticRetentionCompilerManifestPaths = [...]string{
	"cmd/gooo/generate_part01.go",
	"cmd/gooo/generate_pipeline_part01_part01.go",
	"cmd/gooo/generate_pipeline_part02_part01.go",
	"cmd/gooo/generate_pipeline_part03.go",
	"cmd/gooo/generate_pipeline_part04.go",
	"cmd/gooo/public_generation_part01.go",
	"cmd/gooo/public_generation_part02.go",
	"cmd/gooo/self_adoption_generation_part01.go",
	"cmd/gooo/self_retention_certify_part01.go",
	"cmd/gooo/self_retention_consume_part01.go",
	"cmd/gooo/self_retention_helpers_part01.go",
	"internal/meta/generation/semantic_public_generation.go",
	"internal/meta/generation/semantic_retention.go",
	"internal/meta/retentionpolicy/policy.go",
	"internal/meta/retentionpolicy/generated/evaluator.go",
}

var semanticRetentionVerifierManifestPaths = [...]string{
	"internal/meta/generation/semantic_retention.go",
	"internal/meta/generation/semantic_observation_verify.go",
	"scripts/self-improvement-public-generation/main.go",
	"scripts/self-improvement-retained-knowledge/main.go",
}

// SemanticRetentionCaseIDs returns the fixed six-case retained-knowledge
// denominator. Callers may not shrink or reorder this boundary.
func SemanticRetentionCaseIDs() []string {
	return append([]string(nil), semanticRetentionCaseIDs[:]...)
}

func SemanticRetentionCaseDecision(caseID string) (string, bool) {
	return retentionpolicy.Evaluate(caseID)
}

// SemanticRetentionCertificate is an immutable, caller-owned result of an
// explicitly authorized compiler operation. It carries the generated bytes
// so a later process can consume the exact result without process memory.
type SemanticRetentionCertificate struct {
	Schema                  string `json:"schema"`
	CertificateID           string `json:"certificate_id"`
	AdoptionReportDigest    string `json:"adoption_report_digest"`
	ObservationDigest       string `json:"observation_digest"`
	ProposalDigest          string `json:"proposal_digest"`
	AuthorizationDigest     string `json:"authorization_digest"`
	CandidateStableID       string `json:"candidate_stable_id"`
	Target                  string `json:"target"`
	Mode                    string `json:"mode"`
	ContractSourceDigest    string `json:"contract_source_digest"`
	InputSourceDigest       string `json:"input_source_digest"`
	NormalizedIRDigest      string `json:"normalized_ir_digest"`
	GeneratedOutputDigest   string `json:"generated_output_digest"`
	CompilerDigest          string `json:"compiler_digest"`
	ToolchainDigest         string `json:"toolchain_digest"`
	VerifierDigest          string `json:"verifier_digest"`
	PolicyDigest            string `json:"policy_digest"`
	EvaluatorDigest         string `json:"evaluator_digest"`
	GeneratedSource         []byte `json:"generated_source"`
	GeneratedManifest       []byte `json:"generated_manifest"`
	GeneratedManifestDigest string `json:"generated_manifest_digest"`
	RepositoryWrites        int    `json:"repository_writes"`
	LocalTestExecutions     int    `json:"local_test_executions"`
}

// SemanticRetentionCertificateContentDigest derives the certificate identity
// without a self-referential field.
func SemanticRetentionCertificateContentDigest(certificate SemanticRetentionCertificate) (string, error) {
	certificate.CertificateID = ""
	digest, err := cache.DigestOf(certificate)
	if err != nil {
		return "", fmt.Errorf("retention certificate content digest: %w", err)
	}
	return digest.String(), nil
}

func ValidateSemanticRetentionCertificate(certificate SemanticRetentionCertificate) error {
	if certificate.Schema != SemanticRetentionCertificateSchema ||
		!cache.Digest(certificate.CertificateID).Known() ||
		certificate.Target != SemanticRetentionTarget || certificate.Mode != SemanticRetentionMode ||
		certificate.CandidateStableID == "" || len(certificate.GeneratedSource) == 0 || len(certificate.GeneratedManifest) == 0 ||
		certificate.RepositoryWrites != 0 || certificate.LocalTestExecutions != 0 {
		return errors.New("semantic retention certificate is invalid")
	}
	for _, value := range []string{
		certificate.AdoptionReportDigest, certificate.ObservationDigest, certificate.ProposalDigest,
		certificate.AuthorizationDigest, certificate.ContractSourceDigest, certificate.InputSourceDigest,
		certificate.NormalizedIRDigest, certificate.GeneratedOutputDigest, certificate.CompilerDigest,
		certificate.ToolchainDigest, certificate.VerifierDigest, certificate.PolicyDigest, certificate.EvaluatorDigest,
	} {
		if !cache.Digest(value).Known() {
			return errors.New("semantic retention certificate contains unknown digest evidence")
		}
	}
	if cache.HashBytes(certificate.GeneratedSource).String() != certificate.GeneratedOutputDigest {
		return errors.New("semantic retention certificate generated output digest does not match bytes")
	}
	if !cache.Digest(certificate.GeneratedManifestDigest).Known() ||
		cache.HashBytes(certificate.GeneratedManifest).String() != certificate.GeneratedManifestDigest {
		return errors.New("semantic retention certificate generated manifest digest does not match bytes")
	}
	contentDigest, err := SemanticRetentionCertificateContentDigest(certificate)
	if err != nil {
		return err
	}
	if contentDigest != certificate.CertificateID {
		return errors.New("semantic retention certificate identity is not content-addressed")
	}
	return nil
}

// SemanticRetentionBindings are recomputed by the later invocation and are
// compared field-for-field before any retained bytes are consumed.
type SemanticRetentionBindings struct {
	AdoptionReportDigest string
	ObservationDigest    string
	ProposalDigest       string
	AuthorizationDigest  string
	CandidateStableID    string
	ContractSourceDigest string
	InputSourceDigest    string
	NormalizedIRDigest   string
	CompilerDigest       string
	ToolchainDigest      string
	VerifierDigest       string
	PolicyDigest         string
	EvaluatorDigest      string
}

func VerifySemanticRetentionCertificate(certificate SemanticRetentionCertificate, expected SemanticRetentionBindings) error {
	if err := ValidateSemanticRetentionCertificate(certificate); err != nil {
		return err
	}
	actual := []string{
		certificate.AdoptionReportDigest, certificate.ObservationDigest, certificate.ProposalDigest,
		certificate.AuthorizationDigest, certificate.CandidateStableID, certificate.ContractSourceDigest,
		certificate.InputSourceDigest, certificate.NormalizedIRDigest, certificate.CompilerDigest,
		certificate.ToolchainDigest, certificate.VerifierDigest, certificate.PolicyDigest,
		certificate.EvaluatorDigest,
	}
	want := []string{
		expected.AdoptionReportDigest, expected.ObservationDigest, expected.ProposalDigest,
		expected.AuthorizationDigest, expected.CandidateStableID, expected.ContractSourceDigest,
		expected.InputSourceDigest, expected.NormalizedIRDigest, expected.CompilerDigest,
		expected.ToolchainDigest, expected.VerifierDigest, expected.PolicyDigest,
		expected.EvaluatorDigest,
	}
	for index := range actual {
		if actual[index] != want[index] {
			return errors.New("semantic retention certificate does not bind the exact current evidence")
		}
	}
	return nil
}

// SemanticRetentionRuntimeMetrics records comparable integer measurements for
// two independent compiler invocations. Build/test fields remain zero unless
// the caller actually ran those operations under the same contract.
type SemanticRetentionRuntimeMetrics struct {
	SemanticOperationCount  int   `json:"semantic_operation_count"`
	CertificateHits         int   `json:"certificate_hits"`
	CertificateMisses       int   `json:"certificate_misses"`
	GeneratedBytesEqual     bool  `json:"generated_bytes_equal"`
	NormalizedSemanticEqual bool  `json:"normalized_semantic_equal"`
	WallMS                  int64 `json:"wall_ms"`
	PeakRSSKib              int64 `json:"peak_rss_kib"`
	AllocationCount         int64 `json:"allocation_count"`
	AllocationBytes         int64 `json:"allocation_bytes"`
	BuildMS                 int64 `json:"build_ms"`
	TestMS                  int64 `json:"test_ms"`
	ExecutedTests           int64 `json:"executed_tests"`
	ReusedTests             int64 `json:"reused_tests"`
}

// SemanticRetentionResult is a caller-owned artifact emitted by certify or a
// later consume invocation. UNKNOWN and REFUTED paths carry no generated
// bytes, so neither state can silently become an optimization hit.
type SemanticRetentionResult struct {
	Schema                string                          `json:"schema"`
	Lifecycle             string                          `json:"lifecycle"`
	Decision              string                          `json:"decision"`
	Reason                string                          `json:"reason"`
	Unknown               *EnvelopeUnknownState           `json:"unknown"`
	CertificateDigest     string                          `json:"certificate_digest"`
	AdoptionReportDigest  string                          `json:"adoption_report_digest"`
	ObservationDigest     string                          `json:"observation_digest"`
	ProposalDigest        string                          `json:"proposal_digest"`
	AuthorizationDigest   string                          `json:"authorization_digest"`
	CandidateStableID     string                          `json:"candidate_stable_id"`
	ContractSourceDigest  string                          `json:"contract_source_digest"`
	InputSourceDigest     string                          `json:"input_source_digest"`
	NormalizedIRDigest    string                          `json:"normalized_ir_digest"`
	GeneratedOutputDigest string                          `json:"generated_output_digest"`
	CompilerDigest        string                          `json:"compiler_digest"`
	ToolchainDigest       string                          `json:"toolchain_digest"`
	VerifierDigest        string                          `json:"verifier_digest"`
	PolicyDigest          string                          `json:"policy_digest"`
	EvaluatorDigest       string                          `json:"evaluator_digest"`
	GeneratedSource       []byte                          `json:"generated_source"`
	Metrics               SemanticRetentionRuntimeMetrics `json:"metrics"`
	RepositoryWrites      int                             `json:"repository_writes"`
	LocalTestExecutions   int                             `json:"local_test_executions"`
}

func SemanticRetentionUnknownState(reason string) *EnvelopeUnknownState {
	step := SemanticRetentionUnknownCertificateStep
	blockedBy := "retained_certificate"
	if reason == SemanticRetentionUnknownAuthorizationReason {
		step = SemanticRetentionUnknownAuthorizationStep
		blockedBy = "retention_authorization"
	}
	return &EnvelopeUnknownState{
		Stage: SemanticRetentionUnknownStage, Step: step, Reason: reason,
		UnknownClass: SemanticRetentionUnknownClass, NextOperation: SemanticRetentionUnknownNext,
		BlockedBy: []string{blockedBy},
	}
}

func SameSemanticRetentionUnknown(left, right *EnvelopeUnknownState) bool {
	if left == nil || right == nil {
		return left == right
	}
	return left.Stage == right.Stage && left.Step == right.Step && left.Reason == right.Reason &&
		left.UnknownClass == right.UnknownClass && left.NextOperation == right.NextOperation &&
		strings.Join(left.BlockedBy, "\x00") == strings.Join(right.BlockedBy, "\x00")
}

func ValidateSemanticRetentionResult(result SemanticRetentionResult) error {
	if result.Schema != SemanticRetentionResultSchema || result.Lifecycle == "" ||
		result.CandidateStableID == "" || !cache.Digest(result.AdoptionReportDigest).Known() ||
		!cache.Digest(result.ObservationDigest).Known() || !cache.Digest(result.ProposalDigest).Known() ||
		!cache.Digest(result.ContractSourceDigest).Known() || !cache.Digest(result.InputSourceDigest).Known() ||
		!cache.Digest(result.EvaluatorDigest).Known() ||
		result.RepositoryWrites != 0 || result.LocalTestExecutions != 0 {
		return errors.New("semantic retention result is invalid")
	}
	switch result.Decision {
	case "UNKNOWN":
		if (result.Reason != SemanticRetentionUnknownCertificateReason && result.Reason != SemanticRetentionUnknownAuthorizationReason) ||
			!SameSemanticRetentionUnknown(result.Unknown, SemanticRetentionUnknownState(result.Reason)) ||
			result.CertificateDigest != "" || len(result.GeneratedSource) != 0 || result.NormalizedIRDigest != "" || result.GeneratedOutputDigest != "" ||
			result.Metrics != (SemanticRetentionRuntimeMetrics{}) {
			return errors.New("semantic retention UNKNOWN result is not causal")
		}
	case SemanticRetentionRefuted:
		if result.Reason != SemanticRetentionRefutedReason || result.Unknown != nil || len(result.GeneratedSource) != 0 ||
			result.NormalizedIRDigest != "" || result.GeneratedOutputDigest != "" || result.Metrics.SemanticOperationCount != 0 ||
			result.Metrics.CertificateHits != 0 || result.Metrics.CertificateMisses != 1 {
			return errors.New("semantic retention REFUTED result is not causal")
		}
	case "CLOSED":
		if result.Unknown != nil || len(result.GeneratedSource) == 0 || !cache.Digest(result.CertificateDigest).Known() ||
			!cache.Digest(result.NormalizedIRDigest).Known() || !cache.Digest(result.GeneratedOutputDigest).Known() ||
			cache.HashBytes(result.GeneratedSource).String() != result.GeneratedOutputDigest ||
			result.Metrics.SemanticOperationCount < 0 || result.Metrics.CertificateHits < 0 || result.Metrics.CertificateMisses < 0 {
			return errors.New("semantic retention CLOSED result is invalid")
		}
	default:
		return errors.New("semantic retention result decision is invalid")
	}
	return nil
}

// SemanticRetentionManifestDigest binds a certificate to exact source files
// instead of an implicit repository version or mutable process cache.
func SemanticRetentionManifestDigest(readFile func(string) ([]byte, error), paths []string) (string, error) {
	if readFile == nil {
		return "", errors.New("retention manifest reader is nil")
	}
	var builder strings.Builder
	for _, path := range paths {
		data, err := readFile(path)
		if err != nil {
			return "", fmt.Errorf("read retention manifest file %s: %w", path, err)
		}
		builder.WriteString(path)
		builder.WriteByte('\t')
		builder.WriteString(cache.HashBytes(data).String())
		builder.WriteByte('\n')
	}
	return cache.HashBytes([]byte(builder.String())).String(), nil
}

func SemanticRetentionCompilerDigest(readFile func(string) ([]byte, error)) (string, error) {
	return SemanticRetentionManifestDigest(readFile, semanticRetentionCompilerManifestPaths[:])
}

func SemanticRetentionVerifierDigest(readFile func(string) ([]byte, error)) (string, error) {
	return SemanticRetentionManifestDigest(readFile, semanticRetentionVerifierManifestPaths[:])
}

func SemanticRetentionToolchainDigest() string {
	return cache.HashBytes([]byte(strings.Join([]string{runtime.Version(), runtime.GOOS, runtime.GOARCH}, "\x00"))).String()
}

// SemanticRetentionManifestPaths exposes copies for independent verifiers that
// want to audit the exact source binding without mutating the contract.
func SemanticRetentionCompilerManifestPaths() []string {
	return append([]string(nil), semanticRetentionCompilerManifestPaths[:]...)
}

func SemanticRetentionVerifierManifestPaths() []string {
	return append([]string(nil), semanticRetentionVerifierManifestPaths[:]...)
}
