package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/kimjooyoon/meta-ontology-go/internal/bodycodegen"
	"github.com/kimjooyoon/meta-ontology-go/internal/bodyexecution"
)

func TestSourceRecipeCLIContextGenerationAndNativeExecution(t *testing.T) {
	source := "../../examples/body-codegen/path-recipe.gooo.fixture"
	plan := "../../examples/body-codegen/path-recipe.json"
	observation := "../../examples/body-codegen/path-recipe-observation.json"
	var exported, diagnostics bytes.Buffer
	if code := run([]string{"body-context", "--plan", plan, "--activity", "Compose", source}, &exported, &diagnostics); code != exitOK {
		t.Fatal(code, diagnostics.String())
	}
	var contextExport bodycodegen.TypedPathContextExport
	if err := json.Unmarshal(exported.Bytes(), &contextExport); err != nil || len(contextExport.Inputs) != 3 || contextExport.ModelPredictions != 0 {
		t.Fatal("recipe context export", err)
	}
	var generated bytes.Buffer
	if code := run([]string{"body-codegen", "--json", "--activity", "Compose", "--path-plan", plan, "--path-observation", observation, source}, &generated, &diagnostics); code != exitOK {
		t.Fatal(code, diagnostics.String())
	}
	var generation bodycodegen.Result
	if err := json.Unmarshal(generated.Bytes(), &generation); err != nil || generation.Report.BodyPaths.Resolution.Status != "RESOLVED" {
		t.Fatal("recipe generation", err)
	}
	dir := t.TempDir()
	prior, cases := filepath.Join(dir, "generation.json"), filepath.Join(dir, "cases.json")
	if err := os.WriteFile(prior, generated.Bytes(), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(cases, []byte(`{"schema":"gooo/body-runtime-cases/v1","cases":[{"input":10,"expected":-3},{"input":0,"expected":7},{"input":-5,"expected":12}]}`), 0600); err != nil {
		t.Fatal(err)
	}
	goBin := filepath.Join(runtime.GOROOT(), "bin", "go")
	if runtime.GOOS == "windows" {
		goBin += ".exe"
	}
	var executed bytes.Buffer
	if code := run([]string{"body-execute", "--source", source, "--path-plan", plan, "--generation", prior, "--cases", cases, "--go-bin", goBin}, &executed, &diagnostics); code != exitOK {
		t.Fatal(code, diagnostics.String())
	}
	var result bodyexecution.Result
	if err := json.Unmarshal(executed.Bytes(), &result); err != nil || result.Observation.Stage != "COMPLETE" || len(result.Observation.Cases) != 3 {
		t.Fatal("recipe runtime result", err)
	}
	for _, c := range result.Observation.Cases {
		if !c.Passed {
			t.Fatal("compiled body disagreed with recipe", c)
		}
	}
}
