package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/kimjooyoon/meta-ontology-go/internal/conformance/adapter"
	"github.com/kimjooyoon/meta-ontology-go/internal/generator"
	"github.com/kimjooyoon/meta-ontology-go/internal/semantic"
)

const projectionManifestSchema = "gooo/cli/generate-manifest/v1"

// projectionManifest is a durable, append-only record for one CLI
// projection. The nested evidence manifest is the repository's canonical
// producer-independent evidence digest; the surrounding fields bind it to
// this source, generated bytes, source map, and optional PreviousGo input.
type projectionManifest struct {
	Schema              string                   `json:"schema"`
	Producer            string                   `json:"producer"`
	Operation           string                   `json:"operation"`
	Fixture             string                   `json:"fixture"`
	Status              string                   `json:"status"`
	PromotionEligible   bool                     `json:"promotion_eligible"`
	SemanticDigest      string                   `json:"semantic_digest"`
	SourceDigest        string                   `json:"source_digest"`
	GeneratedDigest     string                   `json:"generated_digest"`
	SourceMapDigest     string                   `json:"source_map_digest"`
	PreviousGoProvided  bool                     `json:"previous_go_provided"`
	PreviousGoDigest    string                   `json:"previous_go_digest,omitempty"`
	ProtectedBytesEqual bool                     `json:"protected_bytes_equal"`
	GeneratedFile       string                   `json:"generated_file"`
	ResponseDigest      string                   `json:"response_digest"`
	EvidenceManifest    adapter.EvidenceManifest `json:"evidence_manifest"`
}

func jsonManifestBytes(manifest projectionManifest) ([]byte, error) {
	var output bytes.Buffer
	if err := writeProjectionManifest(&output, manifest); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func writeProjectionManifest(writer io.Writer, manifest projectionManifest) error {
	payload, err := json.Marshal(manifest)
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(writer, "%s\n", payload)
	return err
}

func buildProjectionManifest(filename, generatedFile string, source []byte, previous []byte, ir semantic.IR, result generator.Result) (projectionManifest, error) {
	observed, err := observedProjection(result)
	if err != nil {
		return projectionManifest{}, err
	}
	previousSlots, err := ownedSlotBodies(previous)
	if err != nil {
		return projectionManifest{}, err
	}
	currentSlots, err := ownedSlotBodies(result.Source)
	if err != nil {
		return projectionManifest{}, err
	}
	protectedEqual := len(previous) == 0 || equalSlotBodies(previousSlots, currentSlots)
	response := adapter.Response{
		Schema:            adapter.ProtocolSchema,
		Fixture:           filename,
		Operation:         adapter.OperationGenerate,
		Status:            adapter.StatusPass,
		PromotionEligible: false,
		Observed:          observed,
		Measurements: adapter.Measurements{
			SourceSpanCount:        len(result.SourceMap.Mappings),
			ProtectedBytesEqual:    protectedEqual,
			RepeatCount:            1,
			CanonicalEqualCount:    1,
			SourceEqualCount:       1,
			SemanticEqualCount:     1,
			RegionEqualCount:       1,
			SourceMapResolvedCount: len(result.SourceMap.Mappings),
		},
		Evidence: adapter.EvidenceArtifact{
			Producer: "gooo",
			Bundle: adapter.EvidenceBundle{
				Schema:   adapter.EvidenceSchema,
				Stage:    adapter.StageGoooFallback,
				Fixture:  filename,
				Decision: string(adapter.StatusPass),
				Facts:    []adapter.EvidenceFact{},
			},
		},
	}
	evidence, err := response.ProjectEvidence("gooo", adapter.StageGoooFallback)
	if err != nil {
		return projectionManifest{}, err
	}
	response.Evidence = evidence
	responseDigest, err := response.Digest()
	if err != nil {
		return projectionManifest{}, err
	}
	evidenceManifest, err := evidence.Manifest()
	if err != nil {
		return projectionManifest{}, err
	}
	return projectionManifest{
		Schema:              projectionManifestSchema,
		Producer:            "gooo",
		Operation:           string(adapter.OperationGenerate),
		Fixture:             filename,
		Status:              string(adapter.StatusPass),
		PromotionEligible:   false,
		SemanticDigest:      ir.StableHash(),
		SourceDigest:        semantic.StableHash(source),
		GeneratedDigest:     semantic.StableHash(result.Source),
		SourceMapDigest:     sourceMapDigest(result.SourceMap),
		PreviousGoProvided:  len(previous) > 0,
		PreviousGoDigest:    previousDigest(previous),
		ProtectedBytesEqual: protectedEqual,
		GeneratedFile:       generatedFile,
		ResponseDigest:      responseDigest,
		EvidenceManifest:    evidenceManifest,
	}, nil
}

func observedProjection(result generator.Result) (adapter.Observed, error) {
	regions := make([]adapter.Region, 0)
	slots := make([]adapter.Slot, 0)
	mappings := make([]adapter.Mapping, 0, len(result.SourceMap.Mappings))
	for _, mapping := range result.SourceMap.Mappings {
		start, end := mapping.Generated.Start.Offset, mapping.Generated.End.Offset
		if start < 0 || end < start || end > len(result.Source) {
			return adapter.Observed{}, fmt.Errorf("source map %q has invalid generated range %d:%d", mapping.SemanticID, start, end)
		}
		mapped := adapter.Mapping{
			SemanticID: mapping.SemanticID,
			Kind:       mapping.Kind,
			Source:     adapter.Range{Start: mapping.Source.Start.Offset, End: mapping.Source.End.Offset},
			Generated:  adapter.Range{Start: start, End: end},
		}
		mappings = append(mappings, mapped)
		if mapping.Kind == "slot" {
			slots = append(slots, adapter.Slot{ID: mapping.SemanticID, Start: start, End: end})
			continue
		}
		regions = append(regions, adapter.Region{
			Kind:       mapping.Kind,
			SemanticID: mapping.SemanticID,
			Start:      start,
			End:        end,
			BodyDigest: semantic.StableHash(result.Source[start:end]),
		})
	}
	for index := range slots {
		for _, region := range regions {
			if region.Start <= slots[index].Start && slots[index].End <= region.End {
				slots[index].OwnerID = region.SemanticID
				break
			}
		}
		if slots[index].OwnerID == "" {
			return adapter.Observed{}, fmt.Errorf("slot %q is not inside a generated region", slots[index].ID)
		}
		if slots[index].End > len(result.Source) || slots[index].Start < 0 {
			return adapter.Observed{}, fmt.Errorf("slot %q has invalid range", slots[index].ID)
		}
		slots[index].BodyDigest = semantic.StableHash(result.Source[slots[index].Start:slots[index].End])
	}
	return adapter.Observed{SourceDigest: semantic.StableHash(result.Source), Regions: regions, Slots: slots, SourceMap: mappings}, nil
}

func sourceMapDigest(sourceMap generator.SourceMap) string {
	var canonical strings.Builder
	for _, mapping := range sourceMap.Mappings {
		fmt.Fprintf(&canonical, "%s\x00%s\x00%d\x00%d\x00%d\x00%d\n", mapping.SemanticID, mapping.Kind,
			mapping.Source.Start.Offset, mapping.Source.End.Offset, mapping.Generated.Start.Offset, mapping.Generated.End.Offset)
	}
	return semantic.StableHash([]byte(canonical.String()))
}

func previousDigest(previous []byte) string {
	if len(previous) == 0 {
		return ""
	}
	return semantic.StableHash(previous)
}

type ownedSlot struct {
	id        string
	bodyStart int
}

func ownedSlotBodies(source []byte) (map[string][]byte, error) {
	result := make(map[string][]byte)
	var open *ownedSlot
	for lineStart := 0; lineStart < len(source); {
		lineEnd := lineStart + 1
		for lineEnd < len(source) && source[lineEnd-1] != '\n' {
			lineEnd++
		}
		line := strings.TrimSpace(string(source[lineStart:lineEnd]))
		switch {
		case strings.HasPrefix(line, "//gooo:slot:start"):
			if open != nil {
				return nil, fmt.Errorf("nested slot %q", open.id)
			}
			id, err := markerID(line, "//gooo:slot:start")
			if err != nil {
				return nil, err
			}
			open = &ownedSlot{id: id, bodyStart: lineEnd}
		case strings.HasPrefix(line, "//gooo:slot:end"):
			if open == nil {
				return nil, fmt.Errorf("slot end without start")
			}
			id, err := markerID(line, "//gooo:slot:end")
			if err != nil {
				return nil, err
			}
			if id != open.id {
				return nil, fmt.Errorf("slot %q closes as %q", open.id, id)
			}
			if _, exists := result[id]; exists {
				return nil, fmt.Errorf("duplicate slot %q", id)
			}
			result[id] = append([]byte(nil), source[open.bodyStart:lineStart]...)
			open = nil
		}
		lineStart = lineEnd
	}
	if open != nil {
		return nil, fmt.Errorf("unterminated slot %q", open.id)
	}
	return result, nil
}

func markerID(line, prefix string) (string, error) {
	rest := strings.TrimSpace(strings.TrimPrefix(line, prefix))
	if !strings.HasPrefix(rest, "id=") {
		return "", fmt.Errorf("marker %q has no id", prefix)
	}
	value := strings.TrimSpace(strings.TrimPrefix(rest, "id="))
	if len(value) < 2 || value[0] != '"' {
		return "", fmt.Errorf("marker %q has invalid id", prefix)
	}
	end := 1
	for end < len(value) {
		if value[end] == '"' && value[end-1] != '\\' {
			break
		}
		end++
	}
	if end >= len(value) {
		return "", fmt.Errorf("marker %q has unterminated id", prefix)
	}
	id, err := strconv.Unquote(value[:end+1])
	if err != nil || id == "" {
		return "", fmt.Errorf("marker %q has invalid id", prefix)
	}
	return id, nil
}

func equalSlotBodies(previous, current map[string][]byte) bool {
	if len(previous) != len(current) {
		return false
	}
	for id, body := range previous {
		if string(body) != string(current[id]) {
			return false
		}
	}
	return true
}

func resolveManifestPath(root, raw string) (string, error) {
	if strings.TrimSpace(raw) == "" {
		return "", fmt.Errorf("manifest path is empty")
	}
	abs, err := filepath.Abs(raw)
	if err != nil {
		return "", fmt.Errorf("manifest absolute path: %w", err)
	}
	manifestRoot, err := canonicalOutputRoot(filepath.Dir(abs))
	if err != nil {
		return "", err
	}
	return resolveOutputPath(manifestRoot, filepath.Base(abs))
}
