package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/kimjooyoon/meta-ontology-go/internal/conformance/adapter"
	"io"
)

const projectionManifestSchema = "gooo/cli/generate-manifest/v1"

// projectionManifest is a durable, append-only record for one CLI
// projection. The nested evidence manifest is the repository's canonical
// producer-independent evidence digest; the surrounding fields bind it to
// this source, generated bytes, source map, and optional PreviousGo input.
type projectionManifest struct {
	Schema              string                   `json:"schema"`
	Producer            string                   `json:"producer"`
	Operation           string                   `json:"operation"`
	Fixture             string                   `json:"fixture"`
	Status              string                   `json:"status"`
	PromotionEligible   bool                     `json:"promotion_eligible"`
	SemanticDigest      string                   `json:"semantic_digest"`
	SourceDigest        string                   `json:"source_digest"`
	GeneratedDigest     string                   `json:"generated_digest"`
	SourceMapDigest     string                   `json:"source_map_digest"`
	PreviousGoProvided  bool                     `json:"previous_go_provided"`
	PreviousGoDigest    string                   `json:"previous_go_digest,omitempty"`
	ProtectedBytesEqual bool                     `json:"protected_bytes_equal"`
	GeneratedFile       string                   `json:"generated_file"`
	ResponseDigest      string                   `json:"response_digest"`
	EvidenceManifest    adapter.EvidenceManifest `json:"evidence_manifest"`
}

func jsonManifestBytes(manifest projectionManifest) ([]byte, error) {
	var output bytes.Buffer
	if err := writeProjectionManifest(&output, manifest); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}
func writeProjectionManifest(writer io.Writer, manifest projectionManifest) error {
	payload, err := json.Marshal(manifest)
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(writer, "%s\n", payload)
	return err
}
