package main

import (
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"time"

	"github.com/kimjooyoon/meta-ontology-go/internal/meta/publiccontinuity"
)

func writeContinuityGenerationAccepted(options generateOptions, certificate publiccontinuity.Certificate, certificateDigest string, started time.Time, jsonMode bool, stdout, stderr io.Writer, deadline time.Time) int {
	output, manifest, err := publicGeneratePaths(options)
	if err != nil {
		fmt.Fprintf(stderr, "gooo: public continuity generation: paths: %v\n", err)
		return exitFailure
	}
	report := publiccontinuity.Report{Schema: publiccontinuity.ReportSchema, Lifecycle: "CONSUMPTION", Decision: "CLOSED",
		Reason: "EXACT_CERTIFIED_PUBLIC_GENERATION_CONSUMPTION", CaseID: continuityCaseAccepted, Binding: certificate.Binding,
		CertificateDigest: certificateDigest, PublicInvocations: 2, LedgerEntries: 2, Candidates: 1, DecisionReceipts: 1,
		AcceptedDecisions: 1, Certificates: 1, DigestContinuityEdgesExpected: 4, DigestContinuityEdgesObserved: 4,
		ManualTransformations: certificate.ManualTransformations, SemanticOperationsBefore: 1, SemanticOperationsAfter: 0,
		CandidateCertificateByteReplayMismatches: 0, GeneratedBytesEqual: true, NormalizedSemanticEqual: true,
		ArtifactDenominator: 4, ArtifactCount: 4, RepositoryWrites: 0, LocalBuildExecutions: 0, LocalTestExecutions: 0,
		WallMS: continuityWallMS(started), PeakRSSKib: readPeakRSSKib()}
	reportData, err := marshalContinuityJSON(report)
	if err != nil {
		fmt.Fprintf(stderr, "gooo: public continuity generation: encode report: %v\n", err)
		return exitFailure
	}
	human := []byte(renderContinuityReport(report, "The ordinary generate command consumed the exact certified bytes without recompiling or mutating source."))
	if err := ensurePublicOutputDirectory(options.outputDir); err != nil {
		fmt.Fprintf(stderr, "gooo: public continuity generation: output: %v\n", err)
		return exitFailure
	}
	writes := []atomicWrite{{path: output, data: certificate.GeneratedSource}, {path: manifest, data: certificate.GeneratedManifest},
		{path: filepath.Join(options.outputDir, "continuity-generation-report.json"), data: reportData},
		{path: filepath.Join(options.outputDir, "continuity-generation-report.md"), data: human}}
	if err := writeAtomicFiles(writes); err != nil {
		fmt.Fprintf(stderr, "gooo: public continuity generation: output: %v\n", err)
		return exitFailure
	}
	if jsonMode {
		data, _ := json.Marshal(report)
		_, _ = stdout.Write(append(data, '\n'))
	} else {
		fmt.Fprintf(stdout, "generated: %s\ncontinuity: %s\n", output, filepath.Join(options.outputDir, "continuity-generation-report.md"))
	}
	_ = deadline
	return exitOK
}

func renderContinuityReport(report publiccontinuity.Report, note string) string {
	return fmt.Sprintf("# Gooo public self-observation continuity\n\nDecision: `%s`\nReason: `%s`\nCase: `%s`\nCandidate digest: `%s`\nDecision receipt digest: `%s`\nCertificate digest: `%s`\nDigest continuity edges: `%d/%d`\nManual transformations: `%d`\nSemantic operations before/after: `%d/%d`\nGenerated bytes equal: `%t`\nNormalized semantic equal: `%t`\nArtifacts: `%d/%d`\nRepository writes: `%d`\nLocal build executions: `%d`\nLocal test executions: `%d`\nWall time (ms): `%d`\nPeak RSS (KiB): `%d`\n\n%s\n", report.Decision, report.Reason, report.CaseID, report.Binding.CandidateDigest, report.DecisionReceiptDigest, report.CertificateDigest, report.DigestContinuityEdgesObserved, report.DigestContinuityEdgesExpected, report.ManualTransformations, report.SemanticOperationsBefore, report.SemanticOperationsAfter, report.GeneratedBytesEqual, report.NormalizedSemanticEqual, report.ArtifactCount, report.ArtifactDenominator, report.RepositoryWrites, report.LocalBuildExecutions, report.LocalTestExecutions, report.WallMS, report.PeakRSSKib, note)
}
