package bodypathstream

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/kimjooyoon/meta-ontology-go/internal/bodycodegen"
)

func fileArgs(t *testing.T, recipe bool, suite string) ([]string, string) {
	t.Helper()
	root := t.TempDir()
	fixture, activity := "typed-path-compound", "Combined"
	plan := "typed-path-compound-plan.json"
	if recipe {
		fixture, activity, plan = "path-recipe", "BuildTotal", "path-recipe.json"
	}
	source, err := os.ReadFile("../../examples/body-codegen/" + fixture + ".gooo.fixture")
	if err != nil {
		t.Fatal(err)
	}
	if recipe {
		source = bytes.ReplaceAll(source, []byte("Compose"), []byte(activity))
		raw, err := os.ReadFile("../../examples/body-codegen/" + plan)
		if err != nil {
			t.Fatal(err)
		}
		// The original one-case fixture permits multiple bodies. Add a declared
		// selection example; keep the separate runtime inputs unchanged.
		raw = bytes.Replace(raw, []byte(`{"input": 10, "expected": -3}`),
			[]byte(`{"input": 10, "expected": -3}, {"input": 0, "expected": 7}`), 1)
		plan = filepath.Join(root, "recipe.json")
		if err := os.WriteFile(plan, raw, 0644); err != nil {
			t.Fatal(err)
		}
	} else {
		plan = "../../examples/body-codegen/" + plan
	}
	if err := os.WriteFile(filepath.Join(root, "source.gooo"), source, 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "cases.json"), []byte(suite), 0644); err != nil {
		t.Fatal(err)
	}
	tool := filepath.Join(runtime.GOROOT(), "bin", "go")
	if runtime.GOOS == "windows" {
		tool += ".exe"
	}
	out := filepath.Join(root, "output")
	return []string{"--source", filepath.Join(root, "source.gooo"), "--activity", activity,
		"--path-plan", plan, "--cases", filepath.Join(root, "cases.json"),
		"--out", out, "--repeat", "2", "--go-bin", tool}, out
}

func fileSummary(t *testing.T, out string) []fileRunRow {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(out, "summary.json"))
	if err != nil {
		t.Fatal(err)
	}
	var summary struct {
		Schema string       `json:"schema"`
		Rows   []fileRunRow `json:"rows"`
	}
	if err := json.Unmarshal(b, &summary); err != nil || summary.Schema != "gooo/body-path-file-run/v1" {
		t.Fatal("invalid summary", err)
	}
	return summary.Rows
}

func TestFilesNamedActivitiesAndActualNativeReuse(t *testing.T) {
	for _, recipe := range []bool{false, true} {
		suite := `{"schema":"gooo/body-runtime-cases/v1","cases":[{"input":2,"expected":15},{"input":-4,"expected":-21}]}`
		if recipe {
			suite = `{"schema":"gooo/body-runtime-cases/v1","cases":[{"input":2,"expected":5},{"input":-4,"expected":11}]}`
		}
		args, out := fileArgs(t, recipe, suite)
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		var stdout, stderr bytes.Buffer
		code := RunFilesCommand(ctx, "files", args, &stdout, &stderr)
		cancel()
		if code != 0 {
			t.Fatal(code, stderr.String())
		}
		results, rows := decodeResults(t, stdout.Bytes()), fileSummary(t, out)
		if len(results) != 2 || len(rows) != 2 {
			t.Fatal("lost repetitions")
		}
		for i, r := range results {
			if r.Status != "completed" || r.Response == nil || r.Execution == nil || rows[i].Passed != 2 ||
				rows[i].Total != 2 || rows[i].NativeRuns != 2 || rows[i].ArtifactReused != (i == 1) || rows[i].ResponseMS <= 0 {
				t.Fatalf("row=%+v result=%s", rows[i], r.Error)
			}
			for _, filename := range []string{rows[i].ResponseFile, rows[i].GenerationFile, rows[i].RuntimeFile} {
				b, err := os.ReadFile(filepath.Join(out, filename))
				if err != nil || !json.Valid(b) {
					t.Fatal("lost original artifact", filename, err)
				}
			}
			generated, err := os.ReadFile(filepath.Join(out, strings.Replace(rows[i].GenerationFile, "-generation.json", "-generated.go", 1)))
			if err != nil || string(generated) != r.Response.Source {
				t.Fatal("changed generated bytes", err)
			}
		}
		metadata, err := os.ReadFile(filepath.Join(out, "model-retention.json"))
		if err != nil || !bytes.Contains(metadata, []byte(`"loaded":false`)) {
			t.Fatal("deterministic route loaded a model", err)
		}
		if code := RunFilesCommand(context.Background(), "files", args, io.Discard, &stderr); code != 1 {
			t.Fatal("existing output directory overwritten")
		}
	}
}

func TestFilesPreserveFiniteFailureAndNativeFailure(t *testing.T) {
	args, out := fileArgs(t, false, `{"schema":"gooo/body-runtime-cases/v1","cases":[{"input":2,"expected":999}]}`)
	var stdout, stderr bytes.Buffer
	if code := RunFilesCommand(context.Background(), "files", args, &stdout, &stderr); code != 0 {
		t.Fatal(code, stderr.String())
	}
	for _, row := range fileSummary(t, out) {
		if row.Status != "completed" || row.Passed != 0 || row.Total != 1 {
			t.Fatal("finite failure lost", row)
		}
	}
	args, out = fileArgs(t, false, `{"schema":"gooo/body-runtime-cases/v1","cases":[{"input":2,"expected":15}]}`)
	args[len(args)-1] = filepath.Join(t.TempDir(), "missing-go")
	stdout.Reset()
	if code := RunFilesCommand(context.Background(), "files", args, &stdout, &stderr); code != 1 {
		t.Fatal("native failure exit", code)
	}
	for _, row := range fileSummary(t, out) {
		if row.Status != "execution_failed" || row.GenerationFile == "" || row.RuntimeFile == "" || row.NativeRuns != 0 {
			t.Fatal("failure not retained", row)
		}
	}
}

func TestFilesRejectMissingExpectationBeforeGeneration(t *testing.T) {
	args, out := fileArgs(t, false, `{"schema":"gooo/body-runtime-cases/v1","cases":[{"input":2}]}`)
	var stdout, stderr bytes.Buffer
	if code := RunFilesCommand(context.Background(), "files", args, &stdout, &stderr); code != 1 {
		t.Fatal("missing expectation accepted", code)
	}
	for _, row := range fileSummary(t, out) {
		if row.Status != "rejected" || row.GenerationFile != "" || row.RuntimeFile != "" {
			t.Fatal("invalid cases reached generation", row)
		}
	}
}

func TestFilesArgumentAndInputBounds(t *testing.T) {
	for _, tc := range []struct {
		args []string
		code int
	}{{[]string{"--help"}, 0}, {nil, 2}, {[]string{"--unknown"}, 2}} {
		var stdout, stderr bytes.Buffer
		if code := RunFilesCommand(context.Background(), "files", tc.args, &stdout, &stderr); code != tc.code || stdout.Len() != 0 {
			t.Fatal(code, stderr.String())
		}
	}
	for _, value := range []string{"0", "17"} {
		args, _ := fileArgs(t, false, "{}")
		args[11] = value
		if code := RunFilesCommand(context.Background(), "files", args, io.Discard, io.Discard); code != 2 {
			t.Fatal("unbounded repetition", code)
		}
	}
	for _, data := range [][]byte{nil, {0xff}, bytes.Repeat([]byte{'x'}, (128<<10)+1)} {
		args, out := fileArgs(t, false, "{}")
		if err := os.WriteFile(args[1], data, 0644); err != nil {
			t.Fatal(err)
		}
		if code := RunFilesCommand(context.Background(), "files", args, io.Discard, io.Discard); code != 1 {
			t.Fatal("invalid source accepted", code)
		}
		if _, err := os.Stat(out); !os.IsNotExist(err) {
			t.Fatal("invalid input created output")
		}
	}
	args, out := fileArgs(t, false, "{}")
	args[1] = t.TempDir()
	if code := RunFilesCommand(context.Background(), "files", args, io.Discard, io.Discard); code != 1 {
		t.Fatal("directory read as source", code)
	}
	if _, err := os.Stat(out); !os.IsNotExist(err) {
		t.Fatal("nonregular input created output")
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if code := RunFilesCommand(ctx, "files", args, io.Discard, io.Discard); code != 1 {
		t.Fatal("cancelled call proceeded", code)
	}
}

func TestFileOptionsExactContract(t *testing.T) {
	for _, raw := range []string{`null`, `[]`, `{"Step_attempts":1}`, `{"extra":1}`,
		`{"step_attempts":1,"step_attempts":2}`, `{}` + `{}`, strings.Repeat("[", 65) + "0" + strings.Repeat("]", 65)} {
		var options bodycodegen.TypedPathOptions
		if err := decodeFileOptions([]byte(raw), &options); err == nil {
			t.Fatal("ambiguous options accepted", raw)
		}
	}
	var options bodycodegen.TypedPathOptions
	raw := `{"step_attempts":2,"ci":{"source_sha":"` + strings.Repeat("a", 40) + `","status":"FAIL"}}`
	if err := decodeFileOptions([]byte(raw), &options); err != nil || options.StepAttempts != 2 || options.CI == nil || options.CI.Status != "FAIL" {
		t.Fatal("CI context not preserved", err)
	}
}

func TestFileEvaluatorRetainsStreamRecordBound(t *testing.T) {
	raw := bytes.Repeat([]byte{' '}, MaxRecordBytes+1)
	g := fakeGenerator{generate: func(context.Context, string) (bodycodegen.Result, error) {
		t.Fatal("oversized record reached construction")
		return bodycodegen.Result{}, nil
	}}
	r := evaluateWithExecution(context.Background(), g, record{sequence: 1, raw: raw}, &executionSettings{})
	if r.Status != "rejected" || !strings.Contains(r.Error, "request exceeds") || r.Response != nil {
		t.Fatal("direct file evaluation bypassed stream bound")
	}
}

func TestFileCancellationUnblocksOutputAndPreservesLastReport(t *testing.T) {
	line := executionLine(t, "current", `{"schema":"gooo/body-runtime-cases/v1","cases":[{"input":2,"expected":15}]}`)
	var request Request
	if err := json.Unmarshal(line, &request); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	reader, writer := io.Pipe()
	defer reader.Close()
	defer writer.Close()
	out := t.TempDir()
	done := make(chan int, 1)
	g := fakeGenerator{generate: func(context.Context, string) (bodycodegen.Result, error) {
		return bodycodegen.Result{}, errors.New("recorded construction failure")
	}}
	go func() {
		done <- runFileRequests(ctx, g, request, 2, "", out, writer, io.Discard, func(error) int { return 1 })
	}()
	deadline := time.After(5 * time.Second)
	for {
		if _, err := os.Stat(filepath.Join(out, "summary.json")); err == nil {
			break
		}
		select {
		case <-deadline:
			t.Fatal("first report not saved before blocked output")
		case <-time.After(5 * time.Millisecond):
		}
	}
	cancel()
	select {
	case code := <-done:
		if code != 1 || len(fileSummary(t, out)) != 1 {
			t.Fatal("cancellation lost observation", code)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("blocked output deadlock")
	}
}

type failedFileWriter struct{}

func (failedFileWriter) Write([]byte) (int, error) { return 0, errors.New("output unavailable") }

func TestFileOutputFailurePreservesGenerationFailure(t *testing.T) {
	line := executionLine(t, "current", `{"schema":"gooo/body-runtime-cases/v1","cases":[{"input":2,"expected":15}]}`)
	var request Request
	if err := json.Unmarshal(line, &request); err != nil {
		t.Fatal(err)
	}
	g := fakeGenerator{generate: func(context.Context, string) (bodycodegen.Result, error) {
		return bodycodegen.Result{}, errors.New("original construction failure")
	}}
	out := t.TempDir()
	if code := runFileRequests(context.Background(), g, request, 2, "", out, failedFileWriter{}, io.Discard,
		func(error) int { return 1 }); code != 1 {
		t.Fatal("output failure ignored", code)
	}
	rows := fileSummary(t, out)
	if len(rows) != 1 || rows[0].Status != "rejected" {
		t.Fatal("observation lost or next request started after output failure")
	}
	raw, err := os.ReadFile(filepath.Join(out, rows[0].ResponseFile))
	if err != nil || !bytes.Contains(raw, []byte("original construction failure")) {
		t.Fatal("original failure lost", err)
	}
}
