package receiptprojection

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"strings"
)

func (p Projection) Go() ([]byte, error) {
	if err := p.validateBinding(); err != nil {
		return nil, err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gooo receipt-schema; DO NOT EDIT.\n// Projection profile: %s\npackage %s\n\n", Profile, p.Package)
	fmt.Fprintf(&b, "const %sSchema = %q\nconst DeclarationSHA256 = %q\nconst ProjectionProfile = %q\n", p.Root, p.Schema, p.SourceSHA256, Profile)
	for _, e := range p.Entities {
		fmt.Fprintf(&b, "\n//gooo:generated:start id=%q kind=\"entity\"\ntype %s struct {\n", e.ID, e.Name)
		for _, f := range e.Fields {
			fmt.Fprintf(&b, "%s %s `json:%q gooo:%q`\n", f.GoName, f.GoType, f.Name, f.ID)
		}
		fmt.Fprintf(&b, "}\n//gooo:generated:end id=%q kind=\"entity\"\n", e.ID)
	}
	return format.Source([]byte(b.String()))
}

func (p Projection) JSONSchema() ([]byte, error) {
	if err := p.validateBinding(); err != nil {
		return nil, err
	}
	defs := map[string]any{}
	names := map[string]string{}
	for _, e := range p.Entities {
		names[e.ID] = e.Name
	}
	for _, e := range p.Entities {
		properties := map[string]any{}
		required := make([]string, 0, len(e.Fields))
		for _, f := range e.Fields {
			value := fieldSchema(f, names)
			value["x-gooo-id"] = f.ID
			value["x-gooo-source-span"] = map[string]int{"start": f.Span.Start.Offset, "end": f.Span.End.Offset}
			if e.Name == p.Root && f.Name == "schema" {
				value["const"] = p.Schema
			}
			properties[f.Name] = value
			required = append(required, f.Name)
		}
		defs[e.Name] = map[string]any{"type": "object", "properties": properties, "required": required, "additionalProperties": false, "x-gooo-id": e.ID}
	}
	doc := map[string]any{"$schema": "https://json-schema.org/draft/2020-12/schema", "$id": p.Schema, "$ref": "#/$defs/" + p.Root, "$defs": defs, "x-gooo-declaration-sha256": p.SourceSHA256, "x-gooo-projection-profile": Profile}
	b, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

func (p Projection) validateBinding() error {
	if len(p.source) == 0 {
		return fmt.Errorf("receipt projection has no original Gooo source")
	}
	expected, err := Compile(p.filename, p.source, p.originalRoot)
	if err != nil {
		return err
	}
	actualBytes, err := json.Marshal(p)
	if err != nil {
		return err
	}
	expectedBytes, err := json.Marshal(expected)
	if err != nil {
		return err
	}
	if !bytes.Equal(actualBytes, expectedBytes) {
		return fmt.Errorf("receipt projection changed source-owned structure or identity")
	}
	return nil
}

func fieldSchema(f Field, names map[string]string) map[string]any {
	var s map[string]any
	switch f.TypeID {
	case typePrefix + "text":
		s = map[string]any{"type": "string"}
	case typePrefix + "state":
		s = map[string]any{"type": "string", "enum": []string{"PASS", "PROGRESS", "UNKNOWN", "FAIL_CLOSED"}}
	case typePrefix + "count":
		s = map[string]any{"type": "integer", "minimum": 0}
	case typePrefix + "number":
		s = map[string]any{"type": "number"}
	case typePrefix + "record":
		s = map[string]any{"type": "object"}
	case typePrefix + "counts":
		s = map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "integer", "minimum": 0}}
	default:
		s = map[string]any{"$ref": "#/$defs/" + names[f.TypeID]}
	}
	if f.Many {
		return map[string]any{"type": "array", "items": s}
	}
	if f.Optional {
		return map[string]any{"anyOf": []any{s, map[string]any{"type": "null"}}}
	}
	return s
}
