// Code generated by gooo receipt-schema; DO NOT EDIT.
// Projection profile: gooo/receipt-structure-projection/v1
package outcomedelta

const OutcomeDeltaSchema = "gooo/body-outcomes-delta/v1"
const DeclarationSHA256 = "d933dbe2fb64c71fa87bea5304551c01b7702dcde312e5982c513e005d69a678"
const ProjectionProfile = "gooo/receipt-structure-projection/v1"

//gooo:generated:start id="gooo://outcome-delta/entity/change" kind="entity"
type OutcomeChange struct {
	ActivityID        string           `json:"activity_id" gooo:"gooo://outcome-delta/change/activity"`
	RootInputs        []map[string]any `json:"root_inputs" gooo:"gooo://outcome-delta/change/inputs"`
	Presence          string           `json:"presence" gooo:"gooo://outcome-delta/change/presence"`
	OutcomeChange     string           `json:"outcome_change" gooo:"gooo://outcome-delta/change/outcome"`
	RequirementChange string           `json:"requirement_change" gooo:"gooo://outcome-delta/change/requirement"`
	Assessment        string           `json:"assessment" gooo:"gooo://outcome-delta/change/assessment"`
	Before            []map[string]any `json:"before" gooo:"gooo://outcome-delta/change/before"`
	After             []map[string]any `json:"after" gooo:"gooo://outcome-delta/change/after"`
}

//gooo:generated:end id="gooo://outcome-delta/entity/change" kind="entity"

//gooo:generated:start id="gooo://schema/body-outcomes-delta/v1" kind="entity"
type OutcomeDelta struct {
	Schema               string          `json:"schema" gooo:"gooo://outcome-delta/report/schema"`
	DeclarationSha256    string          `json:"declaration_sha256" gooo:"gooo://outcome-delta/report/declaration"`
	BeforeInputSha256    string          `json:"before_input_sha256" gooo:"gooo://outcome-delta/report/before"`
	AfterInputSha256     string          `json:"after_input_sha256" gooo:"gooo://outcome-delta/report/after"`
	BeforeRuntime        map[string]any  `json:"before_runtime" gooo:"gooo://outcome-delta/report/before-runtime"`
	AfterRuntime         map[string]any  `json:"after_runtime" gooo:"gooo://outcome-delta/report/after-runtime"`
	Rows                 []OutcomeChange `json:"rows" gooo:"gooo://outcome-delta/report/rows"`
	Counts               map[string]int  `json:"counts" gooo:"gooo://outcome-delta/report/counts"`
	ComparatorOperations map[string]int  `json:"comparator_operations" gooo:"gooo://outcome-delta/report/operations"`
	Scope                string          `json:"scope" gooo:"gooo://outcome-delta/report/scope"`
}

//gooo:generated:end id="gooo://schema/body-outcomes-delta/v1" kind="entity"
