package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/kimjooyoon/meta-ontology-go/internal/meta/publicpartialreuse"
)

func verify(reportPath, humanPath string) error {
	if reportPath == "" || humanPath == "" {
		return errors.New("report and human-output are required")
	}
	data, err := readRegular(reportPath)
	if err != nil {
		return err
	}
	var value report
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&value); err != nil {
		return err
	}
	if value.Schema != "gooo/public-partial-test-reuse-verification/v1" || value.Decision != publicpartialreuse.DecisionClosed || value.Operation != publicpartialreuse.Operation ||
		value.CaseDenominator != 6 || value.ClosedCases != 2 || value.UnknownCases != 2 || value.RefutedCases != 2 || value.TestUnitsTotal != 2 ||
		value.GeneratedArtifacts != 2 || value.EvidenceArtifacts != 25 || value.RuntimeComparable || value.RuntimeUnknown == "" || value.RepositoryWrites != 0 || value.LocalTestExecutions != 0 || len(value.PublishedArtifacts) != 25 {
		return errors.New("partial reuse report denominator or safety contract is invalid")
	}
	if err := value.Policy.Validate(); err != nil {
		return err
	}
	if len(value.Cases) != len(value.Policy.Cases) {
		return errors.New("partial reuse report case table is incomplete")
	}
	for index, item := range value.Cases {
		if item.CaseID != value.Policy.Cases[index].ID || item.ExpectedDecision != value.Policy.Cases[index].Decision {
			return fmt.Errorf("partial reuse case %d is not bound to the canonical policy table", index+1)
		}
		if err := publicpartialreuse.CompareCase(item, item.ExpectedDecision); err != nil {
			return err
		}
	}
	if value.NoChangeBefore.TestUnitsExecuted != 2 || value.NoChangeAfter.TestUnitsExecuted != 0 || value.NoChangeAfter.TestUnitsReused != 2 ||
		value.SingleChangeBefore.TestUnitsExecuted != 2 || value.SingleChangeAfter.TestUnitsExecuted != 1 || value.SingleChangeAfter.TestUnitsReused != 1 ||
		value.Cases[1].ImpactedPartitions != 1 || value.Cases[1].UnaffectedPartitions != 1 || value.Cases[1].ClosureEdges != 0 ||
		!value.GeneratedBytesEqual || !value.SemanticEqual || !value.TestContractEqual || !value.ReceiptBindingEqual {
		return errors.New("partial reuse report does not prove selective execution under equal inputs")
	}
	if err := writeNew(humanPath, []byte(humanReport(value)), 0o444); err != nil {
		return err
	}
	return nil
}

func humanReport(value report) string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "# Public partial test reuse\n\nDecision: `%s`\nReason: `%s`\n\n", value.Decision, value.Reason)
	fmt.Fprintf(&builder, "Cases: `%d CLOSED / %d UNKNOWN / %d REFUTED`\n", value.ClosedCases, value.UnknownCases, value.RefutedCases)
	fmt.Fprintf(&builder, "Test units executed before/after: `%d/%d`\n", value.SingleChangeBefore.TestUnitsExecuted, value.SingleChangeAfter.TestUnitsExecuted)
	fmt.Fprintf(&builder, "Test units reused before/after: `%d/%d`\n", value.SingleChangeBefore.TestUnitsReused, value.SingleChangeAfter.TestUnitsReused)
	fmt.Fprintf(&builder, "Impacted/unaffected partitions: `%d/%d`; closure edges: `%d`\n", value.Cases[1].ImpactedPartitions, value.Cases[1].UnaffectedPartitions, value.Cases[1].ClosureEdges)
	fmt.Fprintf(&builder, "Generated bytes / semantic / test contract / receipt binding equal: `%t/%t/%t/%t`\n", value.GeneratedBytesEqual, value.SemanticEqual, value.TestContractEqual, value.ReceiptBindingEqual)
	fmt.Fprintf(&builder, "Repository writes / local test executions: `%d/%d`\n", value.RepositoryWrites, value.LocalTestExecutions)
	fmt.Fprintf(&builder, "Runtime comparison: `UNKNOWN` (%s)\n", value.RuntimeUnknown)
	return builder.String()
}
