package main

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestRunGenerateRejectsInvalidInputWithoutMutation(t *testing.T) {
	tests := []struct {
		name   string
		source string
		want   string
	}{
		{name: "syntax", source: "package billing\nentity Broken id \"x\" @", want: "error"},
		{name: "semantic", source: `package billing
namespace billing
entity Order id "billing://entity/order"
activity PayOrder(PayOrder) -> Order
`, want: "generation failed"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			outputDir := t.TempDir()
			outputPath := filepath.Join(outputDir, generatedFileName)
			original := []byte("existing generated bytes\n")
			if err := os.WriteFile(outputPath, original, 0o640); err != nil {
				t.Fatal(err)
			}
			before, err := os.Stat(outputPath)
			if err != nil {
				t.Fatal(err)
			}
			beforeEntries := directoryEntries(t, outputDir)
			var stdout, stderr bytes.Buffer
			code := runGenerate([]string{"fixture.gooo", "--out", outputDir}, fixtureReader{source: test.source}, SyntaxSourceParser{}, &stdout, &stderr)
			if code != exitFailure || stdout.Len() != 0 || !strings.Contains(stderr.String(), test.want) {
				t.Fatalf("%s generate = code %d, stdout=%q, stderr=%q", test.name, code, stdout.String(), stderr.String())
			}
			after, err := os.Stat(outputPath)
			if err != nil {
				t.Fatal(err)
			}
			got, err := os.ReadFile(outputPath)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, original) || !os.SameFile(before, after) || before.Mode() != after.Mode() || !before.ModTime().Equal(after.ModTime()) || !reflect.DeepEqual(beforeEntries, directoryEntries(t, outputDir)) {
				t.Fatalf("%s rejection mutated output state", test.name)
			}
		})
	}
}
