// Code generated by gooo receipt-schema; DO NOT EDIT.
// Projection profile: gooo/receipt-structure-projection/v1
package completenessdelta

const CompletenessDeltaSchema = "gooo/completeness-delta/v1"
const DeclarationSHA256 = "d8f093b9d138fe7ae29c9931398c7452bc92675f81050d477bd7c821fb6fcc47"
const ProjectionProfile = "gooo/receipt-structure-projection/v1"

//gooo:generated:start id="gooo://completeness-delta/entity/observation" kind="entity"
type DimensionObservation struct {
	Status      string   `json:"status" gooo:"gooo://completeness-delta/field/observation/status"`
	Numerator   int      `json:"numerator" gooo:"gooo://completeness-delta/field/observation/numerator"`
	Denominator int      `json:"denominator" gooo:"gooo://completeness-delta/field/observation/denominator"`
	Unit        string   `json:"unit" gooo:"gooo://completeness-delta/field/observation/unit"`
	Reason      string   `json:"reason" gooo:"gooo://completeness-delta/field/observation/reason"`
	Evidence    []string `json:"evidence" gooo:"gooo://completeness-delta/field/observation/evidence"`
}

//gooo:generated:end id="gooo://completeness-delta/entity/observation" kind="entity"

//gooo:generated:start id="gooo://completeness-delta/entity/change" kind="entity"
type DimensionChange struct {
	ID                string                `json:"id" gooo:"gooo://completeness-delta/field/change/id"`
	Presence          string                `json:"presence" gooo:"gooo://completeness-delta/field/change/presence"`
	Before            *DimensionObservation `json:"before" gooo:"gooo://completeness-delta/field/change/before"`
	After             *DimensionObservation `json:"after" gooo:"gooo://completeness-delta/field/change/after"`
	StateTransition   string                `json:"state_transition" gooo:"gooo://completeness-delta/field/change/state-transition"`
	ObservationChange string                `json:"observation_change" gooo:"gooo://completeness-delta/field/change/observation-change"`
	CountDirection    string                `json:"count_direction" gooo:"gooo://completeness-delta/field/change/count-direction"`
	CountMagnitude    *int                  `json:"count_magnitude" gooo:"gooo://completeness-delta/field/change/count-magnitude"`
	Regression        string                `json:"regression" gooo:"gooo://completeness-delta/field/change/regression"`
	Reason            string                `json:"reason" gooo:"gooo://completeness-delta/field/change/reason"`
}

//gooo:generated:end id="gooo://completeness-delta/entity/change" kind="entity"

//gooo:generated:start id="gooo://schema/completeness-delta/v1" kind="entity"
type CompletenessDelta struct {
	Schema               string            `json:"schema" gooo:"gooo://completeness-delta/field/receipt/schema"`
	Status               string            `json:"status" gooo:"gooo://completeness-delta/field/receipt/status"`
	Relation             string            `json:"relation" gooo:"gooo://completeness-delta/field/receipt/relation"`
	Basis                string            `json:"basis" gooo:"gooo://completeness-delta/field/receipt/basis"`
	Declaration          map[string]any    `json:"declaration" gooo:"gooo://completeness-delta/field/receipt/declaration"`
	BeforeInputSha256    string            `json:"before_input_sha256" gooo:"gooo://completeness-delta/field/receipt/before-input-sha256"`
	AfterInputSha256     string            `json:"after_input_sha256" gooo:"gooo://completeness-delta/field/receipt/after-input-sha256"`
	BeforeReceiptSha256  string            `json:"before_receipt_sha256" gooo:"gooo://completeness-delta/field/receipt/before-receipt-sha256"`
	AfterReceiptSha256   string            `json:"after_receipt_sha256" gooo:"gooo://completeness-delta/field/receipt/after-receipt-sha256"`
	BeforeReceipt        map[string]any    `json:"before_receipt" gooo:"gooo://completeness-delta/field/receipt/before-receipt"`
	AfterReceipt         map[string]any    `json:"after_receipt" gooo:"gooo://completeness-delta/field/receipt/after-receipt"`
	ChangedScopeFields   []string          `json:"changed_scope_fields" gooo:"gooo://completeness-delta/field/receipt/changed-scope-fields"`
	Dimensions           []DimensionChange `json:"dimensions" gooo:"gooo://completeness-delta/field/receipt/dimensions"`
	TransitionCounts     map[string]int    `json:"transition_counts" gooo:"gooo://completeness-delta/field/receipt/transition-counts"`
	ComparatorOperations map[string]int    `json:"comparator_operations" gooo:"gooo://completeness-delta/field/receipt/comparator-operations"`
	NotClaimed           []string          `json:"not_claimed" gooo:"gooo://completeness-delta/field/receipt/not-claimed"`
}

//gooo:generated:end id="gooo://schema/completeness-delta/v1" kind="entity"
