package bodycodegen

import (
	"encoding/json"
	"runtime"
	"runtime/debug"
	"slices"
	"sort"
	"strconv"
	"strings"
)

const completenessReceiptSchema = "gooo/metaprogramming-completeness-receipt/v2"

type CompletenessDimension struct {
	ID          string   `json:"id"`
	Status      string   `json:"status"`
	Numerator   int      `json:"numerator"`
	Denominator int      `json:"denominator"`
	Unit        string   `json:"unit"`
	Reason      string   `json:"reason"`
	Evidence    []string `json:"evidence"`
}

type UnresolvedCompletenessClaim struct {
	ID            string `json:"id"`
	Status        string `json:"status"`
	Reason        string `json:"reason"`
	NextOperation string `json:"next_operation"`
}

type CompletenessReceipt struct {
	Schema                     string                        `json:"schema"`
	ProfileID                  string                        `json:"profile_id"`
	Decision                   string                        `json:"decision"`
	DecisionBasis              string                        `json:"decision_basis"`
	Scope                      map[string]any                `json:"scope"`
	CoreDimensions             []string                      `json:"core_dimensions"`
	Dimensions                 []CompletenessDimension       `json:"dimensions"`
	StatusCounts               map[string]int                `json:"status_counts"`
	AggregateCompletenessScore *float64                      `json:"aggregate_completeness_score"`
	FirstUnresolved            *UnresolvedCompletenessClaim  `json:"first_unresolved"`
	UnresolvedClaims           []UnresolvedCompletenessClaim `json:"unresolved_claims"`
	NotClaimed                 []string                      `json:"not_claimed"`
	FailClosedReason           *string                       `json:"fail_closed_reason"`
}

type completenessPlanIdentity struct {
	ProfileID     string `json:"profile_id"`
	Activity      string `json:"activity"`
	ActivityID    string `json:"activity_id"`
	InputType     string `json:"input_type"`
	OutputType    string `json:"output_type"`
	SourceDigest  string `json:"source_digest"`
	ProgramDigest string `json:"program_digest"`
}

func buildCompletenessReceipt(report Report, failure string) *CompletenessReceipt {
	compilerSHA := report.CompilerSourceSHA
	if compilerSHA == "" {
		compilerSHA = "UNBOUND_LOCAL_SOURCE"
	}
	planSHA := report.PlanSHA256
	if planSHA == "" {
		planSHA = completenessPlanSHA(report)
	}

	generationReason := "Measures whether this accepted activity produced a digest-bound Go projection."
	if failure != "" {
		generationReason = "Generation stopped before a complete projection was produced: " + failure
	}
	dimensions := []CompletenessDimension{
		completenessDimension("declaration_coverage", boolCount(report.ActivityID != ""), 1,
			"stable activity declarations", "Counts the requested activity only when it resolves to a stable semantic ID.",
			[]string{"source_digest:" + report.SourceDigest, "activity_id:" + report.ActivityID}, false),
		completenessDimension("generation_coverage", boolCount(report.Decision == "PASS" && report.GeneratedDigest != ""), 1,
			"generated Go functions", generationReason,
			[]string{"generated_digest:" + report.GeneratedDigest, "report decision:" + report.Decision}, failure != ""),
		completenessDimension("source_ast_coverage", min(report.LoweredSemanticUnits, report.SourceSemanticUnits), report.SourceSemanticUnits,
			"source semantic units lowered", "Counts supported source-body units represented in the selected Go lowering; it does not estimate unstated intent.",
			[]string{"source_semantic_units", "lowered_semantic_units"}, report.LoweredSemanticUnits > report.SourceSemanticUnits),
		completenessDimension("route_semantic_equivalence", boolCount(report.RouteEquivalence.Decision == "PASS" && report.RouteEquivalence.Equivalent && report.RouteEquivalence.SourceSemanticDigest == report.RouteEquivalence.GeneratedSemanticDigest), 1,
			"source/generated route pairs", "Uses the compiler's closed structural equivalence witness for the selected route.",
			[]string{"route_equivalence.schema:" + report.RouteEquivalence.Schema, "route_equivalence.rule:" + report.RouteEquivalence.Rule, "source_semantic_digest:" + report.RouteEquivalence.SourceSemanticDigest, "generated_semantic_digest:" + report.RouteEquivalence.GeneratedSemanticDigest}, report.RouteEquivalence.Decision == "FAIL_CLOSED"),
		completenessDimension("typecheck_coverage", boolCount(report.TypecheckPassed), 1,
			"generated functions accepted by Go type checking", "Counts the generated function only after the compiler's type checker accepts it.",
			[]string{"typecheck_passed"}, false),
		completenessDimension("internal_replay_coverage", boolCount(report.DeterministicReplay && report.GeneratedDigest == report.ReplayDigest), 1,
			"deterministic compiler emission replays", "Requires replayed generated bytes to match the selected output digest.",
			[]string{"generated_digest:" + report.GeneratedDigest, "replay_digest:" + report.ReplayDigest}, false),
		completenessDimension("route_choice_protocol", boolCount(containsString(report.CandidateRoutes, report.Route)), 1,
			"selected routes in the compiler-declared candidate set", "The selected lowering must be a route the compiler declared eligible for this source shape.",
			[]string{"candidate_routes", "selected_route:" + report.Route}, report.Route != "" && !containsString(report.CandidateRoutes, report.Route)),
		provenanceDimension(report, compilerSHA),
		completenessDimension("repository_write_boundary", boolCount(report.RepositoryWrites == 0), 1,
			"repository writes", "The command emits generated source without mutating the repository.",
			[]string{"repository_writes:" + strconv.Itoa(report.RepositoryWrites)}, report.RepositoryWrites != 0),
		completenessDimension("execution_boundary", 0, 1,
			"generated package runtime executions", "This command typechecks and replays generated source but does not execute the generated package.",
			[]string{"body-codegen does not run generated Go"}, false),
		completenessDimension("permission_boundary", 0, 1,
			"observed host permission profiles", "The report does not capture the caller's operating-system permission profile.",
			[]string{"host permission profile is not observed"}, false),
		networkBoundaryDimension(report),
		layaObservationDimension(report),
		completenessDimension("use_case_coverage", 0, 1,
			"independently sourced real workflows", "A single source fixture is not evidence of independent real-world workflow coverage.",
			[]string{"no independent workflow corpus is bound"}, false),
		completenessDimension("reverse_observation_coverage", 0, 1,
			"generated runtime observations mapped back to source", "No generated runtime is executed or reverse-mapped by this command.",
			[]string{"no source-bound reverse-observation trace"}, false),
		completenessDimension("full_domain_semantics", 0, 1,
			"complete input-domain behavior proofs", "Typechecking and structural equivalence do not prove behavior over the input domain.",
			[]string{"generated package execution and an independent domain oracle are not part of this command"}, false),
		completenessDimension("route_quality", 0, 1,
			"independent route-clarity or utility criteria", "Semantic equivalence does not rank readability, clarity, or downstream utility.",
			[]string{"no independent route-quality oracle"}, false),
		completenessDimension("resource_observation", 0, 1,
			"complete process resource profiles", "The report records route-decision latency but not process CPU time or peak memory.",
			[]string{"route_decision_latency_ms is recorded", "CPU and peak RSS are not captured"}, false),
		completenessDimension("resource_baseline_comparison", 0, 1,
			"compatible prior resource receipts", "No same-profile, same-toolchain resource baseline is bound.",
			[]string{"no compatible prior resource receipt"}, false),
		completenessDimension("semantic_profile_delta", 0, 1,
			"compatible before/after semantic receipts", "No same-plan, same-compiler semantic baseline is bound for regression deltas.",
			[]string{"no comparable prior semantic receipt"}, false),
	}

	core := []string{
		"declaration_coverage", "generation_coverage", "internal_replay_coverage",
		"provenance_integrity", "repository_write_boundary", "route_choice_protocol",
		"route_semantic_equivalence", "source_ast_coverage", "typecheck_coverage",
	}
	sort.Strings(core)
	counts := map[string]int{"PASS": 0, "PROGRESS": 0, "UNKNOWN": 0, "FAIL_CLOSED": 0}
	byID := make(map[string]CompletenessDimension, len(dimensions))
	claims := make([]UnresolvedCompletenessClaim, 0, len(dimensions))
	for _, dimension := range dimensions {
		counts[dimension.Status]++
		byID[dimension.ID] = dimension
		if dimension.Status != "PASS" {
			claims = append(claims, UnresolvedCompletenessClaim{
				ID: dimension.ID, Status: dimension.Status, Reason: dimension.Reason,
				NextOperation: nextCompletenessOperation(dimension.ID),
			})
		}
	}
	decision := "PROGRESS_WITHIN_DECLARED_FIXTURE_SCOPE"
	if failure != "" || counts["FAIL_CLOSED"] > 0 {
		decision = "FAIL_CLOSED"
	} else {
		allCorePass := true
		for _, id := range core {
			allCorePass = allCorePass && byID[id].Status == "PASS"
		}
		if allCorePass {
			decision = "PASS_WITHIN_DECLARED_FIXTURE_SCOPE"
		}
	}
	var first *UnresolvedCompletenessClaim
	if len(claims) > 0 {
		copy := claims[0]
		first = &copy
	}
	var failReason *string
	if failure != "" {
		failReason = &failure
	} else if counts["FAIL_CLOSED"] > 0 {
		for _, dimension := range dimensions {
			if dimension.Status == "FAIL_CLOSED" {
				reason := dimension.Reason
				failReason = &reason
				break
			}
		}
	}
	return &CompletenessReceipt{
		Schema: completenessReceiptSchema, ProfileID: "gooo/body-codegen-pure-v1",
		Decision:      decision,
		DecisionBasis: "declaration, generation, source-unit coverage, route equivalence, typecheck, replay, route protocol, provenance, and zero repository writes define the scoped code-generation core; UNKNOWN dimensions remain explicit and are never aggregated",
		Scope: map[string]any{
			"domain_scope":       "one pure typed Gooo activity body in the closed body-codegen profile, with one Integer, Boolean, or Text input and one supported scalar result",
			"allowed_investment": "compiler-controlled lowering and optional Laya selection only among prevalidated equivalent routes; no human approval or authorization is required",
			"excluded_scope":     []string{"unstated natural-language intent", "independently sourced production workflows", "generated runtime behavior", "unrestricted Gooo body syntax", "route clarity or utility"},
			"plan_sha256":        planSHA, "compiler_source_sha": compilerSHA,
			"toolchain": runtime.Version(), "execution_environment": runtime.GOOS + "/" + runtime.GOARCH,
			"input_type": report.InputType, "output_type": report.OutputType,
			"laya_mode": report.RouteDecision.Mode, "laya_provider": report.RouteDecision.Provider,
			"system_budget":        map[string]int{"maximum_human_actions": 0, "maximum_repository_writes": 0},
			"observed_system_cost": map[string]int{"human_actions": 0, "repository_writes": report.RepositoryWrites},
			"boundary":             map[string]any{"non_executing": true, "non_authorizing": true, "excluded_effects": []string{"generated code execution", "repository mutation", "external authority"}},
		},
		CoreDimensions: core, Dimensions: dimensions, StatusCounts: counts,
		AggregateCompletenessScore: nil, FirstUnresolved: first,
		UnresolvedClaims: claims,
		NotClaimed:       []string{"user-intent completeness", "real-workflow coverage", "generated runtime behavior", "full-domain semantics", "route quality", "universal language completeness"},
		FailClosedReason: failReason,
	}
}

func populateCompletenessReceipt(report *Report, failure string) {
	report.CompilerSourceSHA = compilerSourceSHA()
	report.PlanSHA256 = completenessPlanSHA(*report)
	report.CompletenessReceipt = buildCompletenessReceipt(*report, failure)
}

func completenessPlanSHA(report Report) string {
	planBytes, _ := json.Marshal(completenessPlanIdentity{
		ProfileID: "gooo/body-codegen-pure-v1", Activity: report.Activity,
		ActivityID: report.ActivityID, InputType: report.InputType, OutputType: report.OutputType,
		SourceDigest: report.SourceDigest, ProgramDigest: report.ProgramDigest,
	})
	return digest(planBytes)
}

// FailureCompletenessReceipt preserves the stage and cause when the CLI cannot
// return a generated projection, including source-read and parse failures.
func FailureCompletenessReceipt(activity string, source []byte, failure string) *CompletenessReceipt {
	sourceDigest := "UNBOUND_SOURCE"
	if source != nil {
		sourceDigest = digest(source)
	}
	report := Report{
		Decision: "FAIL_CLOSED", Activity: activity, SourceDigest: sourceDigest,
		RepositoryWrites: 0,
	}
	populateCompletenessReceipt(&report, failure)
	return report.CompletenessReceipt
}

func completenessDimension(id string, numerator, denominator int, unit, reason string, evidence []string, failClosed bool) CompletenessDimension {
	status := "UNKNOWN"
	if failClosed || numerator < 0 || denominator < 0 || numerator > denominator {
		status = "FAIL_CLOSED"
	} else if denominator > 0 && numerator > 0 {
		if numerator >= denominator {
			status = "PASS"
		} else {
			status = "PROGRESS"
		}
	}
	return CompletenessDimension{ID: id, Status: status, Numerator: numerator, Denominator: denominator,
		Unit: unit, Reason: reason, Evidence: evidence}
}

func provenanceDimension(report Report, compilerSHA string) CompletenessDimension {
	checks := []bool{
		validDigest(report.SourceDigest), validDigest(report.ProgramDigest),
		validDigest(report.GeneratedDigest), validDigest(report.ReplayDigest),
		report.ActivityID != "", validCommitSHA(compilerSHA),
		validDigest(report.RouteEquivalence.SourceSemanticDigest),
		validDigest(report.RouteEquivalence.GeneratedSemanticDigest),
	}
	numerator := 0
	for _, check := range checks {
		if check {
			numerator++
		}
	}
	return completenessDimension("provenance_integrity", numerator, len(checks),
		"source, body, output, replay, semantic-ID, and compiler-revision bindings",
		"Binds the source, selected body, generated and replay digests, stable activity ID, route semantic digests, and an unmodified compiler revision when embedded in the binary.",
		[]string{"source_digest:" + report.SourceDigest, "program_digest:" + report.ProgramDigest,
			"generated_digest:" + report.GeneratedDigest, "replay_digest:" + report.ReplayDigest,
			"activity_id:" + report.ActivityID, "compiler_source_sha:" + compilerSHA,
			"route_equivalence semantic digests"}, false)
}

func networkBoundaryDimension(report Report) CompletenessDimension {
	noProviderCall := report.RouteDecision.Mode == "deterministic_fallback" &&
		(report.RouteDecision.FallbackReason == "NOT_CONFIGURED" || report.RouteDecision.FallbackReason == "NO_ALTERNATIVE_ROUTE")
	numerator := boolCount(noProviderCall)
	return completenessDimension("external_network_boundary", numerator, 1,
		"runs with no Laya provider request", "A deterministic fallback caused by an unconfigured provider or ineligible alternative routes records no Laya decision request; other provider/network scope is not audited.",
		[]string{"route_decision.mode:" + report.RouteDecision.Mode, "route_decision.provider:" + report.RouteDecision.Provider,
			"route_decision.fallback_reason:" + report.RouteDecision.FallbackReason}, false)
}

func layaObservationDimension(report Report) CompletenessDimension {
	eligible := len(report.CandidateRoutes) > 1
	observed := eligible && report.RouteDecision.Mode == "laya"
	numerator, denominator := 0, 0
	if eligible {
		denominator = 1
		numerator = boolCount(observed)
	}
	return completenessDimension("laya_decision_observation", numerator, denominator,
		"eligible multi-route Laya decisions", "Records a model choice only when the source shape has multiple compiler-approved routes and the Laya provider supplied the decision.",
		[]string{"candidate_routes", "route_decision.mode:" + report.RouteDecision.Mode,
			"route_decision.request_sha256:" + report.RouteDecision.RequestSHA256,
			"route_decision.model_revision:" + report.RouteDecision.ModelRevision}, false)
}

func nextCompletenessOperation(id string) string {
	operations := map[string]string{
		"declaration_coverage":         "BIND_THE_REQUESTED_ACTIVITY_TO_A_STABLE_SOURCE_ID",
		"generation_coverage":          "REPAIR_OR_REGENERATE_THE_ACTIVITY_PROJECTION",
		"source_ast_coverage":          "LOWER_EVERY_ACCEPTED_SOURCE_AST_UNIT_OR_FAIL_CLOSED",
		"route_semantic_equivalence":   "REPAIR_THE_SELECTED_ROUTE_OR_ITS_SEMANTIC_WITNESS",
		"typecheck_coverage":           "REPAIR_GENERATED_GO_TYPE_ERRORS",
		"internal_replay_coverage":     "REPLAY_THE_SELECTED_EMISSION_AND_COMPARE_DIGESTS",
		"route_choice_protocol":        "SELECT_ONLY_FROM_THE_COMPILER_DECLARED_CANDIDATE_SET",
		"provenance_integrity":         "EMBED_AND_BIND_THE_EXACT_COMPILER_SOURCE_REVISION",
		"boundary_coverage":            "KEEP_CODEGEN_NON_EXECUTING_NON_AUTHORIZING_AND_ZERO_WRITE",
		"execution_boundary":           "EXECUTE_GENERATED_CODE_IN_A_SEPARATE_BOUNDED_RUNNER",
		"permission_boundary":          "RECORD_THE_HOST_PERMISSION_PROFILE_WITHOUT_GRANTING_AUTHORITY",
		"external_network_boundary":    "RECORD_AND_AUDIT_THE_CONFIGURED_PROVIDER_NETWORK_SCOPE",
		"laya_decision_observation":    "RUN_AN_ELIGIBLE_CASE_WITH_A_PINNED_LAYA_REVISION",
		"use_case_coverage":            "BIND_INDEPENDENTLY_SOURCED_REAL_WORKFLOW_FIXTURES",
		"reverse_observation_coverage": "MAP_GENERATED_RUNTIME_OBSERVATIONS_BACK_TO_SOURCE_IDS",
		"full_domain_semantics":        "EXECUTE_A_DOMAIN_PARTITION_OR_PROOF_FOR_THE_DECLARED_INPUT_TYPE",
		"route_quality":                "ADD_AN_INDEPENDENT_ROUTE_CLARITY_OR_UTILITY_ORACLE",
		"resource_observation":         "CAPTURE_WALL_CPU_AND_PEAK_RSS_FOR_THE_COMPILER_PROCESS",
		"resource_baseline_comparison": "BIND_A_COMPATIBLE_RESOURCE_BASELINE",
		"semantic_profile_delta":       "BIND_A_COMPATIBLE_BASELINE_AND_REPORT_PER_DIMENSION_DELTAS",
	}
	return operations[id]
}

func compilerSourceSHA() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return "UNBOUND_LOCAL_SOURCE"
	}
	settings := make(map[string]string, len(info.Settings))
	for _, setting := range info.Settings {
		settings[setting.Key] = setting.Value
	}
	revision := settings["vcs.revision"]
	if settings["vcs.modified"] != "false" || !validCommitSHA(revision) {
		return "UNBOUND_LOCAL_SOURCE"
	}
	return revision
}

func validCommitSHA(value string) bool {
	if len(value) != 40 || strings.ToLower(value) != value {
		return false
	}
	for _, char := range value {
		if !((char >= '0' && char <= '9') || (char >= 'a' && char <= 'f')) {
			return false
		}
	}
	return true
}

func validDigest(value string) bool {
	if !strings.HasPrefix(value, "sha256:") || len(value) != len("sha256:")+64 {
		return false
	}
	for _, char := range strings.TrimPrefix(value, "sha256:") {
		if !((char >= '0' && char <= '9') || (char >= 'a' && char <= 'f')) {
			return false
		}
	}
	return true
}

func boolCount(value bool) int {
	if value {
		return 1
	}
	return 0
}

func containsString(values []string, target string) bool {
	return slices.Contains(values, target)
}
