package bodycodegen

import (
	"encoding/json"
	"runtime"
	"runtime/debug"
	"slices"
	"sort"
	"strconv"
	"strings"

	"github.com/kimjooyoon/meta-ontology-go/internal/completeness"
)

const completenessReceiptSchema = completeness.CompletenessReceiptSchema

type CompletenessDimension = completeness.CompletenessDimension
type UnresolvedCompletenessClaim = completeness.UnresolvedCompletenessClaim
type CompletenessReceipt = completeness.CompletenessReceipt

type completenessPlanIdentity struct {
	ProfileID                    string `json:"profile_id"`
	Activity                     string `json:"activity"`
	ActivityID                   string `json:"activity_id"`
	InputType                    string `json:"input_type"`
	OutputType                   string `json:"output_type"`
	SourceDigest                 string `json:"source_digest"`
	ProgramDigest                string `json:"program_digest"`
	BodyFillPlanSHA256           string `json:"body_fill_plan_sha256,omitempty"`
	BodySearchPlanSHA256         string `json:"body_search_plan_sha256,omitempty"`
	BodyPathDocumentSHA256       string `json:"body_path_document_sha256,omitempty"`
	BodyPathOriginalSourceSHA256 string `json:"body_path_original_source_sha256,omitempty"`
	BodyPathSearchConfigSHA256   string `json:"body_path_search_config_sha256,omitempty"`
	RecordAssemblyContractSHA256 string `json:"record_assembly_contract_sha256,omitempty"`
	RecordAssemblyOriginalSHA256 string `json:"record_assembly_original_source_sha256,omitempty"`
}

func buildCompletenessReceipt(report Report, failure string) *CompletenessReceipt {
	compilerSHA := report.CompilerSourceSHA
	if compilerSHA == "" {
		compilerSHA = "UNBOUND_LOCAL_SOURCE"
	}
	planSHA := report.PlanSHA256
	if planSHA == "" {
		planSHA = completenessPlanSHA(report)
	}
	layaMode := report.RouteDecision.Mode
	layaProvider := report.RouteDecision.Provider
	decisionMode := report.RouteDecision.Mode
	decisionProvider := report.RouteDecision.Provider
	if report.BodyFill != nil {
		layaMode = report.BodyFill.Decision.Mode
		layaProvider = report.BodyFill.Decision.Provider
		decisionMode = report.BodyFill.Decision.Mode
		decisionProvider = report.BodyFill.Decision.Provider
		if decisionProvider == "tiny_go" {
			layaMode, layaProvider = "", ""
		}
	}
	if report.BodySearch != nil {
		layaMode, layaProvider = bodySearchProviderSummary(report.BodySearch)
		decisionMode, decisionProvider = layaMode, layaProvider
	}

	generationReason := "Measures whether this accepted activity produced a digest-bound Go projection."
	if failure != "" {
		generationReason = "Generation stopped before a complete projection was produced: " + failure
	}
	dimensions := []CompletenessDimension{
		completenessDimension("declaration_coverage", boolCount(report.ActivityID != ""), 1,
			"stable activity declarations", "Counts the requested activity only when it resolves to a stable semantic ID.",
			[]string{"source_digest:" + report.SourceDigest, "activity_id:" + report.ActivityID}, false),
		completenessDimension("generation_coverage", boolCount(report.Decision == "PASS" && report.GeneratedDigest != ""), 1,
			"generated Go functions", generationReason,
			[]string{"generated_digest:" + report.GeneratedDigest, "report decision:" + report.Decision}, failure != ""),
		completenessDimension("source_ast_coverage", min(report.LoweredSemanticUnits, report.SourceSemanticUnits), report.SourceSemanticUnits,
			"source semantic units lowered", "Counts supported source-body units represented in the selected Go lowering; it does not estimate unstated intent.",
			[]string{"source_semantic_units", "lowered_semantic_units"}, report.LoweredSemanticUnits > report.SourceSemanticUnits),
		completenessDimension("route_semantic_equivalence", boolCount(report.RouteEquivalence.Decision == "PASS" && report.RouteEquivalence.Equivalent && report.RouteEquivalence.SourceSemanticDigest == report.RouteEquivalence.GeneratedSemanticDigest), 1,
			"source/generated route pairs", "Uses the compiler's closed structural equivalence witness for the selected route.",
			[]string{"route_equivalence.schema:" + report.RouteEquivalence.Schema, "route_equivalence.rule:" + report.RouteEquivalence.Rule, "source_semantic_digest:" + report.RouteEquivalence.SourceSemanticDigest, "generated_semantic_digest:" + report.RouteEquivalence.GeneratedSemanticDigest}, report.RouteEquivalence.Decision == "FAIL_CLOSED"),
		completenessDimension("typecheck_coverage", boolCount(report.TypecheckPassed), 1,
			"generated functions accepted by Go type checking", "Counts the generated function only after the compiler's type checker accepts it.",
			[]string{"typecheck_passed"}, false),
		completenessDimension("internal_replay_coverage", boolCount(report.DeterministicReplay && report.GeneratedDigest == report.ReplayDigest), 1,
			"deterministic compiler emission replays", "Requires replayed generated bytes to match the selected output digest.",
			[]string{"generated_digest:" + report.GeneratedDigest, "replay_digest:" + report.ReplayDigest}, false),
		completenessDimension("route_choice_protocol", boolCount(containsString(report.CandidateRoutes, report.Route)), 1,
			"selected routes in the compiler-declared candidate set", "The selected lowering must be a route the compiler declared eligible for this source shape.",
			[]string{"candidate_routes", "selected_route:" + report.Route}, report.Route != "" && !containsString(report.CandidateRoutes, report.Route)),
		provenanceDimension(report, compilerSHA),
		completenessDimension("receipt_schema_binding", boolCount(completeness.DeclarationMatchesProjection()), 1,
			"source-owned receipt schema and generated structure bindings", "The receipt data structure is generated from the embedded Gooo declaration with stable entity and field IDs.",
			[]string{"receipt_declaration_sha256:" + completeness.DeclarationSHA256, "projection_profile:" + completeness.ProjectionProfile}, !completeness.DeclarationMatchesProjection()),
		completenessDimension("repository_write_boundary", boolCount(report.RepositoryWrites == 0), 1,
			"repository writes", "The command emits generated source without mutating the repository.",
			[]string{"repository_writes:" + strconv.Itoa(report.RepositoryWrites)}, report.RepositoryWrites != 0),
		completenessDimension("execution_boundary", 0, 1,
			"generated package runtime executions", "This command typechecks and replays generated source but does not execute the generated package.",
			[]string{"body-codegen does not run generated Go"}, false),
		completenessDimension("permission_boundary", 0, 1,
			"observed host permission profiles", "The report does not capture the caller's operating-system permission profile.",
			[]string{"host permission profile is not observed"}, false),
		networkBoundaryDimension(report),
		layaObservationDimension(report),
		completenessDimension("use_case_coverage", 0, 1,
			"independently sourced real workflows", "A single source fixture is not evidence of independent real-world workflow coverage.",
			[]string{"no independent workflow corpus is bound"}, false),
		completenessDimension("reverse_observation_coverage", 0, 1,
			"generated runtime observations mapped back to source", "No generated runtime is executed or reverse-mapped by this command.",
			[]string{"no source-bound reverse-observation trace"}, false),
		completenessDimension("full_domain_semantics", 0, 1,
			"complete input-domain behavior proofs", "Typechecking and structural equivalence do not prove behavior over the input domain.",
			[]string{"generated package execution and an independent domain oracle are not part of this command"}, false),
		completenessDimension("route_quality", 0, 1,
			"independent route-clarity or utility criteria", "Semantic equivalence does not rank readability, clarity, or downstream utility.",
			[]string{"no independent route-quality oracle"}, false),
		completenessDimension("resource_observation", 0, 1,
			"complete process resource profiles", "The report records route-decision latency but not process CPU time or peak memory.",
			[]string{"route_decision_latency_ms is recorded", "CPU and peak RSS are not captured"}, false),
		completenessDimension("resource_baseline_comparison", 0, 1,
			"compatible prior resource receipts", "No same-profile, same-toolchain resource baseline is bound.",
			[]string{"no compatible prior resource receipt"}, false),
		completenessDimension("semantic_profile_delta", 0, 1,
			"compatible before/after semantic receipts", "No same-plan, same-compiler semantic baseline is bound for regression deltas.",
			[]string{"no comparable prior semantic receipt"}, false),
	}

	core := []string{
		"declaration_coverage", "generation_coverage", "internal_replay_coverage",
		"provenance_integrity", "repository_write_boundary", "route_choice_protocol",
		"route_semantic_equivalence", "source_ast_coverage", "typecheck_coverage",
		"receipt_schema_binding",
	}
	allowedInvestment := "compiler-controlled lowering and optional Laya selection only among prevalidated equivalent routes; no human approval or authorization is required"
	if fill := report.BodyFill; fill != nil {
		dimension := completenessDimension("declared_suite_functional_accuracy", fill.TestCasesPassed, fill.TestCasesTotal,
			"declared test cases matched by the emitted body in the bounded AST evaluator",
			"Measures the declared selection suite only; held-out behavior, generated-package execution, and full-domain correctness require separate evidence.",
			[]string{"body_fill.evaluator:" + fill.Evaluator, "body_fill.test_suite_sha256:" + fill.TestSuiteSHA256,
				"body_fill.ir_plan_sha256:" + fill.IRPlanSHA256, "generated_digest:" + report.GeneratedDigest}, false)
		if fill.TestCasesTotal > 0 && fill.TestCasesPassed == 0 {
			dimension.Status = "PROGRESS"
		}
		dimensions = append(dimensions, dimension)
		if probes := fill.BehavioralProbes; probes != nil {
			probeEvaluationsTotal := probes.CandidateCount * probes.ProbeInputsTotal
			probeEvaluationsCompleted := probes.CandidateRunsCompleted * len(probes.ProbeInputs)
			probeCoverage := completenessDimension("body_fill_candidate_probe_coverage",
				probeEvaluationsCompleted, probeEvaluationsTotal,
				"candidate-by-input observations executed over deterministic training-derived integer probes",
				"This measures automatic diagnostic probe execution coverage; candidate disagreement is not correctness or intent evidence.",
				[]string{"body_fill.behavioral_probes.schema:" + probes.Schema,
					"body_fill.behavioral_probes.profile_sha256:" + probes.ProbeProfileSHA256,
					"body_fill.behavioral_probes.candidate_runs_failed:" + strconv.Itoa(probes.CandidateRunsFailed),
					"body_fill.behavioral_probes.distinguished_pairs:" + strconv.Itoa(probes.CandidatePairsDistinguished),
					"body_fill.behavioral_probes.probe_inputs_with_disagreement:" + strconv.Itoa(probes.ProbeInputsWithDisagreement)}, false)
			dimensions = append(dimensions, probeCoverage)
			core = append(core, probeCoverage.ID)
		}
		if fill.HoldoutCasesTotal > 0 {
			holdout := completenessDimension("body_fill_holdout_accuracy",
				fill.HoldoutCasesPassed, fill.HoldoutCasesTotal,
				"held-out cases matched by the final emitted body after candidate selection",
				"Held-out cases are withheld from the chooser and training score; this is an observed finite check, not an all-domain proof.",
				[]string{"body_fill.holdout_suite_sha256:" + fill.HoldoutSuiteSHA256,
					"body_fill.ir_plan_sha256:" + fill.IRPlanSHA256, "generated_digest:" + report.GeneratedDigest}, false)
			if fill.HoldoutCasesPassed == 0 {
				holdout.Status = "PROGRESS"
			}
			dimensions = append(dimensions, holdout)
			core = append(core, holdout.ID)
		}
		if generated := fill.CandidateGeneration; generated != nil {
			grammar := completenessDimension("body_fill_candidate_grammar_coverage",
				generated.ExpressionsRetainedTotal, generated.ExpressionCandidatesTotal,
				"per-hole expressions retained from the declared bounded grammar",
				"A complete grammar score covers only each named expression grammar derived from training examples; it does not establish intent or all-domain semantics.",
				[]string{"body_fill.candidate_generation.grammar:" + generated.Grammar,
					"body_fill.candidate_generation.candidate_set_sha256:" + generated.CandidateSetSHA256}, false)
			for _, hole := range generated.HoleGrammars {
				grammar.Evidence = append(grammar.Evidence, "hole:"+hole.HoleID+",grammar:"+hole.Grammar+
					",retained:"+strconv.Itoa(hole.ExpressionsRetained)+",total:"+strconv.Itoa(hole.ExpressionCandidatesTotal))
			}
			if !generated.GrammarComplete {
				grammar.Status = "PROGRESS"
			}
			assignmentDenominator := int(generated.AssignmentSpaceSize)
			if uint64(assignmentDenominator) != generated.AssignmentSpaceSize {
				assignmentDenominator = int(^uint(0) >> 1)
			}
			assignments := completenessDimension("body_fill_assignment_space_coverage",
				generated.AssignmentsRetained, assignmentDenominator,
				"complete assignments enumerated from the source-declared per-hole expression sets",
				"This reports the lexicographic prefix explored under the explicit assignment cap; omitted assignments may contain better candidates.",
				[]string{"body_fill.candidate_generation.assignments_omitted:" + strconv.FormatUint(generated.AssignmentsOmitted, 10),
					"body_fill.candidate_generation.assignment_coverage_percent:" + strconv.FormatFloat(generated.AssignmentCoveragePercent, 'f', 4, 64)}, false)
			if generated.AssignmentsOmitted > 0 {
				assignments.Status = "PROGRESS"
			}
			dimensions = append(dimensions, grammar, assignments)
			core = append(core, grammar.ID, assignments.ID)
			allowedInvestment = "Gooo-derived typed expression candidates from source-owned examples, optional model ranking among complete assignments, and measured finite-suite evidence; no human approval or authorization is required"
		}
		dimensions = append(dimensions, completenessDimension("provider_execution_accounting",
			boolCount(fill.ExternalProviderCallsKnown), 1,
			"body-fill provider executions classified as local predictions or external calls",
			"Counts local model predictions separately from external provider calls; unknown failed request outcomes remain unknown.",
			[]string{"body_fill.local_model_predictions:" + strconv.Itoa(fill.LocalModelPredictions),
				"body_fill.external_provider_calls:" + strconv.Itoa(fill.ExternalProviderCalls),
				"body_fill.external_provider_calls_known:" + strconv.FormatBool(fill.ExternalProviderCallsKnown)}, false))
		core = append(core, dimension.ID)
		if decisionProvider == "tiny_go" {
			allowedInvestment = "compiler-controlled assembly from declared expression candidates, measured finite-suite scores, and an optional local tiny_go operation prediction; no human approval or authorization is required"
		} else {
			allowedInvestment = "compiler-controlled assembly from declared expression candidates, measured finite-suite scores, and an optional Laya proposal; no human approval or authorization is required"
		}
	}
	if search := report.BodySearch; search != nil {
		searchDimensions, searchCore := bodySearchCompletenessDimensions(search, report.GeneratedDigest)
		dimensions = append(dimensions, searchDimensions...)
		core = append(core, searchCore...)
		allowedInvestment = "bounded candidate search before evaluation, prior training observations, and independent post-selection holdout measurement; no human approval or authorization is required"
	}
	if report.BodyPaths != nil {
		pathDimensions, pathCore := bodyPathCompletenessDimensions(report)
		dimensions = append(dimensions, pathDimensions...)
		core = append(core, pathCore...)
		allowedInvestment = "source-bound typed alternatives, optional local predictions and finite TDD within declared budgets; CI is caller context; no human actions or repository writes"
	}
	if report.RecordAssembly != nil {
		for _, dimension := range recordAssemblyDimensions(report.RecordAssembly) {
			dimensions = append(dimensions, dimension)
			core = append(core, dimension.ID)
		}
		allowedInvestment = "source-bound record field expressions, optional local ordinal ranking, and finite field observations within the source budget"
	}
	sort.Strings(core)
	counts := map[string]int{"PASS": 0, "PROGRESS": 0, "UNKNOWN": 0, "FAIL_CLOSED": 0}
	byID := make(map[string]CompletenessDimension, len(dimensions))
	claims := make([]UnresolvedCompletenessClaim, 0, len(dimensions))
	for _, dimension := range dimensions {
		counts[dimension.Status]++
		byID[dimension.ID] = dimension
		if dimension.Status != "PASS" {
			claims = append(claims, UnresolvedCompletenessClaim{
				ID: dimension.ID, Status: dimension.Status, Reason: dimension.Reason,
				NextOperation: nextCompletenessOperation(dimension.ID),
			})
		}
	}
	decision := "PROGRESS_WITHIN_DECLARED_FIXTURE_SCOPE"
	if failure != "" || counts["FAIL_CLOSED"] > 0 {
		decision = "FAIL_CLOSED"
	} else {
		allCorePass := true
		for _, id := range core {
			allCorePass = allCorePass && byID[id].Status == "PASS"
		}
		if allCorePass {
			decision = "PASS_WITHIN_DECLARED_FIXTURE_SCOPE"
		}
	}
	var first *UnresolvedCompletenessClaim
	if len(claims) > 0 {
		copy := claims[0]
		first = &copy
	}
	var failReason *string
	if failure != "" {
		failReason = &failure
	} else if counts["FAIL_CLOSED"] > 0 {
		for _, dimension := range dimensions {
			if dimension.Status == "FAIL_CLOSED" {
				reason := dimension.Reason
				failReason = &reason
				break
			}
		}
	}
	receipt := &CompletenessReceipt{
		Schema: completenessReceiptSchema, ProfileID: "gooo/body-codegen-pure-v1",
		Decision:      decision,
		DecisionBasis: "declaration, generation, source-unit coverage, route equivalence, typecheck, replay, route protocol, provenance, and zero repository writes define the scoped code-generation core; body-fill additionally requires declared-suite functional accuracy; UNKNOWN dimensions remain explicit and are never aggregated",
		Scope: map[string]any{
			"receipt_declaration": completeness.ContractBinding(),
			"domain_scope":        "one pure typed Gooo activity body in the closed scalar or declared-record body-codegen profile",
			"allowed_investment":  allowedInvestment,
			"excluded_scope":      []string{"unstated natural-language intent", "independently sourced production workflows", "generated runtime behavior", "unrestricted Gooo body syntax", "route clarity or utility"},
			"plan_sha256":         planSHA, "compiler_source_sha": compilerSHA,
			"toolchain": runtime.Version(), "execution_environment": runtime.GOOS + "/" + runtime.GOARCH,
			"input_type": report.InputType, "output_type": report.OutputType,
			"decision_mode": decisionMode, "decision_provider": decisionProvider,
			"laya_mode": layaMode, "laya_provider": layaProvider,
			"system_budget":        map[string]int{"maximum_human_actions": 0, "maximum_repository_writes": 0},
			"observed_system_cost": map[string]int{"human_actions": 0, "repository_writes": report.RepositoryWrites},
			"boundary":             map[string]any{"non_executing": true, "non_authorizing": true, "excluded_effects": []string{"generated code execution", "repository mutation", "external authority"}},
		},
		CoreDimensions: core, Dimensions: dimensions, StatusCounts: counts,
		AggregateCompletenessScore: nil, FirstUnresolved: first,
		UnresolvedClaims: claims,
		NotClaimed:       []string{"user-intent completeness", "real-workflow coverage", "generated runtime behavior", "full-domain semantics", "route quality", "universal language completeness"},
		FailClosedReason: failReason,
	}
	if len(report.RecordTypes) > 0 {
		receipt.Scope["record_types"] = append([]RecordType(nil), report.RecordTypes...)
		if hasOptionalRecordFields(report.RecordTypes) {
			receipt.Scope["record_body_scope"] = "optional single scalar fields use typed pointers for copy and transport; learned optional-value synthesis is outside this profile"
			receipt.NotClaimed = append(receipt.NotClaimed, "learned synthesis of optional record values")
		}
	}
	if report.BodyPaths != nil {
		bindPathCompletenessScope(receipt, report)
	}
	if report.RecordAssembly != nil {
		bindRecordAssemblyScope(receipt, report)
	}
	return receipt
}

func hasOptionalRecordFields(records []RecordType) bool {
	for _, record := range records {
		for _, field := range record.Fields {
			if field.Presence == "optional" {
				return true
			}
		}
	}
	return false
}

func populateCompletenessReceipt(report *Report, failure string) {
	report.CompilerSourceSHA = compilerSourceSHA()
	report.PlanSHA256 = completenessPlanSHA(*report)
	report.CompletenessReceipt = buildCompletenessReceipt(*report, failure)
}

func completenessPlanSHA(report Report) string {
	fillPlanSHA256 := ""
	searchPlanSHA256 := ""
	pathDocument, pathOriginal, pathConfig := "", "", ""
	recordContract, recordOriginal := "", ""
	if r := report.RecordAssembly; r != nil {
		recordContract, recordOriginal = r.ContractSHA256, r.OriginalSourceSHA256
	}
	if report.BodyFill != nil {
		fillPlanSHA256 = report.BodyFill.IRPlanSHA256
	}
	if report.BodySearch != nil {
		searchPlanSHA256 = report.BodySearch.IRPlanSHA256
	}
	if path := report.BodyPaths; path != nil {
		pathDocument, pathOriginal, pathConfig = path.DocumentSHA256, path.OriginalSourceSHA256, path.SearchConfigSHA256
	}
	planBytes, _ := json.Marshal(completenessPlanIdentity{
		ProfileID: completenessProfile(report), Activity: report.Activity,
		ActivityID: report.ActivityID, InputType: report.InputType, OutputType: report.OutputType,
		SourceDigest: report.SourceDigest, ProgramDigest: report.ProgramDigest,
		BodyFillPlanSHA256:     fillPlanSHA256,
		BodySearchPlanSHA256:   searchPlanSHA256,
		BodyPathDocumentSHA256: pathDocument, BodyPathOriginalSourceSHA256: pathOriginal,
		BodyPathSearchConfigSHA256:   pathConfig,
		RecordAssemblyContractSHA256: recordContract, RecordAssemblyOriginalSHA256: recordOriginal,
	})
	return digest(planBytes)
}

func SearchFailureCompletenessReceipt(activity string, source []byte, failure string, search *IRBodySearchReceipt) *CompletenessReceipt {
	report := Report{Decision: "FAIL_CLOSED", Activity: activity, SourceDigest: digest(source), BodySearch: search}
	populateCompletenessReceipt(&report, failure)
	return report.CompletenessReceipt
}

// FailureCompletenessReceipt preserves the stage and cause when the CLI cannot
// return a generated projection, including source-read and parse failures.
func FailureCompletenessReceipt(activity string, source []byte, failure string) *CompletenessReceipt {
	sourceDigest := "UNBOUND_SOURCE"
	if source != nil {
		sourceDigest = digest(source)
	}
	report := Report{
		Decision: "FAIL_CLOSED", Activity: activity, SourceDigest: sourceDigest,
		RepositoryWrites: 0,
	}
	populateCompletenessReceipt(&report, failure)
	return report.CompletenessReceipt
}

func completenessDimension(id string, numerator, denominator int, unit, reason string, evidence []string, failClosed bool) CompletenessDimension {
	status := "UNKNOWN"
	if failClosed || numerator < 0 || denominator < 0 || numerator > denominator {
		status = "FAIL_CLOSED"
	} else if denominator > 0 && numerator > 0 {
		if numerator >= denominator {
			status = "PASS"
		} else {
			status = "PROGRESS"
		}
	}
	return CompletenessDimension{ID: id, Status: status, Numerator: numerator, Denominator: denominator,
		Unit: unit, Reason: reason, Evidence: evidence}
}

func provenanceDimension(report Report, compilerSHA string) CompletenessDimension {
	checks := []bool{
		validDigest(report.SourceDigest), validDigest(report.ProgramDigest),
		validDigest(report.GeneratedDigest), validDigest(report.ReplayDigest),
		report.ActivityID != "", validCommitSHA(compilerSHA),
		validDigest(report.RouteEquivalence.SourceSemanticDigest),
		validDigest(report.RouteEquivalence.GeneratedSemanticDigest),
	}
	numerator := 0
	for _, check := range checks {
		if check {
			numerator++
		}
	}
	return completenessDimension("provenance_integrity", numerator, len(checks),
		"source, body, output, replay, semantic-ID, and compiler-revision bindings",
		"Binds the source, selected body, generated and replay digests, stable activity ID, route semantic digests, and an unmodified compiler revision when embedded in the binary.",
		[]string{"source_digest:" + report.SourceDigest, "program_digest:" + report.ProgramDigest,
			"generated_digest:" + report.GeneratedDigest, "replay_digest:" + report.ReplayDigest,
			"activity_id:" + report.ActivityID, "compiler_source_sha:" + compilerSHA,
			"route_equivalence semantic digests"}, false)
}

func networkBoundaryDimension(report Report) CompletenessDimension {
	if report.BodyPaths != nil {
		return bodyPathNetworkDimension(report.BodyPaths)
	}
	if search := report.BodySearch; search != nil {
		noProviderOperation := search.ProviderOperations == 0
		return completenessDimension("external_network_boundary", boolCount(noProviderOperation), 1,
			"search runs with no configured-provider resolver operations", "A zero operation count establishes that no provider resolver call was configured; completed candidate attempts are tracked separately.",
			[]string{"body_search.provider_operations:" + strconv.Itoa(search.ProviderOperations), "body_search.attempts"}, false)
	}
	decision := report.RouteDecision
	if report.BodyFill != nil {
		decision = report.BodyFill.Decision
		if decision.Provider == "tiny_go" && report.BodyFill.ExternalProviderCallsKnown &&
			report.BodyFill.ExternalProviderCalls == 0 {
			return completenessDimension("external_network_boundary", 1, 1,
				"local tiny_go prediction runs with no external provider calls",
				"The selected body-fill provider executed the local model and recorded zero external provider calls.",
				[]string{"body_fill.local_model_predictions:" + strconv.Itoa(report.BodyFill.LocalModelPredictions),
					"body_fill.external_provider_calls:0", "decision.provider:tiny_go"}, false)
		}
	}
	noProviderCall := decision.Mode == "deterministic_fallback" &&
		(decision.FallbackReason == "NOT_CONFIGURED" || decision.FallbackReason == "NO_ALTERNATIVE_ROUTE")
	numerator := boolCount(noProviderCall)
	return completenessDimension("external_network_boundary", numerator, 1,
		"runs with no Laya provider request", "A deterministic fallback caused by an unconfigured provider or ineligible alternative routes records no Laya decision request; other provider/network scope is not audited.",
		[]string{"decision.mode:" + decision.Mode, "decision.provider:" + decision.Provider,
			"decision.fallback_reason:" + decision.FallbackReason}, false)
}

func layaObservationDimension(report Report) CompletenessDimension {
	if report.BodyPaths != nil {
		return completenessDimension("laya_decision_observation", 0, 0,
			"eligible Laya decisions", "Typed-path search uses local predictions or deterministic choices; Laya is not configured.",
			[]string{"body_paths.search.selection", "typed_path_provider_accounting"}, false)
	}
	if search := report.BodySearch; search != nil {
		observed, eligible := 0, 0
		for _, attempt := range search.Attempts {
			if attempt.Decision != nil {
				eligible++
				observed += boolCount(attempt.Decision.Mode == "laya")
			}
		}
		return completenessDimension("laya_decision_observation", observed, eligible,
			"multi-candidate search choices before evaluation", "Counts model choices before candidate evaluation; this does not measure candidate correctness.",
			[]string{"body_search.attempts.decision", "body_search.ir_plan_sha256:" + search.IRPlanSHA256}, false)
	}
	eligible := len(report.CandidateRoutes) > 1
	decision := report.RouteDecision
	unit := "eligible multi-route Laya decisions"
	evidence := []string{"candidate_routes", "route_decision.mode:" + decision.Mode,
		"route_decision.request_sha256:" + decision.RequestSHA256,
		"route_decision.model_revision:" + decision.ModelRevision}
	if report.BodyFill != nil {
		eligible = len(report.BodyFill.CandidateScores) > 1
		decision = report.BodyFill.Decision
		if decision.Provider == "tiny_go" {
			return completenessDimension("laya_decision_observation", 0, 0,
				"eligible Laya decisions; local tiny_go choices are counted separately",
				"This run used local tiny_go inference and made no Laya decision request.",
				[]string{"body_fill.decision.provider:tiny_go", "body_fill.decision.mode:" + decision.Mode}, false)
		}
		unit = "eligible IR body-fill decisions"
		evidence = []string{"body_fill.candidate_scores", "body_fill.decision.mode:" + decision.Mode,
			"body_fill.decision.request_sha256:" + decision.RequestSHA256,
			"body_fill.decision.model_revision:" + decision.ModelRevision}
	}
	observed := eligible && decision.Mode == "laya"
	numerator, denominator := 0, 0
	if eligible {
		denominator = 1
		numerator = boolCount(observed)
	}
	return completenessDimension("laya_decision_observation", numerator, denominator,
		unit, "Records a model choice only after Gooo has declared multiple typed candidates and the Laya provider supplied the decision.", evidence, false)
}

func nextCompletenessOperation(id string) string {
	operations := map[string]string{
		"typed_path_source_binding":          "BIND_ORIGINAL_SOURCE_DOCUMENT_SEARCH_CONFIG_AND_SELECTED_BODY",
		"typed_path_finite_accuracy":         "CONTINUE_TYPED_CANDIDATES_AGAINST_DECLARED_FAILURES_AND_MEASURE_UNSEEN_INPUTS_SEPARATELY",
		"typed_path_provider_accounting":     "RECORD_LOCAL_PREDICTIONS_MODEL_PINS_AND_EXTERNAL_CALL_COUNTS",
		"typed_path_candidate_observation":   "CONTINUE_UNATTEMPTED_TYPED_PATHS_WITHIN_THE_DECLARED_BUDGET",
		"typed_path_candidate_scoring":       "REPAIR_TYPE_REJECTIONS_AND_SCORE_REMAINING_DECLARED_CANDIDATES",
		"search_training_accuracy":           "EXPAND_OR_REPAIR_CANDIDATES_AGAINST_TRAINING_FAILURES_WITHIN_THE_SEARCH_BUDGET",
		"search_holdout_accuracy":            "VALIDATE_THE_SELECTED_BODY_AGAINST_A_SEPARATE_UNSEEN_TEST_SUITE",
		"search_candidate_observation":       "MEASURE_UNTESTED_CANDIDATES_IN_A_SEPARATE_EXHAUSTIVE_BASELINE",
		"search_candidate_scoring":           "REPAIR_UNSCORED_CANDIDATES_AND_MEASURE_A_SEPARATE_BASELINE",
		"declared_suite_functional_accuracy": "EXPAND_OR_REPAIR_BODY_CANDIDATES_AGAINST_DECLARED_TESTS_AND_VALIDATE_HELD_OUT_BEHAVIOR",
		"body_fill_holdout_accuracy":         "REVIEW_HELD_OUT_MISMATCHES_AND_EXPAND_THE_DECLARED_TYPED_GRAMMAR_WITHOUT_LEAKING_HOLDOUTS_INTO_CANDIDATE_SELECTION",
		"declared_record_case_accuracy":      "COMPARE_RECORD_ALTERNATIVES_AGAINST_DECLARED_TYPED_CASES",
		"declared_record_field_accuracy":     "COMPLETE_UNMATCHED_DECLARED_RECORD_FIELDS_WITHIN_THE_ATTEMPT_BUDGET",
		"declaration_coverage":               "BIND_THE_REQUESTED_ACTIVITY_TO_A_STABLE_SOURCE_ID",
		"generation_coverage":                "REPAIR_OR_REGENERATE_THE_ACTIVITY_PROJECTION",
		"source_ast_coverage":                "LOWER_EVERY_ACCEPTED_SOURCE_AST_UNIT_OR_FAIL_CLOSED",
		"route_semantic_equivalence":         "REPAIR_THE_SELECTED_ROUTE_OR_ITS_SEMANTIC_WITNESS",
		"typecheck_coverage":                 "REPAIR_GENERATED_GO_TYPE_ERRORS",
		"internal_replay_coverage":           "REPLAY_THE_SELECTED_EMISSION_AND_COMPARE_DIGESTS",
		"route_choice_protocol":              "SELECT_ONLY_FROM_THE_COMPILER_DECLARED_CANDIDATE_SET",
		"provenance_integrity":               "EMBED_AND_BIND_THE_EXACT_COMPILER_SOURCE_REVISION",
		"boundary_coverage":                  "KEEP_CODEGEN_NON_EXECUTING_NON_AUTHORIZING_AND_ZERO_WRITE",
		"execution_boundary":                 "EXECUTE_GENERATED_CODE_IN_A_SEPARATE_BOUNDED_RUNNER",
		"permission_boundary":                "RECORD_THE_HOST_PERMISSION_PROFILE_WITHOUT_GRANTING_AUTHORITY",
		"external_network_boundary":          "RECORD_AND_AUDIT_THE_CONFIGURED_PROVIDER_NETWORK_SCOPE",
		"laya_decision_observation":          "RUN_AN_ELIGIBLE_CASE_WITH_A_PINNED_LAYA_REVISION",
		"use_case_coverage":                  "BIND_INDEPENDENTLY_SOURCED_REAL_WORKFLOW_FIXTURES",
		"reverse_observation_coverage":       "MAP_GENERATED_RUNTIME_OBSERVATIONS_BACK_TO_SOURCE_IDS",
		"full_domain_semantics":              "EXECUTE_A_DOMAIN_PARTITION_OR_PROOF_FOR_THE_DECLARED_INPUT_TYPE",
		"route_quality":                      "ADD_AN_INDEPENDENT_ROUTE_CLARITY_OR_UTILITY_ORACLE",
		"resource_observation":               "CAPTURE_WALL_CPU_AND_PEAK_RSS_FOR_THE_COMPILER_PROCESS",
		"resource_baseline_comparison":       "BIND_A_COMPATIBLE_RESOURCE_BASELINE",
		"semantic_profile_delta":             "BIND_A_COMPATIBLE_BASELINE_AND_REPORT_PER_DIMENSION_DELTAS",
	}
	return operations[id]
}

func compilerSourceSHA() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return "UNBOUND_LOCAL_SOURCE"
	}
	settings := make(map[string]string, len(info.Settings))
	for _, setting := range info.Settings {
		settings[setting.Key] = setting.Value
	}
	revision := settings["vcs.revision"]
	if settings["vcs.modified"] != "false" || !validCommitSHA(revision) {
		return "UNBOUND_LOCAL_SOURCE"
	}
	return revision
}

func validCommitSHA(value string) bool {
	if len(value) != 40 || strings.ToLower(value) != value {
		return false
	}
	for _, char := range value {
		if !((char >= '0' && char <= '9') || (char >= 'a' && char <= 'f')) {
			return false
		}
	}
	return true
}

func validDigest(value string) bool {
	if !strings.HasPrefix(value, "sha256:") || len(value) != len("sha256:")+64 {
		return false
	}
	for _, char := range strings.TrimPrefix(value, "sha256:") {
		if !((char >= '0' && char <= '9') || (char >= 'a' && char <= 'f')) {
			return false
		}
	}
	return true
}

func boolCount(value bool) int {
	if value {
		return 1
	}
	return 0
}

func containsString(values []string, target string) bool {
	return slices.Contains(values, target)
}
