package main

import (
	"encoding/json"
	"fmt"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func runProof(root, outputDir string) (Evidence, error) {
	loaded, err := loadManifests(root)
	if err != nil {
		return Evidence{}, err
	}
	baseline, diagnostic := observeBaseline(root)
	if diagnostic != nil {
		return Evidence{}, diagnosticError(diagnostic)
	}
	baseOutputs, _, err := renderOutputs(root, outputDir, loaded)
	if err != nil {
		return Evidence{}, err
	}
	baseIDs := make([]string, 0, len(loaded))
	for _, item := range loaded {
		baseIDs = append(baseIDs, item.Manifest.StableID)
	}
	sort.Strings(baseIDs)
	evidence := Evidence{
		Schema: evidenceSchema, Decision: "PASS", Reason: "CONFLICT_FREE_REGISTRY_PROJECTION_PROVEN",
		BoundedSlice: baseIDs, BaselineTouchpoints: baseline.Observed, BaselineObservation: baseline.Touchpoints,
		Metrics: integrationMetrics(len(loaded), baseline.Observed), MetricDeltas: metricDeltas(len(loaded), baseline.Observed),
		MutationAuthority: "UNKNOWN",
	}
	evidence.ProjectionReplay = projectionReplay(root, outputDir, loaded, baseOutputs)
	evidence.ManifestOrderInvariant = manifestOrderInvariant(root, outputDir, loaded, baseOutputs)
	evidence.SemanticCausality = semanticCausality(root, outputDir, loaded, baseOutputs)
	evidence.CommentInvariant = commentInvariant(root, outputDir, loaded, baseOutputs)
	evidence.NewConceptFixture = newConceptFixture(root, outputDir, loaded, baseOutputs)
	evidence.FailureContracts = failureContracts(root, loaded, baseOutputs)
	evidence.Strategies = strategyResults(root, outputDir, loaded, evidence)
	evidence.Claims = buildClaims(evidence)
	evidence.RepositoryNetState = repositoryNetState(root)
	evidence.GeneratedOutputs = observedOutputs(outputDir)
	if !allProofsPass(evidence) {
		evidence.Decision = "FAIL_CLOSED"
		evidence.Reason = "CONFLICT_FREE_REGISTRY_PROJECTION_PROOF_INCOMPLETE"
	}
	return evidence, nil
}

func projectionReplay(root, outputDir string, loaded []LoadedManifest, base map[string][]byte) ScenarioResult {
	replay, _, err := renderOutputs(root, outputDir, loaded)
	if err != nil {
		return failedScenario("projection-twice-byte-equality", "projection replay failed", err.Error())
	}
	if !sameOutputs(base, replay) {
		return failedScenario("projection-twice-byte-equality", "PASS", "byte-for-byte replay diverged")
	}
	return passedScenario("projection-twice-byte-equality", "two projections are byte-for-byte identical")
}

func manifestOrderInvariant(root, outputDir string, loaded []LoadedManifest, base map[string][]byte) ScenarioResult {
	reordered := append([]LoadedManifest(nil), loaded...)
	for left, right := 0, len(reordered)-1; left < right; left, right = left+1, right-1 {
		reordered[left], reordered[right] = reordered[right], reordered[left]
	}
	projection, _, err := renderOutputs(root, outputDir, reordered)
	if err != nil {
		return failedScenario("manifest-order-invariance", "PASS", err.Error())
	}
	if !sameOutputs(base, projection) {
		return failedScenario("manifest-order-invariance", "PASS", "manifest order changed generated bytes")
	}
	return passedScenario("manifest-order-invariance", "reordering local manifests preserves every output byte")
}

func semanticCausality(root, outputDir string, loaded []LoadedManifest, base map[string][]byte) ScenarioResult {
	mutated := cloneLoaded(loaded)
	mutated[0].Manifest.Concept.PositiveEffect += " [semantic mutation]"
	mutated[0].RawDigest = digestBytes([]byte(mutated[0].RawDigest + ":semantic"))
	projection, _, err := renderOutputs(root, outputDir, mutated)
	if err != nil {
		return failedScenario("semantic-manifest-causality", "PASS", err.Error())
	}
	changed := changedOutputNames(base, projection)
	want := []string{"README.md", "catalog.json", "denominator.json", "digest.json", "manifest-digests.json", "projection.json"}
	if !sameStringSet(changed, want) {
		return failedScenario("semantic-manifest-causality", "PASS", fmt.Sprintf("changed outputs=%v, want=%v", changed, want))
	}
	return passedScenario("semantic-manifest-causality", "semantic input changed catalog, denominator, documentation, and digest only")
}

func commentInvariant(root, outputDir string, loaded []LoadedManifest, base map[string][]byte) ScenarioResult {
	mutated := cloneLoaded(loaded)
	mutated[0].Manifest.Comments = append(mutated[0].Manifest.Comments, "presentation-only comment")
	mutated[0].RawDigest = digestBytes([]byte(mutated[0].RawDigest + ":comment"))
	projection, _, err := renderOutputs(root, outputDir, mutated)
	if err != nil {
		return failedScenario("comment-only-invariance", "PASS", err.Error())
	}
	changed := changedOutputNames(base, projection)
	want := []string{"digest.json", "manifest-digests.json"}
	if !sameStringSet(changed, want) {
		return failedScenario("comment-only-invariance", "PASS", fmt.Sprintf("changed outputs=%v, want=%v", changed, want))
	}
	return passedScenario("comment-only-invariance", "raw manifest digest changed while semantic projection bytes remained equal")
}

func newConceptFixture(root, outputDir string, loaded []LoadedManifest, base map[string][]byte) ScenarioResult {
	fixturePath := filepath.Join(root, "scripts/conflict-free-registry-projection/testdata/new-concept.manifest.json")
	fixture, err := loadManifest(root, fixturePath)
	if err != nil {
		return failedScenario("new-local-concept-fixture", "PASS", err.Error())
	}
	withFixture := append(cloneLoaded(loaded), fixture)
	projection, _, err := renderOutputs(root, outputDir, withFixture)
	if err != nil {
		return failedScenario("new-local-concept-fixture", "PASS", err.Error())
	}
	changed := changedOutputNames(base, projection)
	want := []string{"README.md", "catalog.json", "denominator.json", "digest.json", "manifest-digests.json", "projection.json"}
	if !sameStringSet(changed, want) {
		return failedScenario("new-local-concept-fixture", "PASS", fmt.Sprintf("changed outputs=%v, want=%v", changed, want))
	}
	return passedScenario("new-local-concept-fixture", "one local fixture changes only deterministic generated projection outputs")
}

func failureContracts(root string, loaded []LoadedManifest, base map[string][]byte) []ScenarioResult {
	duplicate := cloneLoaded(loaded)
	duplicate = append(duplicate, cloneLoaded(loaded[:1])...)
	missing := cloneLoaded(loaded[1:])
	required := make([]string, 0, len(loaded))
	for _, item := range loaded {
		required = append(required, item.Manifest.StableID)
	}
	stale := cloneOutputs(base)
	projection := append([]byte(nil), stale["projection.json"]...)
	projection[0] = projection[0] ^ 1
	stale["projection.json"] = projection
	return []ScenarioResult{
		failureScenario("duplicate-stable-id", validateManifests(duplicate, nil), "DUPLICATE_STABLE_ID"),
		failureScenario("missing-manifest", validateManifests(missing, required), "MISSING_MANIFEST"),
		failureScenario("stale-generated-projection", checkRendered(base, stale), "STALE_GENERATED_PROJECTION"),
	}
}

func failureScenario(id string, diagnostic *Diagnostic, expectedReason string) ScenarioResult {
	if diagnostic == nil {
		return failedScenario(id, "FAIL_CLOSED", "invalid input was accepted")
	}
	if diagnostic.Decision != "FAIL_CLOSED" || diagnostic.Stage == "" || diagnostic.Step == "" || diagnostic.Reason != expectedReason {
		return failedScenario(id, "FAIL_CLOSED", fmt.Sprintf("diagnostic=%+v", *diagnostic))
	}
	return ScenarioResult{ID: id, Decision: "PASS", Expected: "FAIL_CLOSED", Diagnostic: diagnostic, Detail: "stage, step, and reason were preserved"}
}

func strategyResults(root, outputDir string, loaded []LoadedManifest, evidence Evidence) []StrategyResult {
	results := make([]StrategyResult, 0, 3)
	for _, name := range []string{"FOUNDATION", "COHERENCE", "REGRESSION"} {
		selected := true
		for _, item := range loaded {
			if !contains(item.Manifest.VerificationStrategies, name) {
				selected = false
			}
		}
		result := StrategyResult{Name: name, Selected: selected, Decision: "PASS", Reason: "STRATEGY_SELECTED_AND_DISCHARGED"}
		if name == "FOUNDATION" {
			result.Scenarios = []string{"local-manifest-identity", "resource-availability", "baseline-touchpoints"}
			if !selected {
				result.Decision, result.Reason = "FAIL_CLOSED", "FOUNDATION_STRATEGY_NOT_SELECTED"
			}
			if selected {
				if _, err := buildProjection(root, loaded); err != nil {
					result.Decision, result.Reason = "FAIL_CLOSED", "FOUNDATION_PROJECTION_UNAVAILABLE"
				}
			}
		}
		if name == "COHERENCE" {
			result.Scenarios = []string{"projection-twice-byte-equality", "manifest-order-invariance"}
			if !selected || evidence.ProjectionReplay.Decision != "PASS" || evidence.ManifestOrderInvariant.Decision != "PASS" {
				result.Decision, result.Reason = "FAIL_CLOSED", "COHERENCE_REPLAY_NOT_DISCHARGED"
			}
		}
		if name == "REGRESSION" {
			result.Scenarios = []string{"duplicate-stable-id", "missing-manifest", "stale-generated-projection", "semantic-manifest-causality", "comment-only-invariance"}
			if !selected || evidence.SemanticCausality.Decision != "PASS" || evidence.CommentInvariant.Decision != "PASS" {
				result.Decision, result.Reason = "FAIL_CLOSED", "REGRESSION_INVARIANTS_NOT_DISCHARGED"
			}
			for _, scenario := range evidence.FailureContracts {
				if scenario.Decision != "PASS" {
					result.Decision, result.Reason = "FAIL_CLOSED", "REGRESSION_FAILURE_CONTRACT_NOT_DISCHARGED"
				}
			}
		}
		results = append(results, result)
	}
	return results
}

func buildClaims(evidence Evidence) []Claim {
	claims := []Claim{
		claim("projection-replay", "the same local manifests produce byte-identical projection outputs", sectionDigest(evidence.ProjectionReplay)),
		claim("manifest-order", "manifest discovery order is not semantic", sectionDigest(evidence.ManifestOrderInvariant)),
		claim("semantic-causality", "semantic manifest fields change only semantic projection surfaces and digests", sectionDigest(evidence.SemanticCausality)),
		claim("comment-invariance", "presentation-only comments do not change semantic projection bytes", sectionDigest(evidence.CommentInvariant)),
		claim("new-concept-locality", "a new concept fixture needs no existing concept-file edit", sectionDigest(evidence.NewConceptFixture)),
	}
	for _, scenario := range evidence.FailureContracts {
		claims = append(claims, claim(scenario.ID, scenario.ID+" fails closed with stage, step, and reason", sectionDigest(scenario)))
	}
	claims = append(claims, Claim{ID: "rejected-authority-proposition", Proposition: "a stale generated projection may remain authoritative", TargetDigest: sectionDigest("stale-generated-projection-authority"), Transitions: []ClaimTransition{
		{State: "OPEN", TargetDigest: sectionDigest("stale-generated-projection-authority"), Stage: "REGRESSION", Step: "CLAIM_OPEN", Reason: "proposition_under_review"},
		{State: "REFUTED", TargetDigest: sectionDigest("stale-generated-projection-authority"), Stage: "REGRESSION", Step: "GENERATED_OUTPUT", Reason: "STALE_GENERATED_PROJECTION"},
	}})
	return claims
}

func claim(id, proposition, targetDigest string) Claim {
	return Claim{ID: id, Proposition: proposition, TargetDigest: targetDigest, Transitions: []ClaimTransition{
		{State: "OPEN", TargetDigest: targetDigest, Stage: "FOUNDATION", Step: "CLAIM_OPEN", Reason: "proposition_under_review"},
		{State: "DISCHARGED", TargetDigest: targetDigest, Stage: "COHERENCE", Step: "CLAIM_EVIDENCE", Reason: "evidence_matches_target_digest"},
	}}
}

func allProofsPass(evidence Evidence) bool {
	for _, scenario := range []ScenarioResult{evidence.ProjectionReplay, evidence.ManifestOrderInvariant, evidence.SemanticCausality, evidence.CommentInvariant, evidence.NewConceptFixture} {
		if scenario.Decision != "PASS" {
			return false
		}
	}
	for _, scenario := range evidence.FailureContracts {
		if scenario.Decision != "PASS" {
			return false
		}
	}
	for _, strategy := range evidence.Strategies {
		if !strategy.Selected || strategy.Decision != "PASS" {
			return false
		}
	}
	return validateClaims(evidence.Claims) == nil && evidence.RepositoryNetState.NetStateEqual
}

func validateClaims(claims []Claim) error {
	propositions := make(map[string]struct{}, len(claims))
	targets := make(map[string]struct{}, len(claims))
	for _, item := range claims {
		if item.ID == "" || item.Proposition == "" || item.TargetDigest == "" || len(item.Transitions) < 2 {
			return fmt.Errorf("invalid claim shape")
		}
		if _, ok := propositions[item.Proposition]; ok {
			return fmt.Errorf("duplicate claim proposition")
		}
		if _, ok := targets[item.TargetDigest]; ok {
			return fmt.Errorf("duplicate claim target digest")
		}
		propositions[item.Proposition] = struct{}{}
		targets[item.TargetDigest] = struct{}{}
		if item.Transitions[0].State != "OPEN" {
			return fmt.Errorf("claim does not begin OPEN")
		}
		last := item.Transitions[len(item.Transitions)-1].State
		if last != "DISCHARGED" && last != "REFUTED" {
			return fmt.Errorf("claim does not terminate in a known state")
		}
		for _, transition := range item.Transitions {
			if transition.TargetDigest != item.TargetDigest || (transition.State != "OPEN" && transition.State != "DISCHARGED" && transition.State != "REFUTED") {
				return fmt.Errorf("claim transition is not target-bound")
			}
		}
	}
	return nil
}

func cloneLoaded(input []LoadedManifest) []LoadedManifest {
	output := make([]LoadedManifest, 0, len(input))
	for _, item := range input {
		data, _ := json.Marshal(item.Manifest)
		manifest := Manifest{}
		_ = json.Unmarshal(data, &manifest)
		output = append(output, LoadedManifest{Manifest: manifest, SourcePath: item.SourcePath, RawDigest: item.RawDigest})
	}
	return output
}

func cloneOutputs(input map[string][]byte) map[string][]byte {
	output := make(map[string][]byte, len(input))
	for key, value := range input {
		output[key] = append([]byte(nil), value...)
	}
	return output
}

func sameOutputs(left, right map[string][]byte) bool {
	if len(left) != len(right) {
		return false
	}
	for key, value := range left {
		if string(value) != string(right[key]) {
			return false
		}
	}
	return true
}

func changedOutputNames(left, right map[string][]byte) []string {
	keys := make(map[string]struct{}, len(left)+len(right))
	for key := range left {
		keys[key] = struct{}{}
	}
	for key := range right {
		keys[key] = struct{}{}
	}
	changed := make([]string, 0, len(keys))
	for key := range keys {
		if string(left[key]) != string(right[key]) {
			changed = append(changed, key)
		}
	}
	sort.Strings(changed)
	return changed
}

func sameStringSet(left, right []string) bool {
	left = sortedStringsCopy(left)
	right = sortedStringsCopy(right)
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func contains(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

func passedScenario(id, detail string) ScenarioResult {
	return ScenarioResult{ID: id, Decision: "PASS", Expected: "PASS", Detail: detail}
}

func failedScenario(id, expected, detail string) ScenarioResult {
	return ScenarioResult{ID: id, Decision: "FAIL_CLOSED", Expected: expected, Detail: detail}
}

func repositoryNetState(root string) RepositoryObservation {
	before := gitStatus(root)
	after := gitStatus(root)
	return RepositoryObservation{BeforePaths: before, AfterPaths: after, NetStateEqual: sameStringSet(before, after), MutationObserved: false, ObservedAuthority: "UNKNOWN"}
}

func gitStatus(root string) []string {
	command := exec.Command("git", "-C", root, "status", "--porcelain", "--untracked-files=all")
	data, err := command.Output()
	if err != nil {
		return []string{"UNKNOWN"}
	}
	lines := strings.Split(strings.TrimSpace(string(data)), "\n")
	if len(lines) == 1 && lines[0] == "" {
		return nil
	}
	return lines
}

func observedOutputs(outputDir string) []OutputMetadata {
	outputs, err := readGenerated(outputDir)
	if err != nil {
		return []OutputMetadata{{Path: filepath.ToSlash(filepath.Join(defaultOutput, "UNKNOWN")), Digest: "UNKNOWN", Bytes: 0}}
	}
	return outputMetadata("", outputDir, outputs)
}
