package query

import (
	"encoding/json"
	"errors"
	"fmt"
	"sort"
)

const (
	ResolutionSchema   = "gooo-query/resolution/v1"
	ResolutionMaxDepth = 2
	ResolutionResolved = "resolved"
)

var ErrInvalidResolution = errors.New("invalid generated resolution")

// ResolutionRequest asks for one bounded semantic view. Business is an Entity
// ID; the view follows Activity used Business to an Entity generated by that
// Activity. The generated entity is a semantic projection endpoint, not proof
// that a Go file or symbol exists.
type ResolutionRequest struct {
	Schema   string `json:"schema"`
	Business ID     `json:"business"`
	Layer    Layer  `json:"layer"`
	MaxDepth int    `json:"max_depth"`
	Limit    int    `json:"limit"`
}

// ResolutionRow is a detached, non-authoritative semantic resolution result.
type ResolutionRow struct {
	Business        ID     `json:"business"`
	Activity        ID     `json:"activity"`
	GeneratedEntity ID     `json:"generated_entity"`
	Depth           int    `json:"depth"`
	Status          string `json:"status"`
	SourceLayer     string `json:"source_layer"`
}

// ResolutionResponse is canonical-hashable and keeps candidate rows separate.
// A deferred response is explicit when no complete two-hop semantic path is
// available; it never fabricates a generated-code or provenance receipt.
type ResolutionResponse struct {
	Schema        string            `json:"schema"`
	Status        string            `json:"status"`
	Request       ResolutionRequest `json:"request"`
	RequestHash   string            `json:"request_hash,omitempty"`
	Deterministic []ResolutionRow   `json:"deterministic,omitempty"`
	Candidates    []ResolutionRow   `json:"candidates,omitempty"`
	Metadata      EnvelopeMetadata  `json:"metadata"`
	Error         *EnvelopeError    `json:"error,omitempty"`
	Hash          string            `json:"canonical_hash,omitempty"`
}

func (request ResolutionRequest) Normalize() (ResolutionRequest, FactSelection, error) {
	if request.Schema != ResolutionSchema {
		return ResolutionRequest{}, 0, envelopeError(
			ErrInvalidResolution, "invalid_resolution_schema", "schema must be gooo-query/resolution/v1",
		)
	}
	business, err := ParseID(request.Business.String())
	if err != nil {
		return ResolutionRequest{}, 0, envelopeError(ErrInvalidResolution, "invalid_business", err.Error())
	}
	if request.MaxDepth != ResolutionMaxDepth {
		return ResolutionRequest{}, 0, envelopeError(
			ErrInvalidResolution, "invalid_resolution_depth", fmt.Sprintf("must be exactly %d", ResolutionMaxDepth),
		)
	}
	if request.Limit < 1 || request.Limit > MaxEnvelopeLimit {
		return ResolutionRequest{}, 0, envelopeError(
			ErrInvalidResolution, "invalid_resolution_limit", fmt.Sprintf("must be 1..%d", MaxEnvelopeLimit),
		)
	}
	layer, selection, err := normalizeLayer(request.Layer)
	if err != nil {
		return ResolutionRequest{}, 0, err
	}
	request.Business = ID(business)
	request.Layer = layer
	return request, selection, nil
}

func (request ResolutionRequest) CanonicalJSON() ([]byte, error) {
	normalized, _, err := request.Normalize()
	if err != nil {
		return nil, err
	}
	return json.Marshal(normalized)
}

func (request ResolutionRequest) CanonicalDigest() (string, error) {
	canonical, err := request.CanonicalJSON()
	if err != nil {
		return "", err
	}
	return digestBytes(canonical), nil
}

// ResolveGeneratedCode evaluates the fixed two-hop semantic resolution view.
// It reads detached graph snapshots only and never inserts a derived row.
func (graph Graph) ResolveGeneratedCode(request ResolutionRequest) (ResolutionResponse, error) {
	normalized, selection, err := request.Normalize()
	if err != nil {
		return graph.rejectedResolution(request, err)
	}
	requestHash, err := normalized.CanonicalDigest()
	if err != nil {
		return graph.rejectedResolution(normalized, err)
	}
	root, ok := graph.Node(normalized.Business)
	if !ok {
		return graph.rejectedResolution(normalized, fmt.Errorf("%w: %s", ErrUnknownEndpoint, normalized.Business))
	}
	if root.Kind != EntityNodeKind {
		return graph.rejectedResolution(normalized, envelopeError(
			ErrInvalidResolution, "invalid_business_kind", "business endpoint must be an Entity",
		))
	}
	deterministic, candidates := graph.resolutionRows(
		normalized.Business, selection, normalized.Limit,
	)
	status := StatusDeferred
	if len(deterministic)+len(candidates) > 0 {
		status = ResolutionResolved
	}
	metadata := resolutionMetadata(graph.Metadata(), status)
	response := ResolutionResponse{
		Schema: ResolutionSchema, Status: status, Request: normalized,
		RequestHash: requestHash, Deterministic: deterministic,
		Candidates: candidates, Metadata: metadata,
	}
	if err := response.seal(); err != nil {
		return ResolutionResponse{}, err
	}
	return response, nil
}

func (graph Graph) resolutionRows(root ID, selection FactSelection, limit int) ([]ResolutionRow, []ResolutionRow) {
	facts := graph.AllFacts()
	deterministic := graph.resolutionLayer(root, facts, SelectDeterministic, limit, nil)
	if selection == SelectDeterministic || len(deterministic) >= limit {
		return deterministic, nil
	}
	remaining := limit - len(deterministic)
	if selection == SelectCandidate {
		return nil, graph.resolutionLayer(root, facts, SelectCandidate, remaining, nil)
	}
	blocked := resolutionKeys(deterministic)
	candidates := graph.resolutionLayer(root, facts, SelectAll, remaining, blocked)
	return deterministic, candidates
}

func (graph Graph) resolutionLayer(
	root ID, facts []Fact, selection FactSelection, limit int, blocked map[resolutionKey]struct{},
) []ResolutionRow {
	used := make([]Fact, 0)
	generated := make(map[ID][]Fact)
	for _, fact := range facts {
		if !selection.includes(fact.Status) {
			continue
		}
		switch fact.Predicate {
		case Used:
			if fact.Object == root {
				used = append(used, fact)
			}
		case WasGeneratedBy:
			generated[fact.Object] = append(generated[fact.Object], fact)
		}
	}
	sortFacts(used)
	for _, facts := range generated {
		sortFacts(facts)
	}
	rows := make([]ResolutionRow, 0, limit)
	for _, usedFact := range used {
		activity, ok := graph.Node(usedFact.Subject)
		if !ok || activity.Kind != ActivityNodeKind {
			continue
		}
		for _, generatedFact := range generated[usedFact.Subject] {
			output, ok := graph.Node(generatedFact.Subject)
			if !ok || output.Kind != EntityNodeKind {
				continue
			}
			candidate := usedFact.Status == FactCandidate || generatedFact.Status == FactCandidate
			if selection == SelectDeterministic && candidate {
				continue
			}
			if selection == SelectCandidate && !candidate {
				continue
			}
			row := newResolutionRow(root, usedFact.Subject, generatedFact.Subject, candidate)
			key := resolutionKey{row.Business, row.Activity, row.GeneratedEntity}
			if _, exists := blocked[key]; exists {
				continue
			}
			rows = append(rows, row)
			if len(rows) == limit {
				// used and generated are already in the same stable order as
				// sortResolutionRows. Sort only the bounded prefix before
				// returning so the limit also bounds Cartesian expansion.
				sortResolutionRows(rows)
				return append([]ResolutionRow(nil), rows...)
			}
		}
	}
	sortResolutionRows(rows)
	if len(rows) > limit {
		rows = rows[:limit]
	}
	return append([]ResolutionRow(nil), rows...)
}

type resolutionKey struct {
	business, activity, generated ID
}

func newResolutionRow(business, activity, generated ID, candidate bool) ResolutionRow {
	source := FactDeterministic.String()
	if candidate {
		source = FactCandidate.String()
	}
	return ResolutionRow{
		Business: business, Activity: activity, GeneratedEntity: generated,
		Depth: ResolutionMaxDepth, Status: DerivedFactStatus, SourceLayer: source,
	}
}

func resolutionKeys(rows []ResolutionRow) map[resolutionKey]struct{} {
	keys := make(map[resolutionKey]struct{}, len(rows))
	for _, row := range rows {
		keys[resolutionKey{row.Business, row.Activity, row.GeneratedEntity}] = struct{}{}
	}
	return keys
}

func sortResolutionRows(rows []ResolutionRow) {
	sort.Slice(rows, func(i, j int) bool {
		left, right := rows[i], rows[j]
		if left.Business != right.Business {
			return left.Business < right.Business
		}
		if left.Activity != right.Activity {
			return left.Activity < right.Activity
		}
		if left.GeneratedEntity != right.GeneratedEntity {
			return left.GeneratedEntity < right.GeneratedEntity
		}
		return left.SourceLayer < right.SourceLayer
	})
}

func resolutionMetadata(metadata ProjectionMetadata, status string) EnvelopeMetadata {
	result := envelopeMetadata(metadata)
	result.DerivedStatus = DerivedStatusNonAuthoritative
	result.AuthorityLabels = append(result.AuthorityLabels, AuthorityLabel{
		View: "resolution_view", Authority: "derived", Status: status,
	})
	return result
}
