package query

import (
	"errors"
)

const (
	ResolutionSchema   = "gooo-query/resolution/v1"
	ResolutionMaxDepth = 2
	ResolutionResolved = "resolved"
)

var ErrInvalidResolution = errors.New("invalid generated resolution")

// ResolutionRequest asks for one bounded semantic view. Business is an Entity
// ID; the view follows Activity used Business to an Entity generated by that
// Activity. The generated entity is a semantic projection endpoint, not proof
// that a Go file or symbol exists.
type ResolutionRequest struct {
	Schema   string `json:"schema"`
	Business ID     `json:"business"`
	Layer    Layer  `json:"layer"`
	MaxDepth int    `json:"max_depth"`
	Limit    int    `json:"limit"`
}

// ResolutionRow is a detached, non-authoritative semantic resolution result.
type ResolutionRow struct {
	Business        ID     `json:"business"`
	Activity        ID     `json:"activity"`
	GeneratedEntity ID     `json:"generated_entity"`
	Depth           int    `json:"depth"`
	Status          string `json:"status"`
	SourceLayer     string `json:"source_layer"`
}

// ResolutionResponse is canonical-hashable and keeps candidate rows separate.
// A deferred response is explicit when no complete two-hop semantic path is
// available; it never fabricates a generated-code or provenance receipt.
type ResolutionResponse struct {
	Schema        string            `json:"schema"`
	Status        string            `json:"status"`
	Request       ResolutionRequest `json:"request"`
	RequestHash   string            `json:"request_hash,omitempty"`
	Deterministic []ResolutionRow   `json:"deterministic,omitempty"`
	Candidates    []ResolutionRow   `json:"candidates,omitempty"`
	Metadata      EnvelopeMetadata  `json:"metadata"`
	Error         *EnvelopeError    `json:"error,omitempty"`
	Hash          string            `json:"canonical_hash,omitempty"`
}
