package policycompilation

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
)

const NextPolicyExecutionSchema = "gooo/meta-policy-next-execution/v1"
const NextPolicyExecutionRequestSchema = "gooo/meta-policy-next-execution-request/v1"

// NextPolicyExecutionRequest pins a source handoff and caller-owned expectations.
// A predecessor digest links bytes; it does not authenticate a historical run.
type NextPolicyExecutionRequest struct {
	Schema string `json:"schema"`
	ExpectedSourceDigest string `json:"expected_source_digest"`
	ExpectedSemanticDigest string `json:"expected_semantic_digest"`
	PredecessorDigest string `json:"predecessor_digest"`
	Cases []Case `json:"cases"`
}

type NextPolicyExecutionReport struct {
	Schema string `json:"schema"`
	Decision string `json:"decision"`
	Reason string `json:"reason"`
	SourceDigest string `json:"source_digest"`
	SemanticDigest string `json:"semantic_digest"`
	RequestDigest string `json:"request_digest"`
	PredecessorDigest string `json:"predecessor_digest"`
	PredecessorBinding string `json:"predecessor_binding"`
	GeneratedJudgeDigest string `json:"generated_judge_digest"`
	GeneratedBatchInvocations int `json:"generated_batch_invocations"`
	RequestedCases int `json:"requested_cases"`
	ObservedCases int `json:"observed_cases"`
	ExpectationComparisons int `json:"expectation_comparisons"`
	ExpectationMismatches int `json:"expectation_mismatches"`
	ResultBindingMismatches int `json:"result_binding_mismatches"`
	DeclaredCases []Case `json:"declared_cases"`
	Results []DecisionResult `json:"results"`
	ExecutionError string `json:"execution_error,omitempty"`
	Pending *PolicyRevisionPending `json:"pending,omitempty"`
	Admission PolicyRevisionPending `json:"admission"`
	Improvement string `json:"improvement"`
	MutationAuthority int `json:"mutation_authority"`
	PromotionAuthority int `json:"promotion_authority"`
}

// ObserveNextPolicyExecution uses a previous candidate as the source of a fresh
// invocation. Only newly compiled Gooo produces executable Go. The predecessor's
// generated bytes, claimed decisions and historical process claims grant nothing.
func ObserveNextPolicyExecution(ctx context.Context, filename string, source, predecessor, request []byte, pkg, namespace string) NextPolicyExecutionReport {
	report := NextPolicyExecutionReport{
		Schema: NextPolicyExecutionSchema, Decision: "UNKNOWN",
		SourceDigest: DigestBytes(source), RequestDigest: DigestBytes(request),
		PredecessorDigest: DigestBytes(predecessor), Improvement: "UNKNOWN",
		PredecessorBinding: "CALLER_PINNED_BYTES_NOT_HISTORICAL_ATTESTATION",
		Admission: PolicyRevisionPending{
			State: "UNKNOWN", Stage: "ADMISSION", Step: "NEXT_POLICY_EXECUTION",
			Reason: "NEXT_EXECUTION_IS_NOT_REVISION_ADMISSION", UnknownClass: "DIRECT_MISSING",
			NextOperation: "BIND_INDEPENDENT_REVISION_ADMISSION", BlockedBy: []string{},
		},
	}
	var input NextPolicyExecutionRequest
	if !bytes.HasPrefix(bytes.TrimSpace(request), []byte("{")) || decodeStrictJSON(request, &input) != nil {
		return nextExecutionUnknown(report, "INPUT", "DECODE_NEXT_REQUEST", "NEXT_REQUEST_INVALID", "AMBIGUOUS")
	}
	report.RequestedCases, report.DeclaredCases = len(input.Cases), append([]Case(nil), input.Cases...)
	if input.Schema != NextPolicyExecutionRequestSchema || !ValidDigest(input.ExpectedSourceDigest) ||
		!ValidDigest(input.PredecessorDigest) || input.ExpectedSemanticDigest == "" {
		return nextExecutionUnknown(report, "INPUT", "BIND_NEXT_REQUEST", "NEXT_REQUEST_BINDING_MISSING", "DIRECT_MISSING")
	}
	if input.ExpectedSourceDigest != report.SourceDigest || input.PredecessorDigest != report.PredecessorDigest {
		report.Decision, report.Reason = "REFUTED", "NEXT_SOURCE_OR_PREDECESSOR_DIGEST_MISMATCH"
		return report
	}
	if len(input.Cases) == 0 || len(input.Cases) > 128 {
		return nextExecutionUnknown(report, "INPUT", "BOUND_NEXT_CASES", "NEXT_CASE_BATCH_OUTSIDE_1_TO_128", "UNBOUNDED")
	}
	seen := make(map[string]bool, len(input.Cases))
	for _, item := range input.Cases {
		if item.ID == "" || seen[item.ID] || !knownDecision(item.ValidatorExpectation) {
			return nextExecutionUnknown(report, "INPUT", "BIND_NEXT_EXPECTATIONS", "NEXT_CASE_EXPECTATION_INVALID", "AMBIGUOUS")
		}
		seen[item.ID] = true
	}
	var envelope map[string]json.RawMessage
	var operation PolicyRevisionOperationObservation
	if decodeStrictJSON(predecessor, &envelope) != nil || envelope == nil ||
		!bytes.Equal(envelope["schema"], []byte(`"gooo/meta-policy-revision-independent-observation/v1"`)) ||
		json.Unmarshal(envelope["operation"], &operation) != nil || operation.Observation == nil {
		return nextExecutionUnknown(report, "HANDOFF", "READ_PREDECESSOR", "NEXT_PREDECESSOR_SHAPE_UNAVAILABLE", "AMBIGUOUS")
	}
	if operation.Observation.CandidateSource != string(source) {
		report.Decision, report.Reason = "REFUTED", "NEXT_SOURCE_DIFFERS_FROM_PREDECESSOR_CANDIDATE"
		return report
	}
	policy, err := CompileForIdentity(filename, source, pkg, namespace)
	if err != nil {
		report.ExecutionError = err.Error()
		return nextExecutionUnknown(report, "COMPILE", "COMPILE_NEXT_GOOO", "NEXT_SOURCE_NOT_COMPILED", "AMBIGUOUS")
	}
	report.SemanticDigest = policy.SemanticDigest
	if policy.SemanticDigest != input.ExpectedSemanticDigest {
		report.Decision, report.Reason = "REFUTED", "NEXT_SEMANTIC_DIGEST_MISMATCH"
		return report
	}
	generated := GenerateJudge(policy)
	report.GeneratedJudgeDigest, report.GeneratedBatchInvocations = DigestBytes(generated), 1
	report.Results, err = ExecuteGeneratedBatch(ctx, generated, input.Cases)
	report.ObservedCases = len(report.Results)
	if err != nil {
		report.ExecutionError = err.Error()
	}
	for index, result := range report.Results {
		report.ExpectationComparisons++
		if result.Decision != input.Cases[index].ValidatorExpectation {
			report.ExpectationMismatches++
		}
		if result.PolicyDigest != policy.SourceDigest || result.SemanticDigest != policy.SemanticDigest ||
			result.CaseID != input.Cases[index].ID || result.Denominator != policy.Denominator {
			report.ResultBindingMismatches++
		}
	}
	if report.ExpectationMismatches != 0 || report.ResultBindingMismatches != 0 {
		report.Decision, report.Reason = "REFUTED", "NEXT_EXECUTION_CONTRADICTS_DECLARED_EXPECTATION_OR_BINDING"
		return report
	}
	if err != nil || report.ObservedCases != report.RequestedCases {
		return nextExecutionUnknown(report, "EXECUTION", "RUN_NEXT_POLICY", "NEXT_EXECUTION_INCOMPLETE", "DIRECT_MISSING")
	}
	report.Decision, report.Reason = "NEXT_EXECUTION_OBSERVED", "PINNED_CANDIDATE_USED_WITH_UNCHANGED_EXPECTATIONS"
	return report
}

func nextExecutionUnknown(report NextPolicyExecutionReport, stage, step, reason, class string) NextPolicyExecutionReport {
	report.Decision, report.Reason = "UNKNOWN", reason
	report.Pending = &PolicyRevisionPending{
		State: "UNKNOWN", Stage: stage, Step: step, Reason: reason, UnknownClass: class,
		NextOperation: fmt.Sprintf("RESOLVE_%s_AND_REPEAT_NEXT_EXECUTION", step), BlockedBy: []string{},
	}
	return report
}
