package languageconcept

var languageDiagnosticProvenanceConcept = Concept{
	ID: "language-diagnostic-provenance",
	Problem: "a diagnostic can name an error without proving which physical byte, " +
		"logical source, or semantic identity caused it",
	PositiveEffect: "a read-only metaprogram normalizes existing formatter, generator, " +
		"Go, and LSP evidence into replayable provenance and lowers unknowns",
	MetaOperation: "trace-diagnostic-through-semantic-provenance",
	Rarity:        "UNCOMMON_COMBINATION", Stage: "OPERATING", NoveltyClaim: false,
	CodeBindings: []string{
		"internal/formatter",
		"internal/generator",
		"internal/lsp",
		"internal/meta/languagereadiness/languagediagnosticprovenance",
		"internal/meta/languagereadiness/languagediagnosticprovenancebinding",
		"cmd/language-diagnostic-provenance-witness",
		"cmd/language-diagnostic-provenance-readiness-binding",
		"examples/language-diagnostic-provenance",
	},
	MetricBindings: languageDiagnosticProvenanceMetricBindings(),
	UseCases: []UseCase{
		{
			ID:              "trace-generated-diagnostic",
			Trigger:         "a generated Go or formatter diagnostic falls inside one source-map range",
			ExpectedOutcome: "TRACE_4_OF_4_TO_SEMANTIC_ID_AND_LSP_RANGE",
		},
		{
			ID:              "trace-line-directed-diagnostic",
			Trigger:         "Go reports a generated byte whose //line coordinate differs",
			ExpectedOutcome: "PRESERVE_PHYSICAL_AND_LOGICAL_COORDINATES",
		},
		{
			ID:              "reject-ambiguous-or-unknown-provenance",
			Trigger:         "origin, stage, severity, coordinate, or source-map evidence is unknown",
			ExpectedOutcome: "REJECT_8_OF_8_AND_LOWER_RESOLUTION",
		},
	},
}
