package languageconcept

var languageCIPlanUsecaseConcept = concept(
	"language-ci-plan-usecase",
	"a language can accumulate green internal proofs without closing a user-visible development task",
	"a Gooo meta program turns changed files into a deterministic bounded CI plan, explicit unknown coordinates, and a resource scorecard",
	"invoke-ci-plan-meta-program",
	"OPERATING",
	[]string{"internal/metainvocation", "internal/meta/ciplanusecase", "examples/ci-plan", "scripts/ci-plan-usecase", "cmd/gooo"},
	[]string{
		"gooo.metric.ci-plan.cases-satisfied.v1",
		"gooo.metric.ci-plan.pass-decisions.v1",
		"gooo.metric.ci-plan.fail-closed-decisions.v1",
		"gooo.metric.ci-plan.unknown-decisions.v1",
		"gooo.metric.ci-plan.deterministic-replays.v1",
		"gooo.metric.ci-plan.golden-plans.v1",
		"gooo.metric.ci-plan.rule-evidence-refs.v1",
		"gooo.metric.ci-plan.direct-unknown-claims.v1",
		"gooo.metric.ci-plan.dependency-blocked-claims.v1",
		"gooo.metric.ci-plan.refuted-claims.v1",
		"gooo.metric.ci-plan.persistent-claims.v1",
		"gooo.metric.ci-plan.generated-source-replays.v1",
		"gooo.metric.ci-plan.resource-samples.v1",
		"gooo.metric.ci-plan.gooo-files.v1",
		"gooo.metric.ci-plan.go-files.v1",
		"gooo.metric.ci-plan.gooo-lines.v1",
		"gooo.metric.ci-plan.go-lines.v1",
		"gooo.metric.ci-plan.max-wall-ms.v1",
		"gooo.metric.ci-plan.peak-rss-kib.v1",
		"gooo.metric.ci-plan.max-receipt-bytes.v1",
		"gooo.metric.ci-plan.repository-writes.guardrail.v1",
		"gooo.metric.ci-plan.mutation-authority.guardrail.v1",
	},
	UseCase{
		ID:              "changed-files-to-ci-receipt",
		Trigger:         "a user supplies changed repository paths to the PlanCI activity",
		ExpectedOutcome: "4 PASS, 4 FAIL_CLOSED, and 4 causally located UNKNOWN cases replay with zero writes",
	},
)
