package languageconcept

import verifier "github.com/kimjooyoon/meta-ontology-go/internal/meta/languageproofartifactverifier"

var languageProofCarryingArtifactConcept = Concept{
	ID:             "language-proof-carrying-artifact",
	Problem:        "Generated bytes can be mistaken for authority when their justification is not carried and independently checked.",
	PositiveEffect: "A Gooo artifact carries source, operation, and invariant evidence plus a fixed consumer recipe without minting its own authority.",
	MetaOperation:  "grant-read-only-consumption",
	Rarity:         "UNCOMMON_COMBINATION",
	Stage:          "OPERATING",
	NoveltyClaim:   false,
	CodeBindings: []string{
		"internal/meta/languageproofartifact",
		"internal/meta/languageproofartifactverifier",
		"cmd/language-proof-carrying-artifact",
		"cmd/language-proof-carrying-artifact-verifier",
		"examples/language-proof-carrying-artifact",
		"scripts/language-proof-carrying-artifact",
	},
	MetricBindings: verifier.MetricIDs(),
	UseCases: []UseCase{
		{ID: "proof-carrying-consumption", Trigger: "a Gooo operation emits an artifact with three evidence kinds and a canonical recipe", ExpectedOutcome: "PASS_6_OF_6_WITH_READ_ONLY_CONSUMPTION_AUTHORITY"},
		{ID: "bytes-without-authority", Trigger: "a consumer receives generated bytes without source, operation, or recipe inputs", ExpectedOutcome: "FAIL_CLOSED_ARTIFACT_BYTES_NOT_AUTHORITY"},
	},
}
