package main

type failureManifest struct {
	Schema               string            `json:"schema"`
	Version              int               `json:"version"`
	Code                 string            `json:"code"`
	FailureCodes         []string          `json:"failure_codes"`
	Class                string            `json:"class"`
	Severity             string            `json:"severity"`
	Scope                string            `json:"scope"`
	BlockingScope        string            `json:"blocking_scope"`
	Parallelizable       bool              `json:"parallelizable"`
	SourceCommit         string            `json:"source_commit"`
	Repository           string            `json:"repository"`
	BaseRef              string            `json:"base_ref"`
	BaseSHA              string            `json:"base_sha"`
	HeadSHA              string            `json:"head_sha"`
	Event                string            `json:"event"`
	EventRef             string            `json:"event_ref"`
	CheckoutRef          string            `json:"checkout_ref"`
	PRNumber             int64             `json:"pr_number"`
	RunID                int64             `json:"run_id"`
	RunAttempt           int64             `json:"run_attempt"`
	WorkflowSHA          string            `json:"workflow_sha"`
	Job                  failureJob        `json:"job"`
	Activity             string            `json:"activity"`
	Agent                string            `json:"agent"`
	OwnerBranch          string            `json:"owner_branch"`
	OwnerRef             string            `json:"owner_ref"`
	Entity               string            `json:"entity"`
	Provenance           failureProvenance `json:"provenance"`
	EvidenceRefs         []string          `json:"evidence_refs"`
	CatalogPath          string            `json:"catalog_path"`
	CatalogDigest        string            `json:"catalog_digest"`
	CatalogRef           string            `json:"catalog_ref"`
	CatalogVersion       int               `json:"catalog_version"`
	CatalogSHA256        string            `json:"catalog_sha256"`
	Rejections           []string          `json:"rejections"`
	MissingReasons       missingReasons    `json:"missing_reasons"`
	Artifacts            []artifactInput   `json:"artifacts"`
	ProofArtifactRef     *artifactInput    `json:"proof_artifact_ref,omitempty"`
	ArtifactURLs         []string          `json:"artifact_urls"`
	ArtifactRefs         []artifactInput   `json:"artifact_refs"`
	ArtifactStatus       string            `json:"artifact_status"`
	ArtifactReason       string            `json:"artifact_reason"`
	TerminalFailures     []failureJob      `json:"terminal_failures"`
	TerminalFailureCodes []string          `json:"terminal_failure_codes"`
	Message              string            `json:"message"`
	Remediation          string            `json:"remediation"`
	HandoffOwner         string            `json:"handoff_owner"`
	HandoffRequired      bool              `json:"handoff_required"`
}
