package main

type guardianEvidence struct {
	Schema                      string                    `json:"schema"`
	Route                       string                    `json:"route"`
	CheckName                   string                    `json:"check_name"`
	Repository                  string                    `json:"repository"`
	PRNumber                    int64                     `json:"pr_number"`
	Action                      string                    `json:"action"`
	BaseRepo                    string                    `json:"base_repo"`
	BaseRef                     string                    `json:"base_ref"`
	BaseSHA                     string                    `json:"base_sha"`
	HeadRepo                    string                    `json:"head_repo"`
	HeadRef                     string                    `json:"head_ref"`
	HeadSHA                     string                    `json:"head_sha"`
	WorkflowRef                 string                    `json:"workflow_ref"`
	WorkflowSHA                 string                    `json:"workflow_sha"`
	RuntimeRef                  string                    `json:"runtime_ref"`
	RuntimeSHA                  string                    `json:"runtime_sha"`
	EventRef                    string                    `json:"event_ref"`
	DefaultBranch               string                    `json:"default_branch"`
	ObserverEnvironmentName     string                    `json:"observer_environment"`
	InstallationRepositoryScope guardianInstallationScope `json:"installation_repository_scope"`
	RunID                       int64                     `json:"run_id"`
	RunAttempt                  int64                     `json:"run_attempt"`
	WorkflowID                  int64                     `json:"workflow_id"`
	WorkflowPath                string                    `json:"workflow_path"`
	RunEvent                    string                    `json:"run_event"`
	RunStatus                   string                    `json:"run_status"`
	RunConclusion               string                    `json:"run_conclusion"`
	RunCreatedAt                string                    `json:"run_created_at"`
	RunNumber                   int64                     `json:"run_number"`
	LiveRefsBefore              guardianLiveRefs          `json:"live_refs_before"`
	LiveRefsAfter               guardianLiveRefs          `json:"live_refs_after"`
	Topology                    guardianTopology          `json:"topology"`
	BranchProtection            branchProtection          `json:"branch_protection"`
	DevBranchProtection         branchProtection          `json:"dev_branch_protection"`
	ObserverEnvironmentSnapshot guardianEnvironment       `json:"observer_environment_snapshot"`
	ObserverEnvironmentDigest   string                    `json:"observer_environment_digest"`
	ArtifactID                  int64                     `json:"artifact_id"`
	ArtifactName                string                    `json:"artifact_name"`
	ArtifactSize                int64                     `json:"artifact_size"`
	ArtifactExpired             bool                      `json:"artifact_expired"`
	ArtifactDigest              string                    `json:"artifact_digest"`
	ManifestBundleSHA           string                    `json:"manifest_bundle_sha256"`
	GuardianJobID               int64                     `json:"guardian_job_id"`
	GuardianJobName             string                    `json:"guardian_job_name"`
	GuardianJobStatus           string                    `json:"guardian_job_status"`
	GuardianJobConclusion       string                    `json:"guardian_job_conclusion"`
	GuardianJobHeadSHA          string                    `json:"guardian_job_head_sha"`
	CheckRunID                  int64                     `json:"check_run_id"`
	CheckRunName                string                    `json:"check_run_name"`
	CheckRunAppID               int64                     `json:"check_run_app_id"`
	CheckRunStatus              string                    `json:"check_run_status"`
	CheckRunConclusion          string                    `json:"check_run_conclusion"`
	CheckRunHeadSHA             string                    `json:"check_run_head_sha"`
	CheckSuiteID                int64                     `json:"check_suite_id"`
	Decision                    string                    `json:"decision"`
	Code                        *string                   `json:"code"`
	HeadBindingStatus           string                    `json:"head_binding_status"`
	BundleSHA                   string                    `json:"bundle_sha256"`
}
