package verify

func init() {
	branchScopeAllowlist["agent/gooo-quadratic-hole-search-20261008"] = []string{
		".github/agent-scope-table.md",
		".github/ci-governance.json",
		"cmd/gooo/body_quadratic_fit_test.go",
		"cmd/gooo/body_quadratic_refine_test.go",
		"docs/research/quadratic-feedback-20261008/README.md",
		"docs/research/quadratic-feedback-20261008/refinement.json",
		"docs/research/quadratic-feedback-20261008/replay.json",
		"docs/research/quadratic-feedback-20261008/sha256.json",
		"docs/research/quadratic-feedback-20261008/summary.json",
		"docs/research/quadratic-fit-feedback-20261008/README.md",
		"docs/research/quadratic-fit-feedback-20261008/refinement.json",
		"docs/research/quadratic-fit-feedback-20261008/replay.json",
		"docs/research/quadratic-fit-feedback-20261008/sha256.json",
		"docs/research/quadratic-fit-feedback-20261008/summary.json",
		"docs/source-assembly.md",
		"examples/quadratic-feedback/README.md",
		"examples/quadratic-feedback/evaluation-cases.json",
		"examples/quadratic-feedback/feedback-cases.json",
		"examples/quadratic-feedback/source.gooo.fixture",
		"examples/quadratic-fit-feedback/README.md",
		"examples/quadratic-fit-feedback/evaluation-cases.json",
		"examples/quadratic-fit-feedback/feedback-cases.json",
		"examples/quadratic-fit-feedback/source.gooo.fixture",
		"internal/assemblyspec/search_alternatives.go",
		"internal/assemblyspec/spec.go",
		"internal/bidir/quadratic_search_test.go",
		"internal/bodycodegen/body_search_candidate_generation.go",
		"internal/bodycodegen/body_search_hole_arithmetic.go",
		"internal/bodycodegen/body_search_hole_context.go",
		"internal/bodycodegen/body_search_hole_quadratic.go",
		"internal/bodycodegen/body_search_hole_quadratic_order.go",
		"internal/bodycodegen/body_search_hole_quadratic_order_test.go",
		"internal/bodycodegen/body_search_hole_quadratic_test.go",
		"internal/verify/scope_gooo_quadratic_hole_search_20261008.go",
	}
}
