package verify

func init() {
	branchScopeAllowlist["agent/gooo-domain-tools-20261007"] = []string{
		".github/agent-scope-table.md",
		".github/ci-governance.json",
		"cmd/gooo/package_construction_input.go",
		"cmd/gooo/package_construction_input_test.go",
		"cmd/gooo/package_domain_tools_test.go",
		"cmd/gooo/package_execute.go",
		"docs/language-direction.ko.md",
		"docs/research/domain-tools-20261007/assembly-deterministic.json",
		"docs/research/domain-tools-20261007/assembly-model.json",
		"docs/research/domain-tools-20261007/documentation-deterministic.json",
		"docs/research/domain-tools-20261007/documentation-model.json",
		"docs/research/domain-tools-20261007/observation-summary.json",
		"docs/research/domain-tools-20261007/observation.json",
		"docs/research/domain-tools-20261007/summary.json",
		"examples/assembly-explainer/README.md",
		"examples/domain-tools/README.md",
		"examples/domain-tools/assembly.cases.json",
		"examples/domain-tools/assembly.gooo.fixture",
		"examples/domain-tools/assembly.inputs.json",
		"examples/domain-tools/assembly.workspace.json",
		"examples/domain-tools/documentation.cases.json",
		"examples/domain-tools/documentation.gooo.fixture",
		"examples/domain-tools/documentation.inputs.json",
		"examples/domain-tools/documentation.workspace.json",
		"examples/domain-tools/render.gooo.fixture",
		"examples/domain-tools/report.gooo.fixture",
		"internal/bodyexecution/receipt_decode.go",
		"internal/bodyexecution/record_observation.go",
		"internal/bodyexecution/record_observation_test.go",
		"internal/verify/scope_gooo_domain_tools_20261007.go",
	}
}
