package verify

func init() {
	branchScopeAllowlist["agent/gooo-assembly-resume-20261008"] = []string{
		".github/agent-scope-table.md",
		".github/ci-governance.json",
		"cmd/gooo/body_compose.go",
		"cmd/gooo/body_compose_policy.go",
		"cmd/gooo/body_compose_resume_test.go",
		"docs/language-direction.ko.md",
		"docs/language/body-codegen.md",
		"docs/research/assembly-resume-20261008/build.json",
		"docs/research/assembly-resume-20261008/deterministic-checkpoint.json",
		"docs/research/assembly-resume-20261008/deterministic-checkpoint.time",
		"docs/research/assembly-resume-20261008/deterministic-continued.json",
		"docs/research/assembly-resume-20261008/deterministic-continued.time",
		"docs/research/assembly-resume-20261008/exhausted.json",
		"docs/research/assembly-resume-20261008/exhausted.time",
		"docs/research/assembly-resume-20261008/model-checkpoint.json",
		"docs/research/assembly-resume-20261008/model-checkpoint.time",
		"docs/research/assembly-resume-20261008/model-continued.json",
		"docs/research/assembly-resume-20261008/model-continued.time",
		"docs/research/assembly-resume-20261008/replay.json",
		"docs/research/assembly-resume-20261008/replay.time",
		"docs/research/assembly-resume-20261008/summary.json",
		"docs/research/assembly-resume-20261008/unsolved-checkpoint.json",
		"docs/research/assembly-resume-20261008/unsolved-checkpoint.time",
		"docs/research/assembly-resume-20261008/unsolved-continued.json",
		"docs/research/assembly-resume-20261008/unsolved-continued.time",
		"docs/research/verified-construction-thesis.md",
		"examples/assembly-policy/README.md",
		"examples/assembly-policy/checkpoint.gooo.fixture",
		"internal/bodycodegen/record_assembly.go",
		"internal/bodycodegen/record_assembly_replay.go",
		"internal/bodycodegen/record_assembly_types.go",
		"internal/bodycodegen/record_policy.go",
		"internal/bodycodegen/record_policy_types.go",
		"internal/bodycodegen/record_resume.go",
		"internal/bodycodegen/record_resume_test.go",
		"internal/bodyexecution/composition.go",
		"internal/bodyexecution/composition_resume.go",
		"internal/bodyexecution/composition_resume_test.go",
		"internal/verify/scope_gooo_assembly_resume_20261008.go",
	}
}
