package verify

func init() {
	branchScopeAllowlist["agent/gooo-assembly-policy-20261008"] = []string{
		".github/agent-scope-table.md",
		".github/ci-governance.json",
		"cmd/gooo/body_compose.go",
		"cmd/gooo/body_compose_policy.go",
		"cmd/gooo/body_compose_policy_test.go",
		"docs/language/body-codegen.md",
		"docs/research/assembly-policy-20261008/build.json",
		"docs/research/assembly-policy-20261008/deterministic.json",
		"docs/research/assembly-policy-20261008/deterministic.time",
		"docs/research/assembly-policy-20261008/model.json",
		"docs/research/assembly-policy-20261008/model.time",
		"docs/research/assembly-policy-20261008/policy-cases.json",
		"docs/research/assembly-policy-20261008/policy-native.json",
		"docs/research/assembly-policy-20261008/replay.json",
		"docs/research/assembly-policy-20261008/replay.time",
		"docs/research/assembly-policy-20261008/summary.json",
		"docs/research/assembly-policy-20261008/unsolved.exit",
		"docs/research/assembly-policy-20261008/unsolved.json",
		"docs/research/assembly-policy-20261008/unsolved.time",
		"examples/assembly-policy/README.md",
		"examples/assembly-policy/cases.json",
		"examples/assembly-policy/unsolved.gooo.fixture",
		"internal/bodycodegen/record_assembly.go",
		"internal/bodycodegen/record_assembly_replay.go",
		"internal/bodycodegen/record_assembly_types.go",
		"internal/bodycodegen/record_policy.go",
		"internal/bodycodegen/record_policy_selection_test.go",
		"internal/bodycodegen/record_policy_test.go",
		"internal/bodycodegen/record_policy_types.go",
		"internal/bodyexecution/composition_policy_test.go",
		"internal/bodyexecution/composition_source_fill.go",
		"internal/bodyexecution/composition_source_search.go",
		"internal/verify/scope_gooo_assembly_policy_20261008.go",
	}
}
