package verify

func init() {
	branchScopeAllowlist["agent/main-language-preview-20260906"] = []string{
		".github/agent-scope-table.md",
		".github/ci-governance.json",
		".github/workflows/ci.yml",
		"cmd/callback-preview/factory_test.go",
		"cmd/callback-preview/main.go",
		"cmd/callback-preview/main_test.go",
		"examples/language-syntax-roundtrip/corpus.json",
		"internal/meta/generation/callback-extraction-contract.gooo",
		"internal/meta/generation/callback-preview-contract.gooo",
		"internal/meta/generation/callback_extraction_contract.go",
		"internal/meta/generation/callback_extraction_contract_test.go",
		"internal/meta/generation/callback_extraction_observer_test.go",
		"internal/meta/generation/callback_preview_contract.go",
		"internal/meta/generation/callback_preview_contract_test.go",
		"internal/meta/languagereadiness/languagesyntax/conformance/evaluate_test.go",
		"internal/meta/languagereadiness/languagesyntax/registry.go",
		"internal/meta/repositoryprojection/extractor/callback_extraction_claims.go",
		"internal/meta/repositoryprojection/extractor/callback_extraction_observation.go",
		"internal/meta/repositoryprojection/extractor/callback_extraction_observation_test.go",
		"internal/meta/repositoryprojection/extractor/callback_extraction_plan.go",
		"internal/meta/repositoryprojection/extractor/callback_extraction_plan_test.go",
		"internal/meta/repositoryprojection/extractor/callback_factory.go",
		"internal/meta/repositoryprojection/extractor/callback_factory_test.go",
		"internal/meta/repositoryprojection/extractor/callback_observation_module.go",
		"internal/meta/repositoryprojection/extractor/callback_observation_module_test.go",
		"internal/meta/repositoryprojection/extractor/callback_observation_workspace.go",
		"internal/meta/repositoryprojection/extractor/callback_preview.go",
		"internal/meta/repositoryprojection/extractor/callback_preview_test.go",
		"internal/meta/repositoryprojection/extractor/capacity_failure_diagnostics_test.go",
		"internal/meta/repositoryprojection/extractor/closure_preservation.go",
		"internal/meta/repositoryprojection/extractor/closure_preservation_structure.go",
		"internal/meta/repositoryprojection/extractor/closure_preservation_test.go",
		"internal/meta/repositoryprojection/extractor/decompose.go",
		"internal/meta/repositoryprojection/extractor/extract.go",
		"internal/meta/repositoryprojection/extractor/rendered_capacity_progress_regression_test.go",
		"internal/meta/repositoryprojection/extractor/suffix_closure_identity_test.go",
		"internal/verify/scope_callback_preview_20260907.go",
		"internal/verify/scope_callback_preview_20260907_test.go",
	}
}
