package verify

func init() {
	branchScopeAllowlist["agent/language-multi-file-execution"] = []string{
		"bootstrap/function-extractor/recipes.json",
		".github/agent-scope-table.md",
		".github/ci-governance.json",
		".github/workflows/ci.yml",
		"cmd/gooo/run_package_source.go",
		"cmd/gooo/run_package_source_test.go",
		"cmd/gooo/run_source_part01.go",
		"cmd/gooo/run_source_part02.go",
		"cmd/language-package-execution-witness",
		"docs/language/language-package-execution.md",
		"examples/billing-package",
		"examples/language-delivery-scorecard/contract.json",
		"examples/language-package-execution",
		"examples/language-syntax-roundtrip/corpus.json",
		"examples/user-journey-scorecard/contract.json",
		"internal/meta/languageconcept/artifact_test.go",
		"internal/meta/languagedelivery",
		"internal/meta/languagereadiness/languagesyntax/conformance/evaluate_test.go",
		"internal/meta/languagereadiness/languagesyntax/model.go",
		"internal/meta/languagereadiness/languagesyntax/registry.go",
		"internal/meta/languagepackageexecution",
		"internal/meta/userjourneyscorecard",
		"internal/packageruntime/packageexecution",
		"internal/verify/scope_language_package_execution.go",
		"scripts/language-package-execution",
		"scripts/source-subject-witness/applicability.go",
		"scripts/source-subject-witness/applicability_fixture_test.go",
		"scripts/source-subject-witness/applicability_test.go",
		"scripts/source-subject-witness/catalog_binding_test.go",
		"scripts/source-subject-witness/counts.go",
		"scripts/source-subject-witness/function_binding.go",
		"scripts/source-subject-witness/validate.go",
		"scripts/source-subject-witness/source.go",
		"scripts/source-subject-witness/source_test.go",
	}
}
