package verify

func init() {
	branchScopeAllowlist["agent/gooo-source-fill-composition-20261007"] = []string{
		".github/agent-scope-table.md",
		".github/ci-governance.json",
		"cmd/gooo/body_compose.go",
		"cmd/gooo/body_compose_fill_test.go",
		"cmd/gooo/body_compose_search_test.go",
		"docs/language-direction.ko.md",
		"docs/native-body-composition.md",
		"docs/research/source-fill-dogfood-20261007.json",
		"docs/research/source-fill-native-20261007/deterministic-native.json",
		"docs/research/source-fill-native-20261007/model-native.json",
		"docs/research/source-fill-native-20261007/saved-replay.json",
		"examples/body-codegen/source-fill-composition-cases.json",
		"examples/body-codegen/source-fill-composition.gooo.fixture",
		"examples/body-codegen/source-search-composition-cases.json",
		"examples/body-codegen/source-search-composition.gooo.fixture",
		"internal/bodycodegen/body_fill.go",
		"internal/bodycodegen/body_fill_decision.go",
		"internal/bodycodegen/body_fill_record.go",
		"internal/bodycodegen/body_fill_tiny.go",
		"internal/bodycodegen/body_realize.go",
		"internal/bodycodegen/completeness_receipt.go",
		"internal/bodycodegen/record_assembly_plan.go",
		"internal/bodycodegen/source_fill_replay.go",
		"internal/bodycodegen/source_fill_replay_test.go",
		"internal/bodycodegen/source_search_composition.go",
		"internal/bodycodegen/source_search_composition_test.go",
		"internal/bodyexecution/composition.go",
		"internal/bodyexecution/composition_prepare.go",
		"internal/bodyexecution/composition_source_fill.go",
		"internal/bodyexecution/composition_source_fill_test.go",
		"internal/bodyexecution/composition_source_search.go",
		"internal/bodyexecution/composition_source_search_test.go",
		"internal/verify/scope_gooo_source_fill_composition_20261007.go",
		"internal/verify/scope_gooo_source_search_composition_20261007.go",
	}
}
