package verify

func init() {
	branchScopeAllowlist["agent/core-evidence-integration-20260911"] = []string{
		".github/agent-scope-table.md",
		".github/ci-governance.json",
		".github/workflows/ci.yml",
		".github/workflows/self-improvement-contract.yml",
		".github/workflows/transformation-effect.yml",
		"cmd/gooo/graph_fields_dump.go",
		"cmd/gooo/graph_fields_invalid_test.go",
		"cmd/gooo/graph_fields_v1.go",
		"cmd/gooo/graph_fields_v1_test.go",
		"cmd/gooo/main_part01.go",
		"cmd/language-syntax-witness/io.go",
		"cmd/language-syntax-witness/negative_report.go",
		"cmd/language-syntax-witness/negative_report_test.go",
		"cmd/language-syntax-witness/run.go",
		"examples/language-syntax-roundtrip/corpus.json",
		"examples/relay-game-contract/README.md",
		"examples/relay-game-contract/main.gooo",
		"internal/meta/languagereadiness/languagesyntax/conformance/evaluate_test.go",
		"internal/meta/languagereadiness/languagesyntax/registry.go",
		"internal/verify/scope_core_evidence_integration_20260911.go",
		"internal/verify/scope_graph_observer_coverage_20260911.go",
		"internal/verify/scope_native_test_cost_trace_20260911.go",
		"internal/verify/scope_pr_authoritative_contract_20260911.go",
		"internal/verify/scope_relay_graph_fields_20260911.go",
		"internal/verify/scope_syntax_negative_evidence_20260911.go",
		"internal/verify/workflow_part03_test.go",
		"scripts/ci-proof/domain.go",
		"scripts/ci-proof/graph_observation.go",
		"scripts/ci-proof/graph_observation_test.go",
		"scripts/meta-execution/collapse_execution_test.go",
		"scripts/meta-execution/collapse_execution_trace_test.go",
		"scripts/self-improvement-contract/workflow_authority_cases_test.go",
		"scripts/self-improvement-contract/workflow_authority_test.go",
	}
}
