package semanticdeltareceiptconsumer

const (
	receiptSchema       = "gooo/semantic-delta-receipt/v1"
	producerName        = "semanticdeltareceipt.ProduceFiles"
	consumerName        = "semanticdeltareceiptconsumer.AdjudicateFiles"
	metaOperation       = "separate-text-structural-semantic-deltas"
	decisionFixedPoint  = "FIXED_POINT"
	decisionDelta       = "DELTA_OBSERVED"
	decisionFailClosed  = "FAIL_CLOSED"
	resolutionExact     = "EXACT"
	resolutionUnknown   = "UNKNOWN"
	resolutionLower     = "LOWER_RESOLUTION"
	resolutionInvariant = "INVARIANT_ONLY"
	classPreserved      = "SEMANTIC_PRESERVED"
	classChanged        = "SEMANTIC_CHANGED"
	classIndeterminate  = "INDETERMINATE"
	statusOpen          = "OPEN"
	statusDischarged    = "DISCHARGED"
	statusRefuted       = "REFUTED"
	rawChanged          = "RAW_CHANGED"
	rawFixedPoint       = "RAW_FIXED_POINT"
	semanticPreserved   = "SEMANTIC_PRESERVED"
	semanticChanged     = "SEMANTIC_CHANGED"
	semanticUnknown     = "SEMANTIC_UNKNOWN"
	reasonTextualOnly   = "TEXTUAL_DELTA_WITH_SEMANTIC_FIXED_POINT"
	reasonMeaning       = "SEMANTIC_CLAIM_DELTA_OBSERVED"
	reasonUnavailable   = "SEMANTIC_TRANSLATION_VALIDATION_UNAVAILABLE"
	reasonReceipt       = "SEMANTIC_DELTA_RECEIPT_MISMATCH"
	reasonSubject       = "SEMANTIC_DELTA_SUBJECT_UNKNOWN"
)
