package semanticdeltareceiptconsumer

const (
	receiptSchema        = "gooo/semantic-delta-receipt/v2"
	producerName         = "semanticdeltareceipt.ProduceFiles"
	consumerName         = "semanticdeltareceiptconsumer.AdjudicateFiles"
	metaOperation        = "separate-text-structural-semantic-deltas"
	decisionFixedPoint   = "FIXED_POINT"
	decisionDelta        = "DELTA_OBSERVED"
	decisionFailClosed   = "FAIL_CLOSED"
	resolutionExact      = "EXACT"
	resolutionLower      = "LOWER_RESOLUTION"
	resolutionInvariant  = "INVARIANT_ONLY"
	classPreserved       = "SEMANTIC_PRESERVED"
	classChanged         = "SEMANTIC_CHANGED"
	classIndeterminate   = "INDETERMINATE"
	statusOpen           = "OPEN"
	statusDischarged     = "DISCHARGED"
	statusRefuted        = "REFUTED"
	rawChanged           = "RAW_CHANGED"
	rawFixedPoint        = "RAW_FIXED_POINT"
	semanticPreserved    = "SEMANTIC_PRESERVED"
	semanticChanged      = "SEMANTIC_CHANGED"
	semanticUnknown      = "SEMANTIC_UNKNOWN"
	reasonTextualOnly    = "TEXTUAL_DELTA_WITH_SEMANTIC_FIXED_POINT"
	reasonMeaning        = "SEMANTIC_CLAIM_DELTA_OBSERVED"
	reasonUnavailable    = "SEMANTIC_TRANSLATION_VALIDATION_UNAVAILABLE"
	reasonReceipt        = "SEMANTIC_DELTA_RECEIPT_MISMATCH"
	reasonSubject        = "SEMANTIC_DELTA_SUBJECT_UNKNOWN"
	reasonComponentDelta = "SEMANTIC_COMPONENT_DELTA_OBSERVED"
	reasonUnmodeled      = "UNMODELED_SEMANTIC_COMPONENT_CHANGED"
	reasonAmbiguous      = "AMBIGUOUS_CLAIM_MATCH"
	reasonMeta           = "META_CONTRACT_UNAVAILABLE"
	claimKindBounded     = "BOUNDED_SEMANTIC_EQUIVALENCE"
	claimKindObject      = "OBJECT_PROPOSITION"
	claimKindPreserve    = "BEFORE_CLAIM_PRESERVATION"
	unavailableStage     = "project-source"
	unavailableStep      = "parse-lower"
	componentNode        = "node-semantic"
	componentField       = "entity-field"
	componentValue       = "activity-value-program"
	componentRelation    = "relation-fact"
	componentFingerprint = "ir-semantic-fingerprint"
)
