package generator

import (
	"fmt"
	"strconv"
	"strings"
)

// canonicalMarkerManifestV1 returns the exact marker evidence bytes. Its
// schema is: one header record (schema, version, encoding, newline), one
// regions count record, then region records with rank, ID, kind, byte bounds,
// line bounds, and slot count, followed by slot records with region rank,
// rank, ID, owner ID/kind, and byte/line bounds. Regions are ordered by
// generated byte bounds and slots by their bounds. IDs and kinds are checked
// against the normalized SemanticIR; maps are lookup-only and never serialized.
// Every record ends in exactly one LF, including the final record; validation
// completes before any bytes are returned.
func canonicalMarkerManifestV1(source []byte, markers parsedMarkers, ir SemanticIR) ([]byte, error) {
	regions, err := normalizeMarkerManifestV1(source, markers, ir)
	if err != nil {
		return nil, err
	}
	var manifest strings.Builder
	manifest.WriteString("schema\t")
	manifest.WriteString(canonicalMarkerManifestSchemaV1)
	manifest.WriteString("\tprofile\t")
	manifest.WriteString(canonicalMarkerManifestProfileV1)
	manifest.WriteString("\tversion\t")
	manifest.WriteString(strconv.Itoa(canonicalMarkerManifestVersionV1))
	manifest.WriteString("\tencoding\t")
	manifest.WriteString(canonicalMarkerManifestEncodingV1)
	manifest.WriteString("\tterminal-newline\t")
	manifest.WriteString(canonicalMarkerManifestNewlineV1)
	manifest.WriteByte('\n')
	fmt.Fprintf(&manifest, "regions\t%d\n", len(regions))
	for regionIndex, region := range regions {
		id, err := markerManifestStringV1(region.ID)
		if err != nil {
			return nil, err
		}
		kind, err := markerManifestStringV1(region.Kind)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&manifest, "%s\t%d\t%s\t%s\t%d\t%d\t%d\t%d\t%d\n", canonicalMarkerManifestRegionRecordV1, regionIndex, id, kind, region.Start, region.End, region.StartLine, region.EndLine, len(region.Slots))
		for slotIndex, slot := range region.Slots {
			if err := writeMarkerManifestSlotV1(&manifest, regionIndex, slotIndex, slot); err != nil {
				return nil, err
			}
		}
	}
	return []byte(manifest.String()), nil
}
func writeMarkerManifestSlotV1(manifest *strings.Builder, regionIndex, slotIndex int, slot markerManifestSlotV1) error {
	id, err := markerManifestStringV1(slot.ID)
	if err != nil {
		return err
	}
	regionID, err := markerManifestStringV1(slot.RegionID)
	if err != nil {
		return err
	}
	regionKind, err := markerManifestStringV1(slot.RegionKind)
	if err != nil {
		return err
	}
	fmt.Fprintf(manifest, "%s\t%d\t%d\t%s\t%s\t%s\t%d\t%d\t%d\t%d\n", canonicalMarkerManifestSlotRecordV1, regionIndex, slotIndex, id, regionID, regionKind, slot.Start, slot.End, slot.StartLine, slot.EndLine)
	return nil
}
