package generator

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

const (
	canonicalMarkerManifestSchemaV1       = "gooo.generator.marker-manifest"
	canonicalMarkerManifestProfileV1      = "generated-regions-and-slots"
	canonicalMarkerManifestVersionV1      = 1
	canonicalMarkerManifestEncodingV1     = "utf-8-byte-length-hex"
	canonicalMarkerManifestNewlineV1      = "LF"
	canonicalMarkerManifestRegionRecordV1 = "region"
	canonicalMarkerManifestSlotRecordV1   = "slot"
)

// markerManifestRegionV1 and markerManifestSlotV1 are the fixed typed fields
// emitted by canonicalMarkerManifestV1. IDs and kinds are source marker
// strings; their output tokens are UTF-8 byte length followed by lowercase
// hexadecimal bytes, so tabs, newlines, and map iteration cannot change the
// record grammar.
type markerManifestRegionV1 struct {
	ID        string
	Kind      string
	Start     int
	End       int
	StartLine int
	EndLine   int
	Slots     []markerManifestSlotV1
}

type markerManifestSlotV1 struct {
	ID         string
	RegionID   string
	RegionKind string
	Start      int
	End        int
	StartLine  int
	EndLine    int
}

// canonicalMarkerManifestV1 returns the exact marker evidence bytes. Its
// schema is: one header record (schema, version, encoding, newline), one
// regions count record, then region records with rank, ID, kind, byte bounds,
// line bounds, and slot count, followed by slot records with region rank,
// rank, ID, owner ID/kind, and byte/line bounds. Regions are ordered by
// generated byte bounds and slots by their bounds. IDs and kinds are checked
// against the normalized SemanticIR; maps are lookup-only and never serialized.
// Every record ends in exactly one LF, including the final record; validation
// completes before any bytes are returned.
func canonicalMarkerManifestV1(source []byte, markers parsedMarkers, ir SemanticIR) ([]byte, error) {
	regions, err := normalizeMarkerManifestV1(source, markers, ir)
	if err != nil {
		return nil, err
	}
	var manifest strings.Builder
	manifest.WriteString("schema\t")
	manifest.WriteString(canonicalMarkerManifestSchemaV1)
	manifest.WriteString("\tprofile\t")
	manifest.WriteString(canonicalMarkerManifestProfileV1)
	manifest.WriteString("\tversion\t")
	manifest.WriteString(strconv.Itoa(canonicalMarkerManifestVersionV1))
	manifest.WriteString("\tencoding\t")
	manifest.WriteString(canonicalMarkerManifestEncodingV1)
	manifest.WriteString("\tterminal-newline\t")
	manifest.WriteString(canonicalMarkerManifestNewlineV1)
	manifest.WriteByte('\n')
	fmt.Fprintf(&manifest, "regions\t%d\n", len(regions))
	for regionIndex, region := range regions {
		id, err := markerManifestStringV1(region.ID)
		if err != nil {
			return nil, err
		}
		kind, err := markerManifestStringV1(region.Kind)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&manifest, "%s\t%d\t%s\t%s\t%d\t%d\t%d\t%d\t%d\n", canonicalMarkerManifestRegionRecordV1, regionIndex, id, kind, region.Start, region.End, region.StartLine, region.EndLine, len(region.Slots))
		for slotIndex, slot := range region.Slots {
			if err := writeMarkerManifestSlotV1(&manifest, regionIndex, slotIndex, slot); err != nil {
				return nil, err
			}
		}
	}
	return []byte(manifest.String()), nil
}

func writeMarkerManifestSlotV1(manifest *strings.Builder, regionIndex, slotIndex int, slot markerManifestSlotV1) error {
	id, err := markerManifestStringV1(slot.ID)
	if err != nil {
		return err
	}
	regionID, err := markerManifestStringV1(slot.RegionID)
	if err != nil {
		return err
	}
	regionKind, err := markerManifestStringV1(slot.RegionKind)
	if err != nil {
		return err
	}
	fmt.Fprintf(manifest, "%s\t%d\t%d\t%s\t%s\t%s\t%d\t%d\t%d\t%d\n", canonicalMarkerManifestSlotRecordV1, regionIndex, slotIndex, id, regionID, regionKind, slot.Start, slot.End, slot.StartLine, slot.EndLine)
	return nil
}

func normalizeMarkerManifestV1(source []byte, markers parsedMarkers, ir SemanticIR) ([]markerManifestRegionV1, error) {
	expectedRegions, expectedSlots, err := expectedMarkerManifestOwnersV1(ir)
	if err != nil {
		return nil, err
	}
	regions := make([]markerManifestRegionV1, 0, len(markers.Regions))
	seenRegions := make(map[string]struct{}, len(markers.Regions))
	seenSlots := make(map[string]markerManifestSlotV1, len(markers.Slots))
	for _, observed := range markers.Regions {
		if err := validateMarkerRegionV1(source, observed, expectedRegions, seenRegions); err != nil {
			return nil, err
		}
		region := markerManifestRegionV1{ID: observed.ID, Kind: observed.Kind, Start: observed.Start, End: observed.End, StartLine: observed.StartLine, EndLine: observed.EndLine}
		for _, observedSlot := range observed.Slots {
			slot, err := validateMarkerSlotV1(source, observed, observedSlot, expectedSlots, seenSlots)
			if err != nil {
				return nil, err
			}
			region.Slots = append(region.Slots, slot)
		}
		sort.SliceStable(region.Slots, func(left, right int) bool { return markerManifestSlotLessV1(region.Slots[left], region.Slots[right]) })
		if err := validateMarkerSlotOrderV1(region); err != nil {
			return nil, err
		}
		regions = append(regions, region)
	}
	if len(regions) != len(expectedRegions) {
		return nil, fmt.Errorf("generator: marker manifest v1 region count %d does not match declared count %d", len(regions), len(expectedRegions))
	}
	if len(seenSlots) != len(expectedSlots) || len(markers.Slots) != len(expectedSlots) {
		return nil, fmt.Errorf("generator: marker manifest v1 slot count does not match declared count")
	}
	for slotID, expected := range seenSlots {
		observed, exists := markers.Slots[slotID]
		if !exists || !sameParsedSlotV1(source, observed, expected) {
			return nil, fmt.Errorf("generator: marker manifest v1 slot map disagrees for %q", slotID)
		}
	}
	sort.SliceStable(regions, func(left, right int) bool { return markerManifestRegionLessV1(regions[left], regions[right]) })
	if err := validateMarkerRegionOrderV1(regions); err != nil {
		return nil, err
	}
	return regions, nil
}

func expectedMarkerManifestOwnersV1(ir SemanticIR) (map[string]string, map[string]markerManifestSlotV1, error) {
	expectedRegions := make(map[string]string, len(ir.Entities)+len(ir.Activities))
	expectedSlots := make(map[string]markerManifestSlotV1)
	for _, entity := range ir.Entities {
		if err := addMarkerManifestRegionOwnerV1(expectedRegions, entity.ID, "entity"); err != nil {
			return nil, nil, err
		}
	}
	for _, activity := range ir.Activities {
		if err := addMarkerManifestRegionOwnerV1(expectedRegions, activity.ID, "activity"); err != nil {
			return nil, nil, err
		}
		for _, slot := range activity.Slots {
			if slot.ID == "" {
				return nil, nil, fmt.Errorf("generator: marker manifest v1 declared slot has empty ID")
			}
			if _, exists := expectedSlots[slot.ID]; exists {
				return nil, nil, fmt.Errorf("generator: marker manifest v1 duplicate declared slot ID %q", slot.ID)
			}
			expectedSlots[slot.ID] = markerManifestSlotV1{ID: slot.ID, RegionID: activity.ID, RegionKind: "activity"}
		}
	}
	return expectedRegions, expectedSlots, nil
}

func addMarkerManifestRegionOwnerV1(owners map[string]string, id, kind string) error {
	if id == "" {
		return fmt.Errorf("generator: marker manifest v1 declared %s has empty ID", kind)
	}
	if _, exists := owners[id]; exists {
		return fmt.Errorf("generator: marker manifest v1 duplicate declared region ID %q", id)
	}
	owners[id] = kind
	return nil
}

func validateMarkerRegionV1(source []byte, observed generatedRegion, expected map[string]string, seen map[string]struct{}) error {
	if observed.ID == "" {
		return fmt.Errorf("generator: marker manifest v1 region has empty ID")
	}
	if _, exists := seen[observed.ID]; exists {
		return fmt.Errorf("generator: marker manifest v1 duplicate region ID %q", observed.ID)
	}
	wantKind, exists := expected[observed.ID]
	if !exists {
		return fmt.Errorf("generator: marker manifest v1 unknown region ID %q", observed.ID)
	}
	if observed.Kind != wantKind {
		return fmt.Errorf("generator: marker manifest v1 region %q has kind %q, want %q", observed.ID, observed.Kind, wantKind)
	}
	if err := validateMarkerBoundsV1(source, observed.Start, observed.End, observed.StartLine, observed.EndLine, true); err != nil {
		return fmt.Errorf("generator: marker manifest v1 region %q: %w", observed.ID, err)
	}
	seen[observed.ID] = struct{}{}
	return nil
}

func validateMarkerSlotV1(source []byte, region generatedRegion, observed parsedSlot, expected map[string]markerManifestSlotV1, seen map[string]markerManifestSlotV1) (markerManifestSlotV1, error) {
	want, exists := expected[observed.ID]
	if !exists {
		return markerManifestSlotV1{}, fmt.Errorf("generator: marker manifest v1 unknown slot ID %q", observed.ID)
	}
	if _, exists := seen[observed.ID]; exists {
		return markerManifestSlotV1{}, fmt.Errorf("generator: marker manifest v1 duplicate slot ID %q", observed.ID)
	}
	if observed.RegionID != region.ID || observed.RegionKind != region.Kind || observed.RegionID != want.RegionID || observed.RegionKind != want.RegionKind {
		return markerManifestSlotV1{}, fmt.Errorf("generator: marker manifest v1 slot %q has invalid owner", observed.ID)
	}
	if err := validateMarkerBoundsV1(source, observed.Start, observed.End, observed.StartLine, observed.EndLine, false); err != nil {
		return markerManifestSlotV1{}, fmt.Errorf("generator: marker manifest v1 slot %q: %w", observed.ID, err)
	}
	if !bytes.Equal(observed.Body, source[observed.Start:observed.End]) {
		return markerManifestSlotV1{}, fmt.Errorf("generator: marker manifest v1 slot %q body does not match source bounds", observed.ID)
	}
	if observed.Start < region.Start || observed.End > region.End || observed.End < observed.Start {
		return markerManifestSlotV1{}, fmt.Errorf("generator: marker manifest v1 slot %q is outside region bounds", observed.ID)
	}
	slot := markerManifestSlotV1{ID: observed.ID, RegionID: observed.RegionID, RegionKind: observed.RegionKind, Start: observed.Start, End: observed.End, StartLine: observed.StartLine, EndLine: observed.EndLine}
	seen[observed.ID] = slot
	return slot, nil
}

func validateMarkerBoundsV1(source []byte, start, end, startLine, endLine int, region bool) error {
	if start < 0 || end < start || end > len(source) || startLine < 0 || endLine < startLine {
		return fmt.Errorf("noncanonical byte or line bounds")
	}
	if region {
		if !markerLineStartV1(source, start) || !markerLineEndV1(source, end) || markerLineStartIndexV1(source, start) != startLine || markerLineEndIndexV1(source, end) != endLine {
			return fmt.Errorf("noncanonical generated-region boundary")
		}
		if end == start {
			return fmt.Errorf("empty generated region")
		}
		return nil
	}
	if !markerLineEndV1(source, start) || !markerLineStartV1(source, end) || markerLineEndIndexV1(source, start) != startLine || markerLineStartIndexV1(source, end) != endLine {
		return fmt.Errorf("noncanonical slot boundary")
	}
	return nil
}

func validateMarkerRegionOrderV1(regions []markerManifestRegionV1) error {
	for index := 1; index < len(regions); index++ {
		if regions[index-1].End > regions[index].Start {
			return fmt.Errorf("generator: marker manifest v1 generated regions overlap")
		}
	}
	return nil
}

func validateMarkerSlotOrderV1(region markerManifestRegionV1) error {
	for index := 1; index < len(region.Slots); index++ {
		if region.Slots[index-1].End > region.Slots[index].Start {
			return fmt.Errorf("generator: marker manifest v1 slots overlap in region %q", region.ID)
		}
	}
	return nil
}

func markerManifestRegionLessV1(left, right markerManifestRegionV1) bool {
	if left.Start != right.Start {
		return left.Start < right.Start
	}
	if left.End != right.End {
		return left.End < right.End
	}
	if left.Kind != right.Kind {
		return left.Kind < right.Kind
	}
	return left.ID < right.ID
}

func markerManifestSlotLessV1(left, right markerManifestSlotV1) bool {
	if left.Start != right.Start {
		return left.Start < right.Start
	}
	if left.End != right.End {
		return left.End < right.End
	}
	return left.ID < right.ID
}

func sameParsedSlotV1(source []byte, observed parsedSlot, expected markerManifestSlotV1) bool {
	return observed.ID == expected.ID && observed.RegionID == expected.RegionID && observed.RegionKind == expected.RegionKind && observed.Start == expected.Start && observed.End == expected.End && observed.StartLine == expected.StartLine && observed.EndLine == expected.EndLine && observed.Start >= 0 && observed.End >= observed.Start && observed.End <= len(source) && bytes.Equal(observed.Body, source[observed.Start:observed.End])
}
