package generator

import (
	"fmt"
	"strings"
)

const defaultHeader = "// Code generated by gooo. DO NOT EDIT."

func (g Generator) renderBlocks(ir SemanticIR, previous parsedMarkers) (map[string][]byte, []string, error) {
	blocks := make(map[string][]byte, len(ir.Entities)+len(ir.Activities))
	order := make([]string, 0, len(ir.Entities)+len(ir.Activities))
	for _, entity := range ir.Entities {
		block, err := formatBlock(ir.Package, renderEntity(entity))
		if err != nil {
			return nil, nil, fmt.Errorf("generator: format entity %q: %w", entity.ID, err)
		}
		blocks[entity.ID] = block
		order = append(order, entity.ID)
	}
	for _, activity := range ir.Activities {
		block, err := formatBlock(ir.Package, renderActivity(activity, previous.Slots))
		if err != nil {
			return nil, nil, fmt.Errorf("generator: format activity %q: %w", activity.ID, err)
		}
		blocks[activity.ID] = block
		order = append(order, activity.ID)
	}
	return blocks, order, nil
}
func renderEntity(entity Entity) string {
	var output strings.Builder
	fmt.Fprintf(&output, "%s\n", generatedMarker(generatedStartPrefix, entity.ID, "entity"))
	if len(entity.Fields) == 0 {
		fmt.Fprintf(&output, "type %s struct{}\n", entity.GoName)
	} else {
		fmt.Fprintf(&output, "type %s struct {\n", entity.GoName)
		for _, field := range entity.Fields {
			fmt.Fprintf(&output, "\t%s %s\n", field.GoName, field.GoType)
		}
		output.WriteString("}\n")
	}
	fmt.Fprintf(&output, "%s\n", generatedMarker(generatedEndPrefix, entity.ID, "entity"))
	return output.String()
}
func renderActivity(activity Activity, previous map[string]parsedSlot) string {
	var output strings.Builder
	fmt.Fprintf(&output, "%s\n", generatedMarker(generatedStartPrefix, activity.ID, "activity"))
	fmt.Fprintf(&output, "func %s(%s)%s {\n", activity.GoName, renderInputs(activity.Inputs), renderOutputs(activity.Outputs))
	for _, slot := range activity.Slots {
		fmt.Fprintf(&output, "\t%s\n", slotMarker(slotStartPrefix, slot.ID))
		body, exists := previous[slot.ID]
		if exists {
			output.Write(body.Body)
			if len(body.Body) > 0 && body.Body[len(body.Body)-1] != '\n' {
				output.WriteByte('\n')
			}
		} else if slot.Default != "" {
			output.WriteString(indentSnippet(slot.Default, "\t"))
			if !strings.HasSuffix(slot.Default, "\n") {
				output.WriteByte('\n')
			}
		}
		fmt.Fprintf(&output, "\t%s\n", slotMarker(slotEndPrefix, slot.ID))
	}
	output.WriteString("}\n")
	fmt.Fprintf(&output, "%s\n", generatedMarker(generatedEndPrefix, activity.ID, "activity"))
	return output.String()
}
