package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

const defaultHeader = "// Code generated by gooo. DO NOT EDIT."

func (g Generator) renderBlocks(ir SemanticIR, previous parsedMarkers) (map[string][]byte, []string, error) {
	blocks := make(map[string][]byte, len(ir.Entities)+len(ir.Activities))
	order := make([]string, 0, len(ir.Entities)+len(ir.Activities))
	for _, entity := range ir.Entities {
		block, err := formatBlock(ir.Package, renderEntity(entity))
		if err != nil {
			return nil, nil, fmt.Errorf("generator: format entity %q: %w", entity.ID, err)
		}
		blocks[entity.ID] = block
		order = append(order, entity.ID)
	}
	for _, activity := range ir.Activities {
		block, err := formatBlock(ir.Package, renderActivity(activity, previous.Slots))
		if err != nil {
			return nil, nil, fmt.Errorf("generator: format activity %q: %w", activity.ID, err)
		}
		blocks[activity.ID] = block
		order = append(order, activity.ID)
	}
	return blocks, order, nil
}

func renderEntity(entity Entity) string {
	var output strings.Builder
	fmt.Fprintf(&output, "%s\n", generatedMarker(generatedStartPrefix, entity.ID, "entity"))
	if len(entity.Fields) == 0 {
		fmt.Fprintf(&output, "type %s struct{}\n", entity.GoName)
	} else {
		fmt.Fprintf(&output, "type %s struct {\n", entity.GoName)
		for _, field := range entity.Fields {
			fmt.Fprintf(&output, "\t%s %s\n", field.GoName, field.GoType)
		}
		output.WriteString("}\n")
	}
	fmt.Fprintf(&output, "%s\n", generatedMarker(generatedEndPrefix, entity.ID, "entity"))
	return output.String()
}

func renderActivity(activity Activity, previous map[string]parsedSlot) string {
	var output strings.Builder
	fmt.Fprintf(&output, "%s\n", generatedMarker(generatedStartPrefix, activity.ID, "activity"))
	fmt.Fprintf(&output, "func %s(%s)%s {\n", activity.GoName, renderInputs(activity.Inputs), renderOutputs(activity.Outputs))
	for _, slot := range activity.Slots {
		fmt.Fprintf(&output, "\t%s\n", slotMarker(slotStartPrefix, slot.ID))
		body, exists := previous[slot.ID]
		if exists {
			output.Write(body.Body)
			if len(body.Body) > 0 && body.Body[len(body.Body)-1] != '\n' {
				output.WriteByte('\n')
			}
		} else if slot.Default != "" {
			output.WriteString(indentSnippet(slot.Default, "\t"))
			if !strings.HasSuffix(slot.Default, "\n") {
				output.WriteByte('\n')
			}
		}
		fmt.Fprintf(&output, "\t%s\n", slotMarker(slotEndPrefix, slot.ID))
	}
	output.WriteString("}\n")
	fmt.Fprintf(&output, "%s\n", generatedMarker(generatedEndPrefix, activity.ID, "activity"))
	return output.String()
}

func renderInputs(inputs []Port) string {
	parts := make([]string, len(inputs))
	for index, input := range inputs {
		parts[index] = input.GoName + " " + input.GoType
	}
	return strings.Join(parts, ", ")
}

func renderOutputs(outputs []Port) string {
	switch len(outputs) {
	case 0:
		return ""
	case 1:
		return " " + outputs[0].GoType
	default:
		parts := make([]string, len(outputs))
		for index, output := range outputs {
			parts[index] = output.GoType
		}
		return " (" + strings.Join(parts, ", ") + ")"
	}
}

func indentSnippet(snippet, prefix string) string {
	lines := strings.Split(snippet, "\n")
	var output strings.Builder
	for index, line := range lines {
		if line != "" {
			output.WriteString(prefix)
		}
		output.WriteString(line)
		if index < len(lines)-1 {
			output.WriteByte('\n')
		}
	}
	return output.String()
}

func formatBlock(packageName, block string) ([]byte, error) {
	source := []byte("package " + packageName + "\n\n" + block)
	formatted, err := format.Source(source)
	if err != nil {
		return nil, err
	}
	marker := []byte(generatedStartPrefix)
	start := bytes.Index(formatted, marker)
	if start < 0 {
		return nil, fmt.Errorf("formatted block lost generated marker")
	}
	result := bytes.TrimLeft(formatted[start:], "\n")
	result = bytes.TrimRight(result, "\n")
	result = append(result, '\n')
	return result, nil
}

func (g Generator) renderNewFile(ir SemanticIR, blocks map[string][]byte, order []string) ([]byte, error) {
	header := g.Options.Header
	if header == "" {
		header = defaultHeader
	}
	var source strings.Builder
	source.WriteString(header)
	source.WriteString("\npackage ")
	source.WriteString(ir.Package)
	source.WriteString("\n")
	if len(ir.Imports) > 0 {
		source.WriteString("\nimport (\n")
		for _, item := range ir.Imports {
			if item.Name == "" {
				fmt.Fprintf(&source, "\t%s\n", quotePath(item.Path))
			} else {
				fmt.Fprintf(&source, "\t%s %s\n", item.Name, quotePath(item.Path))
			}
		}
		source.WriteString(")\n")
	}
	for _, id := range order {
		source.WriteString("\n")
		source.Write(blocks[id])
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("generator: format new file: %w", err)
	}
	return formatted, nil
}
