package metacircularboundary

import "github.com/kimjooyoon/meta-ontology-go/internal/meta/metacircularboundarycontract"

type Coordinate = metacircularboundarycontract.Coordinate
type SourceObservation = metacircularboundarycontract.SourceObservation
type Computation = metacircularboundarycontract.Computation
type GraphObservation = metacircularboundarycontract.GraphObservation
type TypedRelation = metacircularboundarycontract.TypedRelation
type EffectEvidence = metacircularboundarycontract.EffectEvidence
type EffectObservation = metacircularboundarycontract.EffectObservation
type ExternalGrantArtifact = metacircularboundarycontract.ExternalGrantArtifact
type ExternalGrant = metacircularboundarycontract.ExternalGrant
type Attempt = metacircularboundarycontract.Attempt
type CaseDefinition = metacircularboundarycontract.CaseDefinition
type CaseObservation = metacircularboundarycontract.CaseObservation
type ClaimTransition = metacircularboundarycontract.ClaimTransition
type ExecutionArtifact = metacircularboundarycontract.ExecutionArtifact
type Receipt = metacircularboundarycontract.Receipt
type CaseResult = metacircularboundarycontract.CaseResult
type Indicator = metacircularboundarycontract.Indicator
type Summary = metacircularboundarycontract.Summary
type Report = metacircularboundarycontract.Report
type MetaOperation = metacircularboundarycontract.MetaOperation
type Denominator = metacircularboundarycontract.Denominator
type Input = metacircularboundarycontract.Input
type ReplayEvidence = metacircularboundarycontract.ReplayEvidence
type JudgeReceipt = metacircularboundarycontract.JudgeReceipt
